// src/lib/vocab-library/concepts.ts
//
// The shared vocab picture library: one illustration per ENGLISH concept,
// reused by every language course and by the kids' games. Keying on the
// concept (not "le genou" / "la rodilla" / "das Knie") means one picture is
// generated once and every course points at it.
//
// Why it exists: lesson images used to come from Pexels stock photos, and a
// photo search for "knee" returns a whole footballer. Children need to see the
// one thing they are naming, so these are flat cartoon illustrations built to
// be unambiguous.
//
// Four kinds, each chosen for precision rather than convenience:
//   - "figure"  a part of the shared cartoon child, marked with a highlight
//               ring and cropped around it. A body part can't be shown alone —
//               a cropped hand and arm look identical.
//   - "object"  a standalone single-subject flat illustration (FLUX).
//   - "shape"   drawn with canvas. A model renders "diamond" as a gemstone.
//   - "numeral" drawn with canvas. Image models garble digits.
//   - `from`    an object whose picture already exists as a hand-verified game
//               tile in public/games/<theme>/ — copied in, never regenerated.
//
// Images live in Supabase Storage at lesson-images/vocab-library/<slug>.png.
// Generated and uploaded by scripts/generate-vocab-library.mjs.

export type Annotate = { x: number; y: number; size: number };

export interface Concept {
  /** Stable library key and filename. */
  slug: string;
  /** English label, shown in tooling. */
  label: string;
  kind: "figure" | "object" | "shape" | "numeral";
  /** Ring placement on the base figure, normalized 0-1. "figure" only. */
  annotate?: Annotate;
  /** Crop half-extent around the ring, normalized. "figure" only. */
  zoom?: number;
  /** FLUX prompt subject. "object" only, unless `from` is set. */
  prompt?: string;
  /** Copy an already-verified game tile instead of generating. */
  from?: { theme: string; slug: string };
  /** Which shape to draw. "shape" only. */
  shape?: string;
  /** Which number to draw. "numeral" only. */
  numeral?: number;
  /**
   * Set when a generated picture failed review — wrong subject, or text baked
   * into the image. Held concepts are never served to a lesson; regenerate
   * with `--force --only=<slug>` and clear the flag once the picture is good.
   */
  hold?: string;
  /** English phrasings that should resolve to this concept (lowercase). */
  aliases: string[];
}

// Ring coordinates are shared with the games' body theme
// (src/lib/games/curated/body.ts) — both read the same base figure.
export const CONCEPTS: Concept[] = [
  // — body parts, marked on the shared cartoon figure
  { slug: "head", label: "head", kind: "figure",
    annotate: { x: 0.5, y: 0.265, size: 0.135 }, zoom: 0.23,
    aliases: ["head", "heads", "child pointing at head", "the head"] },
  { slug: "hair", label: "hair", kind: "figure",
    annotate: { x: 0.5, y: 0.2, size: 0.06 }, zoom: 0.2,
    aliases: ["hair", "the hair"] },
  { slug: "eye", label: "eye", kind: "figure",
    annotate: { x: 0.452, y: 0.345, size: 0.026 }, zoom: 0.13,
    aliases: ["eye", "eyes", "eye close up", "eyes looking", "the eyes"] },
  { slug: "nose", label: "nose", kind: "figure",
    annotate: { x: 0.5, y: 0.368, size: 0.022 }, zoom: 0.13,
    aliases: ["nose", "noses", "the nose"] },
  { slug: "mouth", label: "mouth", kind: "figure",
    annotate: { x: 0.5, y: 0.397, size: 0.032 }, zoom: 0.13,
    aliases: ["mouth", "mouths", "the mouth"] },
  { slug: "ear", label: "ear", kind: "figure",
    annotate: { x: 0.41, y: 0.36, size: 0.024 }, zoom: 0.13,
    aliases: ["ear", "ears", "ear close up", "the ears"] },
  { slug: "cheek", label: "cheek", kind: "figure",
    annotate: { x: 0.44, y: 0.375, size: 0.028 }, zoom: 0.14,
    aliases: ["cheek", "cheeks"] },
  { slug: "neck", label: "neck", kind: "figure",
    annotate: { x: 0.5, y: 0.452, size: 0.028 }, zoom: 0.15,
    aliases: ["neck", "necks", "person touching neck", "the neck"] },
  { slug: "shoulder", label: "shoulder", kind: "figure",
    annotate: { x: 0.437, y: 0.462, size: 0.032 }, zoom: 0.17,
    aliases: ["shoulder", "shoulders", "shoulder close up", "the shoulders"] },
  { slug: "arm", label: "arm", kind: "figure",
    annotate: { x: 0.365, y: 0.425, size: 0.03 }, zoom: 0.2,
    aliases: ["arm", "arms", "arms raised in celebration", "the arms"] },
  { slug: "hand", label: "hand", kind: "figure",
    annotate: { x: 0.3, y: 0.405, size: 0.035 }, zoom: 0.16,
    aliases: ["hand", "hands", "hand waving", "the hands"] },
  { slug: "tummy", label: "tummy", kind: "figure",
    annotate: { x: 0.5, y: 0.55, size: 0.05 }, zoom: 0.22,
    aliases: ["tummy", "belly", "stomach", "belly showing", "the tummy"] },
  { slug: "leg", label: "leg", kind: "figure",
    annotate: { x: 0.44, y: 0.775, size: 0.062 }, zoom: 0.26,
    aliases: ["leg", "legs", "legs running", "the legs"] },
  { slug: "knee", label: "knee", kind: "figure",
    annotate: { x: 0.44, y: 0.782, size: 0.026 }, zoom: 0.12,
    aliases: ["knee", "knees", "knee bending", "the knees"] },
  { slug: "foot", label: "foot", kind: "figure",
    annotate: { x: 0.44, y: 0.85, size: 0.045 }, zoom: 0.18,
    aliases: ["foot", "feet", "the feet"] },

  // — animals (imported from the games' curated set)
  { slug: "cat", label: "cat", kind: "object", from: { theme: "animals", slug: "chat" },
    aliases: ["cat"] },
  { slug: "dog", label: "dog", kind: "object", from: { theme: "animals", slug: "chien" },
    aliases: ["dog"] },
  { slug: "cow", label: "cow", kind: "object", from: { theme: "animals", slug: "vache" },
    aliases: ["cow"] },
  { slug: "horse", label: "horse", kind: "object", from: { theme: "animals", slug: "cheval" },
    aliases: ["horse"] },
  { slug: "sheep", label: "sheep", kind: "object", from: { theme: "animals", slug: "mouton" },
    aliases: ["sheep"] },
  { slug: "pig", label: "pig", kind: "object", from: { theme: "animals", slug: "cochon" },
    aliases: ["pig"] },
  { slug: "rabbit", label: "rabbit", kind: "object", from: { theme: "animals", slug: "lapin" },
    aliases: ["rabbit"] },
  { slug: "duck", label: "duck", kind: "object", from: { theme: "animals", slug: "canard" },
    aliases: ["duck"] },
  { slug: "lion", label: "lion", kind: "object", from: { theme: "animals", slug: "lion" },
    aliases: ["lion"] },
  { slug: "elephant", label: "elephant", kind: "object", from: { theme: "animals", slug: "elephant" },
    aliases: ["elephant"] },
  { slug: "monkey", label: "monkey", kind: "object", from: { theme: "animals", slug: "singe" },
    aliases: ["monkey"] },
  { slug: "frog", label: "frog", kind: "object", from: { theme: "animals", slug: "grenouille" },
    aliases: ["frog"] },
  { slug: "bird", label: "bird", kind: "object", from: { theme: "animals", slug: "oiseau" },
    aliases: ["bird"] },
  { slug: "fish", label: "fish", kind: "object", from: { theme: "animals", slug: "poisson" },
    aliases: ["fish"] },
  { slug: "bear", label: "bear", kind: "object", from: { theme: "animals", slug: "ours" },
    aliases: ["bear"] },
  { slug: "tiger", label: "tiger", kind: "object", from: { theme: "animals", slug: "tigre" },
    aliases: ["tiger"] },
  { slug: "snake", label: "snake", kind: "object", from: { theme: "animals", slug: "serpent" },
    hold: "the games tile reads as a green crescent, not a snake",
    aliases: ["snake"] },
  { slug: "owl", label: "owl", kind: "object", from: { theme: "animals", slug: "hibou" },
    aliases: ["owl"] },
  { slug: "turtle", label: "turtle", kind: "object", from: { theme: "animals", slug: "tortue" },
    aliases: ["turtle"] },
  { slug: "giraffe", label: "giraffe", kind: "object", from: { theme: "animals", slug: "girafe" },
    aliases: ["giraffe"] },

  // — clothes (imported from the games' curated set)
  { slug: "t-shirt", label: "t-shirt", kind: "object", from: { theme: "clothes", slug: "tshirt" },
    aliases: ["t-shirt"] },
  { slug: "pants", label: "pants", kind: "object", from: { theme: "clothes", slug: "pantalon" },
    aliases: ["pants"] },
  { slug: "dress", label: "dress", kind: "object", from: { theme: "clothes", slug: "robe" },
    aliases: ["dress"] },
  { slug: "skirt", label: "skirt", kind: "object", from: { theme: "clothes", slug: "jupe" },
    aliases: ["skirt"] },
  { slug: "jacket", label: "jacket", kind: "object", from: { theme: "clothes", slug: "veste" },
    aliases: ["jacket"] },
  { slug: "sweater", label: "sweater", kind: "object", from: { theme: "clothes", slug: "pull" },
    aliases: ["sweater"] },
  { slug: "shoes", label: "shoes", kind: "object", from: { theme: "clothes", slug: "chaussures" },
    aliases: ["shoes"] },
  { slug: "socks", label: "socks", kind: "object", from: { theme: "clothes", slug: "chaussettes" },
    aliases: ["socks"] },
  { slug: "hat", label: "hat", kind: "object", from: { theme: "clothes", slug: "chapeau" },
    aliases: ["hat"] },
  { slug: "gloves", label: "gloves", kind: "object", from: { theme: "clothes", slug: "gants" },
    aliases: ["gloves"] },
  { slug: "scarf", label: "scarf", kind: "object", from: { theme: "clothes", slug: "echarpe" },
    aliases: ["scarf"] },
  { slug: "shorts", label: "shorts", kind: "object", from: { theme: "clothes", slug: "short" },
    aliases: ["shorts"] },
  { slug: "pajamas", label: "pajamas", kind: "object", from: { theme: "clothes", slug: "pyjama" },
    aliases: ["pajamas"] },
  { slug: "tie", label: "tie", kind: "object", from: { theme: "clothes", slug: "cravate" },
    aliases: ["tie"] },
  { slug: "boots", label: "boots", kind: "object", from: { theme: "clothes", slug: "bottes" },
    aliases: ["boots"] },

  // — colors (imported from the games' curated set)
  { slug: "red", label: "red", kind: "object", from: { theme: "colors", slug: "rouge" },
    aliases: ["red", "red object"] },
  { slug: "blue", label: "blue", kind: "object", from: { theme: "colors", slug: "bleu" },
    aliases: ["blue", "blue object"] },
  { slug: "green", label: "green", kind: "object", from: { theme: "colors", slug: "vert" },
    aliases: ["green", "green object"] },
  { slug: "yellow", label: "yellow", kind: "object", from: { theme: "colors", slug: "jaune" },
    aliases: ["yellow", "yellow object"] },
  { slug: "orange", label: "orange", kind: "object", from: { theme: "colors", slug: "orange" },
    aliases: ["orange", "orange object"] },
  { slug: "purple", label: "purple", kind: "object", from: { theme: "colors", slug: "violet" },
    aliases: ["purple", "purple object"] },
  { slug: "pink", label: "pink", kind: "object", from: { theme: "colors", slug: "rose" },
    aliases: ["pink", "pink object"] },
  { slug: "black", label: "black", kind: "object", from: { theme: "colors", slug: "noir" },
    aliases: ["black", "black object"] },
  { slug: "white", label: "white", kind: "object", from: { theme: "colors", slug: "blanc" },
    aliases: ["white", "white object"] },
  { slug: "brown", label: "brown", kind: "object", from: { theme: "colors", slug: "marron" },
    aliases: ["brown", "brown object"] },
  { slug: "grey", label: "grey", kind: "object", from: { theme: "colors", slug: "gris" },
    aliases: ["grey", "gray", "gray object", "grey object"] },

  // — food (imported from the games' curated set)
  { slug: "apple", label: "apple", kind: "object", from: { theme: "food", slug: "pomme" },
    aliases: ["apple"] },
  { slug: "banana", label: "banana", kind: "object", from: { theme: "food", slug: "banane" },
    aliases: ["banana"] },
  { slug: "orange-fruit", label: "orange (fruit)", kind: "object", from: { theme: "food", slug: "orange" },
    aliases: ["orange fruit", "orange on a table"] },
  { slug: "strawberry", label: "strawberry", kind: "object", from: { theme: "food", slug: "fraise" },
    aliases: ["strawberry"] },
  { slug: "grapes", label: "grapes", kind: "object", from: { theme: "food", slug: "raisin" },
    aliases: ["grapes"] },
  { slug: "watermelon", label: "watermelon", kind: "object", from: { theme: "food", slug: "pasteque" },
    aliases: ["watermelon"] },
  { slug: "bread", label: "bread", kind: "object", from: { theme: "food", slug: "pain" },
    aliases: ["bread"] },
  { slug: "cheese", label: "cheese", kind: "object", from: { theme: "food", slug: "fromage" },
    aliases: ["cheese"] },
  { slug: "cake", label: "cake", kind: "object", from: { theme: "food", slug: "gateau" },
    aliases: ["cake"] },
  { slug: "pizza", label: "pizza", kind: "object", from: { theme: "food", slug: "pizza" },
    aliases: ["pizza"] },
  { slug: "ice-cream", label: "ice cream", kind: "object", from: { theme: "food", slug: "glace" },
    aliases: ["ice cream"] },
  { slug: "carrot", label: "carrot", kind: "object", from: { theme: "food", slug: "carotte" },
    aliases: ["carrot"] },
  { slug: "tomato", label: "tomato", kind: "object", from: { theme: "food", slug: "tomate" },
    aliases: ["tomato"] },
  { slug: "egg", label: "egg", kind: "object", from: { theme: "food", slug: "oeuf" },
    aliases: ["egg"] },
  { slug: "milk", label: "milk", kind: "object", from: { theme: "food", slug: "lait" },
    aliases: ["milk"] },

  // — home (imported from the games' curated set)
  { slug: "house", label: "house", kind: "object", from: { theme: "home", slug: "maison" },
    aliases: ["house"] },
  { slug: "door", label: "door", kind: "object", from: { theme: "home", slug: "porte" },
    aliases: ["door"] },
  { slug: "window", label: "window", kind: "object", from: { theme: "home", slug: "fenetre" },
    aliases: ["window"] },
  { slug: "table", label: "table", kind: "object", from: { theme: "home", slug: "table" },
    aliases: ["table"] },
  { slug: "chair", label: "chair", kind: "object", from: { theme: "home", slug: "chaise" },
    aliases: ["chair"] },
  { slug: "bed", label: "bed", kind: "object", from: { theme: "home", slug: "lit" },
    aliases: ["bed"] },
  { slug: "lamp", label: "lamp", kind: "object", from: { theme: "home", slug: "lampe" },
    aliases: ["lamp"] },
  { slug: "key", label: "key", kind: "object", from: { theme: "home", slug: "cle" },
    aliases: ["key"] },
  { slug: "clock", label: "clock", kind: "object", from: { theme: "home", slug: "horloge" },
    aliases: ["clock"] },
  { slug: "plate", label: "plate", kind: "object", from: { theme: "home", slug: "assiette" },
    aliases: ["plate"] },
  { slug: "cup", label: "cup", kind: "object", from: { theme: "home", slug: "tasse" },
    aliases: ["cup"] },
  { slug: "spoon", label: "spoon", kind: "object", from: { theme: "home", slug: "cuillere" },
    aliases: ["spoon"] },
  { slug: "fork", label: "fork", kind: "object", from: { theme: "home", slug: "fourchette" },
    aliases: ["fork"] },
  { slug: "mirror", label: "mirror", kind: "object", from: { theme: "home", slug: "miroir" },
    aliases: ["mirror"] },

  // — nature (imported from the games' curated set)
  { slug: "tree", label: "tree", kind: "object", from: { theme: "nature", slug: "arbre" },
    aliases: ["tree"] },
  { slug: "flower", label: "flower", kind: "object", from: { theme: "nature", slug: "fleur" },
    aliases: ["flower"] },
  { slug: "leaf", label: "leaf", kind: "object", from: { theme: "nature", slug: "feuille" },
    aliases: ["leaf"] },
  { slug: "mountain", label: "mountain", kind: "object", from: { theme: "nature", slug: "montagne" },
    aliases: ["mountain"] },
  { slug: "river", label: "river", kind: "object", from: { theme: "nature", slug: "riviere" },
    aliases: ["river"] },
  { slug: "moon", label: "moon", kind: "object", from: { theme: "nature", slug: "lune" },
    aliases: ["moon"] },
  { slug: "star", label: "star", kind: "object", from: { theme: "nature", slug: "etoile" },
    aliases: ["star"] },
  { slug: "grass", label: "grass", kind: "object", from: { theme: "nature", slug: "herbe" },
    aliases: ["grass"] },
  { slug: "stone", label: "stone", kind: "object", from: { theme: "nature", slug: "pierre" },
    aliases: ["stone"] },
  { slug: "mushroom", label: "mushroom", kind: "object", from: { theme: "nature", slug: "champignon" },
    aliases: ["mushroom"] },
  { slug: "cactus", label: "cactus", kind: "object", from: { theme: "nature", slug: "cactus" },
    aliases: ["cactus"] },
  { slug: "pine-tree", label: "pine tree", kind: "object", from: { theme: "nature", slug: "sapin" },
    aliases: ["pine tree"] },

  // — numbers (imported from the games' curated set)
  { slug: "one", label: "one", kind: "object", from: { theme: "numbers", slug: "un" },
    aliases: ["one"] },
  { slug: "two", label: "two", kind: "object", from: { theme: "numbers", slug: "deux" },
    aliases: ["two"] },
  { slug: "three", label: "three", kind: "object", from: { theme: "numbers", slug: "trois" },
    aliases: ["three"] },
  { slug: "four", label: "four", kind: "object", from: { theme: "numbers", slug: "quatre" },
    aliases: ["four"] },
  { slug: "five", label: "five", kind: "object", from: { theme: "numbers", slug: "cinq" },
    aliases: ["five"] },
  { slug: "six", label: "six", kind: "object", from: { theme: "numbers", slug: "six" },
    aliases: ["six"] },
  { slug: "seven", label: "seven", kind: "object", from: { theme: "numbers", slug: "sept" },
    aliases: ["seven"] },
  { slug: "eight", label: "eight", kind: "object", from: { theme: "numbers", slug: "huit" },
    aliases: ["eight"] },
  { slug: "nine", label: "nine", kind: "object", from: { theme: "numbers", slug: "neuf" },
    aliases: ["nine"] },
  { slug: "ten", label: "ten", kind: "object", from: { theme: "numbers", slug: "dix" },
    aliases: ["ten"] },

  // — sports (imported from the games' curated set)
  { slug: "football", label: "football", kind: "object", from: { theme: "sports", slug: "football" },
    aliases: ["football"] },
  { slug: "basketball", label: "basketball", kind: "object", from: { theme: "sports", slug: "basket" },
    aliases: ["basketball"] },
  { slug: "tennis", label: "tennis", kind: "object", from: { theme: "sports", slug: "tennis" },
    aliases: ["tennis"] },
  { slug: "swimming", label: "swimming", kind: "object", from: { theme: "sports", slug: "natation" },
    aliases: ["swimming"] },
  { slug: "cycling", label: "cycling", kind: "object", from: { theme: "sports", slug: "velo" },
    aliases: ["cycling"] },
  { slug: "skiing", label: "skiing", kind: "object", from: { theme: "sports", slug: "ski" },
    aliases: ["skiing"] },
  { slug: "skating", label: "skating", kind: "object", from: { theme: "sports", slug: "patins" },
    aliases: ["skating"] },
  { slug: "boxing", label: "boxing", kind: "object", from: { theme: "sports", slug: "boxe" },
    aliases: ["boxing"] },
  { slug: "medal", label: "medal", kind: "object", from: { theme: "sports", slug: "medaille" },
    aliases: ["medal"] },
  { slug: "trophy", label: "trophy", kind: "object", from: { theme: "sports", slug: "trophee" },
    aliases: ["trophy"] },
  { slug: "stopwatch", label: "stopwatch", kind: "object", from: { theme: "sports", slug: "chronometre" },
    aliases: ["stopwatch"] },
  { slug: "dumbbell", label: "dumbbell", kind: "object", from: { theme: "sports", slug: "haltere" },
    aliases: ["dumbbell"] },

  // — travel (imported from the games' curated set)
  { slug: "car", label: "car", kind: "object", from: { theme: "travel", slug: "voiture" },
    aliases: ["car"] },
  { slug: "bus", label: "bus", kind: "object", from: { theme: "travel", slug: "bus" },
    aliases: ["bus"] },
  { slug: "train", label: "train", kind: "object", from: { theme: "travel", slug: "train" },
    aliases: ["train"] },
  { slug: "plane", label: "plane", kind: "object", from: { theme: "travel", slug: "avion" },
    aliases: ["plane"] },
  { slug: "bicycle", label: "bicycle", kind: "object", from: { theme: "travel", slug: "velo" },
    aliases: ["bicycle"] },
  { slug: "boat", label: "boat", kind: "object", from: { theme: "travel", slug: "bateau" },
    aliases: ["boat"] },
  { slug: "truck", label: "truck", kind: "object", from: { theme: "travel", slug: "camion" },
    aliases: ["truck"] },
  { slug: "motorcycle", label: "motorcycle", kind: "object", from: { theme: "travel", slug: "moto" },
    aliases: ["motorcycle"] },
  { slug: "helicopter", label: "helicopter", kind: "object", from: { theme: "travel", slug: "helicoptere" },
    aliases: ["helicopter"] },
  { slug: "rocket", label: "rocket", kind: "object", from: { theme: "travel", slug: "fusee" },
    aliases: ["rocket"] },
  { slug: "suitcase", label: "suitcase", kind: "object", from: { theme: "travel", slug: "valise" },
    aliases: ["suitcase"] },
  { slug: "map", label: "map", kind: "object", from: { theme: "travel", slug: "carte" },
    aliases: ["map"] },

  // — weather (imported from the games' curated set)
  { slug: "sun", label: "sun", kind: "object", from: { theme: "weather", slug: "soleil" },
    aliases: ["sun"] },
  { slug: "cloud", label: "cloud", kind: "object", from: { theme: "weather", slug: "nuage" },
    aliases: ["cloud"] },
  { slug: "rain", label: "rain", kind: "object", from: { theme: "weather", slug: "pluie" },
    aliases: ["rain"] },
  { slug: "snow", label: "snow", kind: "object", from: { theme: "weather", slug: "neige" },
    aliases: ["snow"] },
  { slug: "storm", label: "storm", kind: "object", from: { theme: "weather", slug: "orage" },
    aliases: ["storm"] },
  { slug: "wind", label: "wind", kind: "object", from: { theme: "weather", slug: "vent" },
    aliases: ["wind"] },
  { slug: "rainbow", label: "rainbow", kind: "object", from: { theme: "weather", slug: "arcenciel" },
    aliases: ["rainbow"] },
  { slug: "umbrella", label: "umbrella", kind: "object", from: { theme: "weather", slug: "parapluie" },
    aliases: ["umbrella"] },
  { slug: "ice", label: "ice", kind: "object", from: { theme: "weather", slug: "glace" },
    aliases: ["ice"] },
  { slug: "fog", label: "fog", kind: "object", from: { theme: "weather", slug: "brouillard" },
    aliases: ["fog"] },

  // — animals and minibeasts
  { slug: "crocodile", label: "crocodile", kind: "object",
    prompt: "a crocodile",
    aliases: ["crocodile"] },
  { slug: "zebra", label: "zebra", kind: "object",
    prompt: "a zebra",
    aliases: ["zebra"] },
  { slug: "rhinoceros", label: "rhinoceros", kind: "object",
    prompt: "a rhinoceros",
    aliases: ["rhinoceros", "rhino"] },
  { slug: "hippopotamus", label: "hippopotamus", kind: "object",
    prompt: "a hippopotamus",
    aliases: ["hippopotamus", "hippo"] },
  { slug: "wolf", label: "wolf", kind: "object",
    prompt: "a grey wolf",
    aliases: ["wolf", "loup"] },
  { slug: "parrot", label: "parrot", kind: "object",
    prompt: "a colourful parrot",
    aliases: ["parrot"] },
  { slug: "hamster", label: "hamster", kind: "object",
    prompt: "a hamster",
    aliases: ["hamster"] },
  { slug: "goat", label: "goat", kind: "object",
    prompt: "a goat",
    aliases: ["goat"] },
  { slug: "hedgehog", label: "hedgehog", kind: "object",
    prompt: "a hedgehog",
    aliases: ["hedgehog"] },
  { slug: "kangaroo", label: "kangaroo", kind: "object",
    prompt: "a kangaroo",
    aliases: ["kangaroo"] },
  { slug: "hen", label: "hen", kind: "object",
    prompt: "a hen, a female chicken",
    aliases: ["chicken", "hen"] },
  { slug: "ant", label: "ant", kind: "object",
    prompt: "a single ant seen from the side",
    hold: "generated with the word 'ant' printed on it",
    aliases: ["ant"] },
  { slug: "butterfly", label: "butterfly", kind: "object",
    prompt: "a butterfly with open wings",
    aliases: ["butterfly"] },
  { slug: "ladybug", label: "ladybug", kind: "object",
    prompt: "a red ladybug with black spots",
    aliases: ["ladybug", "ladybird"] },
  { slug: "mosquito", label: "mosquito", kind: "object",
    prompt: "a mosquito",
    aliases: ["mosquito"] },
  { slug: "dragonfly", label: "dragonfly", kind: "object",
    prompt: "a dragonfly with open wings",
    aliases: ["dragonfly"] },
  { slug: "grasshopper", label: "grasshopper", kind: "object",
    prompt: "a green grasshopper",
    aliases: ["grasshopper"] },
  { slug: "snail", label: "snail", kind: "object",
    prompt: "a snail with its shell",
    aliases: ["snail"] },
  { slug: "goldfish", label: "goldfish", kind: "object",
    prompt: "a goldfish in a round fish bowl",
    aliases: ["goldfish"] },

  // — fruit and vegetables
  { slug: "pineapple", label: "pineapple", kind: "object",
    prompt: "a whole pineapple",
    aliases: ["pineapple"] },
  { slug: "cherry", label: "cherry", kind: "object",
    prompt: "two cherries joined at the stem",
    aliases: ["cherry", "cherries"] },
  { slug: "melon", label: "melon", kind: "object",
    prompt: "a melon cut in half",
    aliases: ["melon"] },
  { slug: "potato", label: "potato", kind: "object",
    prompt: "a single brown potato",
    aliases: ["potato", "potatoes"] },
  { slug: "onion", label: "onion", kind: "object",
    prompt: "a single brown onion",
    aliases: ["onion", "onions"] },
  { slug: "bell-pepper", label: "bell pepper", kind: "object",
    prompt: "a single red bell pepper",
    aliases: ["bell pepper", "bell peppers", "pepper"] },

  // — food and drink
  // Cooked dishes are kept apart from the live animal on purpose: a food
  // lesson's "plate of chicken" must not show a hen in a farmyard.
  { slug: "chicken-meat", label: "chicken (meat)", kind: "object",
    prompt: "a cooked roast chicken drumstick on a white plate",
    aliases: ["plate of chicken", "chicken meat", "roast chicken"] },
  { slug: "fish-dish", label: "fish (dish)", kind: "object",
    prompt: "a cooked fish fillet on a white plate with a slice of lemon",
    aliases: ["plate of fish", "cooked fish", "fish dish"] },
  { slug: "chocolate", label: "chocolate", kind: "object",
    prompt: "a bar of chocolate broken into squares",
    aliases: ["chocolate"] },
  { slug: "tea", label: "tea", kind: "object",
    prompt: "a cup of hot tea with a tea bag label",
    aliases: ["tea"] },
  { slug: "coffee", label: "coffee", kind: "object",
    prompt: "a cup of black coffee on a saucer",
    aliases: ["coffee"] },
  { slug: "pasta", label: "pasta", kind: "object",
    prompt: "a bowl of spaghetti pasta",
    aliases: ["pasta", "noodles"] },
  { slug: "salad", label: "salad", kind: "object",
    prompt: "a bowl of green salad",
    aliases: ["salad"] },
  { slug: "rice", label: "rice", kind: "object",
    prompt: "a bowl of white rice",
    aliases: ["rice"] },
  { slug: "meat", label: "meat", kind: "object",
    prompt: "a raw steak of red meat",
    aliases: ["meat"] },
  { slug: "ham", label: "ham", kind: "object",
    prompt: "slices of pink ham",
    aliases: ["ham"] },
  { slug: "butter", label: "butter", kind: "object",
    prompt: "a block of butter on a dish",
    aliases: ["butter"] },
  { slug: "jam", label: "jam", kind: "object",
    prompt: "a jar of red strawberry jam",
    hold: "generated a busy tiled pattern, not a single subject",
    aliases: ["jam"] },
  { slug: "juice", label: "juice", kind: "object",
    prompt: "a glass of orange juice",
    hold: "generated with garbled text on the glass",
    aliases: ["juice"] },
  { slug: "soup", label: "soup", kind: "object",
    prompt: "a bowl of hot soup with a spoon",
    aliases: ["soup"] },
  { slug: "sandwich", label: "sandwich", kind: "object",
    prompt: "a sandwich cut in half",
    aliases: ["sandwich"] },
  { slug: "cookies", label: "cookies", kind: "object",
    prompt: "three round chocolate chip cookies",
    aliases: ["cookies", "cookie", "biscuits"] },
  { slug: "cupcake", label: "cupcake", kind: "object",
    prompt: "a cupcake with pink frosting in a paper case",
    aliases: ["cupcake"] },
  { slug: "pancakes", label: "pancakes", kind: "object",
    prompt: "a stack of pancakes with syrup",
    aliases: ["pancakes", "pancake"] },
  { slug: "lollipop", label: "lollipop", kind: "object",
    prompt: "a round swirl lollipop on a stick",
    aliases: ["lollipop"] },
  { slug: "pudding", label: "pudding", kind: "object",
    prompt: "a cup of chocolate pudding dessert",
    aliases: ["pudding"] },
  { slug: "sugar", label: "sugar", kind: "object",
    prompt: "a bowl of white sugar with sugar cubes",
    aliases: ["sugar"] },
  { slug: "flour", label: "flour", kind: "object",
    prompt: "a paper bag of white flour, open at the top",
    aliases: ["flour"] },
  { slug: "seafood", label: "seafood", kind: "object",
    prompt: "a plate of prawns and mussels",
    aliases: ["seafood"] },
  { slug: "dough", label: "dough", kind: "object",
    prompt: "a ball of bread dough on a floured board",
    aliases: ["dough"] },

  // — home, kitchen and bathroom
  { slug: "sofa", label: "sofa", kind: "object",
    prompt: "a two-seater sofa seen from the front",
    aliases: ["sofa", "couch"] },
  { slug: "armchair", label: "armchair", kind: "object",
    prompt: "a single soft armchair",
    aliases: ["armchair"] },
  { slug: "rug", label: "rug", kind: "object",
    prompt: "a rectangular patterned rug lying flat",
    aliases: ["rug", "carpet"] },
  { slug: "television", label: "television", kind: "object",
    prompt: "a flat screen television on a stand",
    aliases: ["television", "tv"] },
  { slug: "painting", label: "painting", kind: "object",
    prompt: "a framed picture hanging on a wall",
    aliases: ["painting"] },
  { slug: "shelf", label: "shelf", kind: "object",
    prompt: "a wall shelf holding a row of books",
    aliases: ["shelf", "bookshelf"] },
  { slug: "desk", label: "desk", kind: "object",
    prompt: "a writing desk with a chair",
    aliases: ["desk"] },
  { slug: "wardrobe", label: "wardrobe", kind: "object",
    prompt: "a tall wooden wardrobe with closed doors",
    aliases: ["wardrobe", "closet"] },
  { slug: "wall", label: "wall", kind: "object",
    prompt: "a brick wall of a house",
    hold: "generated a whole house instead of a wall",
    aliases: ["wall"] },
  { slug: "roof", label: "roof", kind: "object",
    prompt: "the red tiled roof of a small house",
    aliases: ["roof"] },
  { slug: "stairs", label: "stairs", kind: "object",
    prompt: "a staircase with wooden steps",
    aliases: ["stairs", "staircase"] },
  { slug: "chimney", label: "chimney", kind: "object",
    prompt: "a brick chimney on a house roof",
    aliases: ["chimney"] },
  { slug: "fence", label: "fence", kind: "object",
    prompt: "a white garden fence",
    aliases: ["fence"] },
  { slug: "oven", label: "oven", kind: "object",
    prompt: "a kitchen oven with a glass door",
    aliases: ["oven"] },
  { slug: "refrigerator", label: "refrigerator", kind: "object",
    prompt: "a tall kitchen refrigerator with the door closed",
    aliases: ["refrigerator", "fridge"] },
  { slug: "frying-pan", label: "frying pan", kind: "object",
    prompt: "a frying pan seen from above",
    aliases: ["frying pan", "pan"] },
  { slug: "cupboard", label: "cupboard", kind: "object",
    prompt: "a kitchen cupboard with two doors",
    aliases: ["cupboard"] },
  { slug: "trash-can", label: "trash can", kind: "object",
    prompt: "a closed kitchen trash can",
    aliases: ["trash can", "bin", "rubbish bin"] },
  { slug: "bowl", label: "bowl", kind: "object",
    prompt: "an empty round bowl",
    aliases: ["bowl"] },
  { slug: "knife", label: "knife", kind: "object",
    prompt: "a single table knife",
    aliases: ["knife"] },
  { slug: "soap", label: "soap", kind: "object",
    prompt: "a bar of soap with bubbles",
    hold: "generated with the word 'SOAP' printed on it",
    aliases: ["soap"] },
  { slug: "towel", label: "towel", kind: "object",
    prompt: "a folded bath towel",
    hold: "generated with 'Bath towel' printed on it",
    aliases: ["towel"] },
  { slug: "bathtub", label: "bathtub", kind: "object",
    prompt: "a white bathtub full of water",
    aliases: ["bathtub", "bath"] },
  { slug: "toilet", label: "toilet", kind: "object",
    prompt: "a white toilet seen from the side",
    aliases: ["toilet"] },
  { slug: "sink", label: "sink", kind: "object",
    prompt: "a bathroom sink with a tap",
    aliases: ["sink", "washbasin"] },

  // — school, toys and objects
  { slug: "book", label: "book", kind: "object",
    prompt: "a closed hardback book",
    aliases: ["book"] },
  { slug: "notebook", label: "notebook", kind: "object",
    prompt: "a spiral notebook",
    aliases: ["notebook"] },
  { slug: "backpack", label: "backpack", kind: "object",
    prompt: "a school backpack",
    aliases: ["backpack", "school bag"] },
  { slug: "board", label: "board", kind: "object",
    prompt: "a classroom whiteboard on a stand, blank",
    aliases: ["board", "whiteboard"] },
  { slug: "flag", label: "flag", kind: "object",
    prompt: "a plain flag on a flagpole",
    aliases: ["flag"] },
  { slug: "stuffed-animal", label: "stuffed animal", kind: "object",
    prompt: "a soft teddy bear toy",
    aliases: ["stuffed animal", "teddy bear", "soft toy"] },
  { slug: "puzzle", label: "puzzle", kind: "object",
    prompt: "four jigsaw puzzle pieces",
    aliases: ["puzzle", "jigsaw"] },
  { slug: "blocks", label: "blocks", kind: "object",
    prompt: "a stack of coloured wooden toy building blocks",
    aliases: ["blocks", "building blocks"] },
  { slug: "rocking-horse", label: "rocking horse", kind: "object",
    prompt: "a wooden rocking horse toy",
    aliases: ["rocking horse"] },
  { slug: "yo-yo", label: "yo-yo", kind: "object",
    prompt: "a yo-yo on its string",
    aliases: ["yo yo", "yo-yo"] },
  { slug: "xylophone", label: "xylophone", kind: "object",
    prompt: "a colourful toy xylophone with beaters",
    aliases: ["xylophone"] },
  { slug: "money", label: "money", kind: "object",
    prompt: "banknotes and coins",
    aliases: ["money", "dollar", "cash"] },
  { slug: "iceberg", label: "iceberg", kind: "object",
    prompt: "an iceberg floating in the sea",
    aliases: ["iceberg"] },

  // — clothes
  { slug: "coat", label: "coat", kind: "object",
    prompt: "a long winter coat",
    aliases: ["coat"] },
  { slug: "cap", label: "cap", kind: "object",
    prompt: "a baseball cap",
    aliases: ["cap"] },
  { slug: "blouse", label: "blouse", kind: "object",
    prompt: "a woman's blouse",
    aliases: ["blouse"] },
  { slug: "shirt", label: "shirt", kind: "object",
    prompt: "a button-up shirt",
    aliases: ["shirt"] },

  // — shops and places
  { slug: "store", label: "store", kind: "object",
    prompt: "the front of a small shop with an awning",
    aliases: ["store", "shop"] },
  { slug: "bookstore", label: "bookstore", kind: "object",
    prompt: "the front of a bookshop with books in the window",
    aliases: ["bookstore", "book shop"] },
  { slug: "supermarket", label: "supermarket", kind: "object",
    prompt: "a supermarket aisle with shelves of groceries",
    aliases: ["supermarket"] },
  { slug: "market", label: "market", kind: "object",
    prompt: "an outdoor market stall with fruit and vegetables",
    aliases: ["market"] },
  { slug: "shopping-mall", label: "shopping mall", kind: "object",
    prompt: "the inside of a shopping mall with shops on two floors",
    aliases: ["shopping mall", "mall"] },
  { slug: "clothing-store", label: "clothing store", kind: "object",
    prompt: "a clothes shop with racks of clothing",
    aliases: ["clothing store", "clothes shop", "boutique"] },
  { slug: "electronics-store", label: "electronics store", kind: "object",
    prompt: "an electronics shop with televisions and computers on display",
    aliases: ["electronics store"] },

  // — sports
  { slug: "baseball", label: "baseball", kind: "object",
    prompt: "a baseball and a baseball bat",
    aliases: ["baseball"] },
  { slug: "golf", label: "golf", kind: "object",
    prompt: "a golf ball on a tee with a golf club",
    aliases: ["golf"] },
  { slug: "volleyball", label: "volleyball", kind: "object",
    prompt: "a volleyball and a net",
    aliases: ["volleyball"] },
  { slug: "badminton", label: "badminton", kind: "object",
    prompt: "a badminton racket and a shuttlecock",
    aliases: ["badminton"] },
  { slug: "ice-hockey", label: "ice hockey", kind: "object",
    prompt: "an ice hockey stick and puck",
    aliases: ["ice hockey"] },
  { slug: "athletics", label: "athletics", kind: "object",
    prompt: "a running track with a starting block",
    aliases: ["athletics"] },
  { slug: "climbing", label: "climbing", kind: "object",
    prompt: "a climber on a climbing wall",
    aliases: ["climbing"] },
  { slug: "gymnastics", label: "gymnastics", kind: "object",
    prompt: "a gymnast doing a handstand on a beam",
    aliases: ["gymnastics"] },

  // — seasons and weather
  { slug: "spring", label: "spring", kind: "object",
    prompt: "a spring scene with blossom trees and flowers",
    aliases: ["spring"] },
  { slug: "summer", label: "summer", kind: "object",
    prompt: "a summer beach scene with a bright sun",
    aliases: ["summer"] },
  { slug: "autumn", label: "autumn", kind: "object",
    prompt: "an autumn scene with orange falling leaves",
    aliases: ["autumn", "fall"] },
  { slug: "winter", label: "winter", kind: "object",
    prompt: "a winter scene with snow on bare trees",
    aliases: ["winter"] },
  { slug: "sunny", label: "sunny", kind: "object",
    prompt: "a bright sun in a clear blue sky",
    aliases: ["sunny"] },
  { slug: "rainy", label: "rainy", kind: "object",
    prompt: "rain falling from a grey cloud onto the ground",
    aliases: ["rainy", "it is raining"] },
  { slug: "snowy", label: "snowy", kind: "object",
    prompt: "snowflakes falling from a cloud onto snowy ground",
    aliases: ["snowy", "it is snowing"] },
  { slug: "windy", label: "windy", kind: "object",
    prompt: "a tree bending in strong wind with leaves blowing",
    aliases: ["windy"] },
  { slug: "stormy", label: "stormy", kind: "object",
    prompt: "a dark storm cloud with a lightning bolt",
    aliases: ["stormy"] },
  { slug: "foggy", label: "foggy", kind: "object",
    prompt: "a road disappearing into thick grey fog",
    aliases: ["foggy"] },
  { slug: "cloudy", label: "cloudy", kind: "object",
    prompt: "a sky full of grey clouds",
    aliases: ["cloudy"] },
  { slug: "hot", label: "hot", kind: "object",
    prompt: "a thermometer showing a high temperature next to a blazing sun",
    aliases: ["hot"] },
  { slug: "cold", label: "cold", kind: "object",
    prompt: "a thermometer showing a low temperature next to a snowflake",
    aliases: ["cold"] },

  // — emotions
  { slug: "happy", label: "happy", kind: "object",
    prompt: "a cartoon child smiling happily, head and shoulders",
    aliases: ["happy"] },
  { slug: "sad", label: "sad", kind: "object",
    prompt: "a cartoon child crying with a sad face, head and shoulders",
    aliases: ["sad"] },
  { slug: "angry", label: "angry", kind: "object",
    prompt: "a cartoon child with an angry frowning face, head and shoulders",
    aliases: ["angry"] },
  { slug: "scared", label: "scared", kind: "object",
    prompt: "a cartoon child looking frightened with wide eyes, head and shoulders",
    aliases: ["scared", "frightened", "afraid"] },
  { slug: "worried", label: "worried", kind: "object",
    prompt: "a cartoon child looking worried and biting a lip, head and shoulders",
    aliases: ["worried"] },
  { slug: "surprised", label: "surprised", kind: "object",
    prompt: "a cartoon child with a surprised open mouth and raised eyebrows, head and shoulders",
    aliases: ["surprised"] },
  { slug: "calm", label: "calm", kind: "object",
    prompt: "a cartoon child with a calm peaceful face and closed eyes, head and shoulders",
    aliases: ["calm"] },
  { slug: "tired", label: "tired", kind: "object",
    prompt: "a cartoon child yawning and rubbing an eye, head and shoulders",
    aliases: ["tired"] },
  { slug: "hungry", label: "hungry", kind: "object",
    prompt: "a cartoon child holding a rumbling tummy and looking hungry",
    aliases: ["hungry", "hunger"] },

  // — family and people
  { slug: "mother", label: "mother", kind: "object",
    prompt: "a cartoon mother holding her young child",
    aliases: ["mother", "mum", "mom"] },
  { slug: "father", label: "father", kind: "object",
    prompt: "a cartoon father holding his young child",
    aliases: ["father", "dad"] },
  { slug: "grandmother", label: "grandmother", kind: "object",
    prompt: "a smiling cartoon grandmother with grey hair and glasses",
    aliases: ["grandmother", "grandma"] },
  { slug: "grandfather", label: "grandfather", kind: "object",
    prompt: "a smiling cartoon grandfather with grey hair and a moustache",
    aliases: ["grandfather", "grandpa"] },
  { slug: "sister", label: "sister", kind: "object",
    prompt: "two cartoon sisters standing together",
    aliases: ["sister"] },
  { slug: "brother", label: "brother", kind: "object",
    prompt: "two cartoon brothers standing together",
    aliases: ["brother"] },
  { slug: "baby", label: "baby", kind: "object",
    prompt: "a cartoon baby sitting on the floor",
    aliases: ["baby"] },
  { slug: "friend", label: "friend", kind: "object",
    prompt: "two cartoon children standing side by side with their arms around each other",
    aliases: ["friend", "friend masc", "friend fem"] },
  { slug: "best-friend", label: "best friend", kind: "object",
    prompt: "two cartoon children laughing together and doing a high five",
    aliases: ["best friend masc", "best friend fem", "best friend"] },
  { slug: "classmate", label: "classmate", kind: "object",
    prompt: "two cartoon children sitting together at a school desk",
    aliases: ["classmate"] },
  { slug: "neighbor", label: "neighbor", kind: "object",
    prompt: "two cartoon people waving to each other over a garden fence",
    aliases: ["neighbor", "neighbour", "neighbor masc", "neighbor fem"] },

  // — actions
  { slug: "to-read", label: "to read", kind: "object",
    prompt: "a cartoon child sitting and reading an open book",
    aliases: ["to read", "reading", "she is reading"] },
  { slug: "to-paint", label: "to paint", kind: "object",
    prompt: "a cartoon child painting a picture at an easel with a brush",
    aliases: ["to paint", "painting a picture", "she is painting"] },
  { slug: "to-draw", label: "to draw", kind: "object",
    prompt: "a cartoon child drawing on paper with a pencil",
    aliases: ["to draw", "drawing"] },
  { slug: "to-dance", label: "to dance", kind: "object",
    prompt: "a cartoon child dancing with arms in the air",
    aliases: ["to dance", "dancing", "he is dancing"] },
  { slug: "to-cook", label: "to cook", kind: "object",
    prompt: "a cartoon child cooking at a pot on a stove",
    aliases: ["to cook", "cooking", "cook"] },
  { slug: "to-sing", label: "to sing", kind: "object",
    prompt: "a cartoon child singing into a microphone",
    aliases: ["to sing", "singing"] },
  { slug: "to-sleep", label: "to sleep", kind: "object",
    prompt: "a cartoon child asleep in bed under a blanket",
    aliases: ["to sleep", "sleeping"] },
  { slug: "to-jump", label: "to jump", kind: "object",
    prompt: "a cartoon child jumping in the air with both feet off the ground",
    aliases: ["jump", "to jump", "jumping"] },
  { slug: "to-run", label: "to run", kind: "object",
    prompt: "a cartoon child running fast",
    aliases: ["running", "to run"] },
  { slug: "to-swim", label: "to swim", kind: "object",
    prompt: "a cartoon child swimming in a swimming pool",
    aliases: ["to swim"] },
  { slug: "to-travel", label: "to travel", kind: "object",
    prompt: "a cartoon child pulling a suitcase at an airport",
    aliases: ["to travel", "travelling"] },
  { slug: "to-listen-to-music", label: "to listen to music", kind: "object",
    prompt: "a cartoon child wearing headphones and listening to music",
    aliases: ["to listen to music", "listening to music"] },
  { slug: "to-watch-television", label: "to watch television", kind: "object",
    prompt: "a cartoon child sitting on a sofa watching television",
    aliases: ["to watch television", "watching television"] },
  { slug: "to-ride-a-bike", label: "to ride a bike", kind: "object",
    prompt: "a cartoon child riding a bicycle",
    aliases: ["to ride a bike", "riding a bike"] },
  { slug: "to-take-a-walk", label: "to take a walk", kind: "object",
    prompt: "a cartoon child walking along a path in a park",
    aliases: ["to take a walk", "going for a walk"] },
  { slug: "to-have-a-picnic", label: "to have a picnic", kind: "object",
    prompt: "a cartoon child sitting on a picnic blanket with a picnic basket",
    aliases: ["to have a picnic", "picnic"] },
  { slug: "to-roller-skate", label: "to roller skate", kind: "object",
    prompt: "a cartoon child roller skating",
    aliases: ["to roller skate", "roller skating"] },
  { slug: "to-play-video-games", label: "to play video games", kind: "object",
    prompt: "a cartoon child holding a game controller in front of a screen",
    aliases: ["to play video games", "playing video games"] },
  { slug: "to-do-origami", label: "to do origami", kind: "object",
    prompt: "a cartoon child folding a paper origami crane",
    aliases: ["to do origami", "origami"] },
  { slug: "to-garden", label: "to do gardening", kind: "object",
    prompt: "a cartoon child watering plants in a garden with a watering can",
    aliases: ["i do gardening", "gardening", "to do gardening"] },
  { slug: "to-play-with-blocks", label: "to play with blocks", kind: "object",
    prompt: "a cartoon child sitting on the floor building a tower of toy blocks",
    aliases: ["he is playing with blocks", "playing with blocks"] },

  // — classroom commands
  { slug: "close-your-eyes", label: "close your eyes", kind: "object",
    prompt: "a cartoon child standing with both eyes closed tight, head and shoulders",
    aliases: ["close your eyes"] },
  { slug: "open-your-mouth", label: "open your mouth", kind: "object",
    prompt: "a cartoon child standing with mouth wide open, head and shoulders",
    aliases: ["open your mouth"] },
  { slug: "touch-your-nose", label: "touch your nose", kind: "object",
    prompt: "a cartoon child touching the tip of their nose with one finger",
    aliases: ["touch your nose"] },
  { slug: "raise-your-hand", label: "raise your hand", kind: "object",
    prompt: "a cartoon child standing with one hand raised straight up",
    aliases: ["raise your hand"] },
  { slug: "clap-your-hands", label: "clap your hands", kind: "object",
    prompt: "a cartoon child clapping both hands together",
    aliases: ["clap your hands"] },
  { slug: "tap-your-foot", label: "tap your foot", kind: "object",
    prompt: "a cartoon child tapping one foot on the ground",
    aliases: ["tap your foot"] },
  { slug: "cross-your-arms", label: "cross your arms", kind: "object",
    prompt: "a cartoon child standing with arms folded across the chest",
    aliases: ["cross your arms"] },
  { slug: "wave-your-hand", label: "wave your hand", kind: "object",
    prompt: "a cartoon child waving one hand in greeting",
    aliases: ["make a wave with your hand", "wave your hand"] },

  // — times of day
  { slug: "morning", label: "morning", kind: "object",
    prompt: "a sun rising over hills in the early morning",
    aliases: ["morning"] },
  { slug: "afternoon", label: "afternoon", kind: "object",
    prompt: "a bright sun high in the sky over a park in the afternoon",
    aliases: ["afternoon"] },
  { slug: "evening", label: "evening", kind: "object",
    prompt: "a sun setting over hills in the evening",
    aliases: ["evening"] },
  { slug: "night", label: "night", kind: "object",
    prompt: "a night sky with a moon and stars over houses",
    aliases: ["night"] },

  // — shapes — drawn with canvas, not generated: a model renders
  // "diamond" as a gemstone and can't be trusted with exact geometry
  { slug: "circle", label: "circle", kind: "shape", shape: "circle",
    aliases: ["circle"] },
  { slug: "square", label: "square", kind: "shape", shape: "square",
    aliases: ["square"] },
  { slug: "triangle", label: "triangle", kind: "shape", shape: "triangle",
    aliases: ["triangle"] },
  { slug: "rectangle", label: "rectangle", kind: "shape", shape: "rectangle",
    aliases: ["rectangle"] },
  { slug: "oval", label: "oval", kind: "shape", shape: "oval",
    aliases: ["oval"] },
  { slug: "diamond", label: "diamond", kind: "shape", shape: "diamond",
    aliases: ["diamond"] },
  { slug: "heart", label: "heart", kind: "shape", shape: "heart",
    aliases: ["heart"] },
  { slug: "star-shape", label: "star", kind: "shape", shape: "star",
    aliases: ["star shape", "star shape in the sky", "star shape on a table", "star shape on paper"] },

  // — numerals 11+ — drawn with canvas (1-10 come from the games' number
  // cards). Image models garble digits, so nothing here is generated
  { slug: "eleven", label: "11", kind: "numeral", numeral: 11,
    aliases: ["eleven", "11"] },
  { slug: "twelve", label: "12", kind: "numeral", numeral: 12,
    aliases: ["twelve", "12"] },
  { slug: "thirteen", label: "13", kind: "numeral", numeral: 13,
    aliases: ["thirteen", "13"] },
  { slug: "fourteen", label: "14", kind: "numeral", numeral: 14,
    aliases: ["fourteen", "14"] },
  { slug: "fifteen", label: "15", kind: "numeral", numeral: 15,
    aliases: ["fifteen", "15"] },
  { slug: "sixteen", label: "16", kind: "numeral", numeral: 16,
    aliases: ["sixteen", "16"] },
  { slug: "seventeen", label: "17", kind: "numeral", numeral: 17,
    aliases: ["seventeen", "17"] },
  { slug: "eighteen", label: "18", kind: "numeral", numeral: 18,
    aliases: ["eighteen", "18"] },
  { slug: "nineteen", label: "19", kind: "numeral", numeral: 19,
    aliases: ["nineteen", "19"] },
  { slug: "twenty", label: "20", kind: "numeral", numeral: 20,
    aliases: ["twenty", "20"] },
  { slug: "thirty", label: "30", kind: "numeral", numeral: 30,
    aliases: ["thirty", "30"] },
  { slug: "forty", label: "40", kind: "numeral", numeral: 40,
    aliases: ["forty", "40"] },
  { slug: "fifty", label: "50", kind: "numeral", numeral: 50,
    aliases: ["fifty", "50"] },
  { slug: "sixty", label: "60", kind: "numeral", numeral: 60,
    aliases: ["sixty", "60"] },
  { slug: "seventy", label: "70", kind: "numeral", numeral: 70,
    aliases: ["seventy", "70"] },
  { slug: "eighty", label: "80", kind: "numeral", numeral: 80,
    aliases: ["eighty", "80"] },
  { slug: "ninety", label: "90", kind: "numeral", numeral: 90,
    aliases: ["ninety", "90"] },
  { slug: "one-hundred", label: "100", kind: "numeral", numeral: 100,
    aliases: ["one hundred", "100"] },
];

const BY_ALIAS = new Map<string, Concept>();
for (const c of CONCEPTS) {
  BY_ALIAS.set(c.slug, c);
  for (const a of c.aliases) BY_ALIAS.set(a, c);
}

/**
 * Lowercase, strip accents and punctuation, and drop a leading article so
 * "An Onion" and "onion" are the same key. Articles only — "to read" keeps its
 * "to", because the infinitive is how the courses label actions.
 */
function normalize(s: string): string {
  return String(s || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/^(a|an|the) /, "");
}

/**
 * Resolve an English hint (image_query or translation) to a library concept.
 *
 * Matching is deliberately EXACT — whole-hint against a slug or a listed alias.
 * A word-level fallback looks tempting ("a knee bending in sport" -> knee) but
 * misfires badly on the wider corpus: "shaking hands" in a B1 business lesson
 * became the cartoon child's hand, and "jouer au foot" became a foot. Adding
 * an alias is cheap; a wrong picture in a lesson is not.
 *
 * Hints are tried in order, so callers should pass the most specific first —
 * image_query before translation. That is what keeps "orange fruit" on the
 * fruit and a bare "orange" on the colour swatch.
 */
export function conceptFor(...hints: (string | undefined)[]): Concept | null {
  for (const hint of hints) {
    const n = normalize(hint || "");
    if (!n) continue;
    const hit = BY_ALIAS.get(n);
    if (hit) return hit;
  }
  return null;
}

export function conceptBySlug(slug: string): Concept | null {
  return CONCEPTS.find((c) => c.slug === slug) || null;
}
