// src/lib/vocab-library/concepts.ts
//
// The shared vocab picture library: one illustration per ENGLISH concept,
// reused by every language course and by the kids' games. Keying on the
// concept (not "le genou" / "la rodilla" / "das Knie") means one picture is
// generated once and every course points at it.
//
// Two kinds of concept:
//   - "figure": a part of the shared cartoon child. Can't be shown in
//     isolation — a cropped photo of a knee reads as a leg — so we composite a
//     highlight ring onto the one base figure and crop around it.
//   - "object": a standalone thing, drawn as a single-subject flat illustration.
//
// Images live in Supabase Storage at lesson-images/vocab-library/<slug>.png.
// Generated by scripts/generate-vocab-library.mjs.

export type Annotate = { x: number; y: number; size: number };

export interface Concept {
  /** Stable library key and filename. */
  slug: string;
  /** English label, shown in tooling. */
  label: string;
  kind: "figure" | "object";
  /** Ring placement on the base figure, normalized 0-1. Required for "figure". */
  annotate?: Annotate;
  /** Crop half-extent around the ring, normalized. Required for "figure". */
  zoom?: number;
  /** FLUX prompt subject. Required for "object". */
  prompt?: string;
  /** English phrasings that should resolve to this concept (lowercase). */
  aliases: string[];
}

// Ring coordinates are shared with the games' body theme
// (src/lib/games/curated/body.ts) — both read the same base figure.
export const CONCEPTS: Concept[] = [
  { slug: "head", label: "head", kind: "figure",
    annotate: { x: 0.5, y: 0.265, size: 0.135 }, zoom: 0.23,
    aliases: ["head", "heads", "child pointing at head", "the head"] },
  { slug: "hair", label: "hair", kind: "figure",
    annotate: { x: 0.5, y: 0.2, size: 0.06 }, zoom: 0.2,
    aliases: ["hair", "the hair"] },
  { slug: "eye", label: "eye", kind: "figure",
    annotate: { x: 0.452, y: 0.345, size: 0.026 }, zoom: 0.13,
    aliases: ["eye", "eyes", "eye close up", "eyes looking", "the eyes"] },
  { slug: "nose", label: "nose", kind: "figure",
    annotate: { x: 0.5, y: 0.368, size: 0.022 }, zoom: 0.13,
    aliases: ["nose", "noses", "the nose"] },
  { slug: "mouth", label: "mouth", kind: "figure",
    annotate: { x: 0.5, y: 0.397, size: 0.032 }, zoom: 0.13,
    aliases: ["mouth", "mouths", "the mouth"] },
  { slug: "ear", label: "ear", kind: "figure",
    annotate: { x: 0.41, y: 0.36, size: 0.024 }, zoom: 0.13,
    aliases: ["ear", "ears", "ear close up", "the ears"] },
  { slug: "neck", label: "neck", kind: "figure",
    annotate: { x: 0.5, y: 0.452, size: 0.028 }, zoom: 0.15,
    aliases: ["neck", "necks", "person touching neck", "the neck"] },
  { slug: "shoulder", label: "shoulder", kind: "figure",
    annotate: { x: 0.437, y: 0.462, size: 0.032 }, zoom: 0.17,
    aliases: ["shoulder", "shoulders", "shoulder close up", "the shoulders"] },
  { slug: "arm", label: "arm", kind: "figure",
    annotate: { x: 0.365, y: 0.425, size: 0.03 }, zoom: 0.2,
    aliases: ["arm", "arms", "arms raised in celebration", "the arms"] },
  { slug: "hand", label: "hand", kind: "figure",
    annotate: { x: 0.3, y: 0.405, size: 0.035 }, zoom: 0.16,
    aliases: ["hand", "hands", "hand waving", "the hands"] },
  { slug: "tummy", label: "tummy", kind: "figure",
    annotate: { x: 0.5, y: 0.55, size: 0.05 }, zoom: 0.22,
    aliases: ["tummy", "belly", "stomach", "belly showing", "the tummy"] },
  { slug: "leg", label: "leg", kind: "figure",
    annotate: { x: 0.44, y: 0.775, size: 0.062 }, zoom: 0.26,
    aliases: ["leg", "legs", "legs running", "the legs"] },
  { slug: "knee", label: "knee", kind: "figure",
    annotate: { x: 0.44, y: 0.782, size: 0.026 }, zoom: 0.12,
    aliases: ["knee", "knees", "knee bending", "the knees"] },
  { slug: "foot", label: "foot", kind: "figure",
    annotate: { x: 0.44, y: 0.85, size: 0.045 }, zoom: 0.18,
    aliases: ["foot", "feet", "the feet"] },
];

const BY_ALIAS = new Map<string, Concept>();
for (const c of CONCEPTS) {
  BY_ALIAS.set(c.slug, c);
  for (const a of c.aliases) BY_ALIAS.set(a, c);
}

function normalize(s: string): string {
  return String(s || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Resolve an English hint (image_query or translation) to a library concept.
 * Falls back to a word-level match so "a knee bending in sport" still lands on
 * "knee", but only when exactly one concept's word appears — an ambiguous hint
 * gets no match and the caller keeps its existing photo path.
 */
export function conceptFor(...hints: (string | undefined)[]): Concept | null {
  for (const hint of hints) {
    const n = normalize(hint || "");
    if (!n) continue;
    const exact = BY_ALIAS.get(n);
    if (exact) return exact;
    const words = new Set(n.split(" "));
    const hit = CONCEPTS.filter(
      (c) => words.has(c.slug) || c.aliases.some((a) => !a.includes(" ") && words.has(a))
    );
    if (hit.length === 1) return hit[0];
  }
  return null;
}

export function conceptBySlug(slug: string): Concept | null {
  return CONCEPTS.find((c) => c.slug === slug) || null;
}
