-- Generated by scripts/create-stripe-prices.mjs
-- Stripe mode: LIVE

update public.subscription_plan_prices set stripe_price_id = 'price_1U7kP3FNAbIzYQSpiKBYCsNJ'
 where plan_key = 'community' and term_months = 1;
update public.subscription_plan_prices set stripe_price_id = 'price_1U7kP4FNAbIzYQSp4ZhwFt6q'
 where plan_key = 'community' and term_months = 3;
update public.subscription_plan_prices set stripe_price_id = 'price_1U7kP5FNAbIzYQSpzDbchofs'
 where plan_key = 'community' and term_months = 12;
update public.subscription_plan_prices set stripe_price_id = 'price_1U7kP6FNAbIzYQSp9a6e5qxo'
 where plan_key = 'professional' and term_months = 1;
update public.subscription_plan_prices set stripe_price_id = 'price_1U7kP6FNAbIzYQSp0xYd8tq9'
 where plan_key = 'professional' and term_months = 3;
update public.subscription_plan_prices set stripe_price_id = 'price_1U7kP7FNAbIzYQSpinropO3p'
 where plan_key = 'professional' and term_months = 12;

-- Refuse to go live with a gap.
do $$
declare missing int;
begin
  select count(*) into missing
    from public.subscription_plan_prices
   where stripe_price_id is null or stripe_price_id like 'price_XXX%';
  if missing > 0 then
    raise exception '% price row(s) still have no Stripe price id', missing;
  end if;
end $$;

-- Open the doors.
update public.subscription_plans set active = true
 where plan_key in ('community', 'professional');

-- Confirm.
select p.plan_key, p.name, p.active, pp.term_months, pp.total_cents / 100.0 as one_per_week,
       pp.stripe_price_id
  from public.subscription_plans p
  join public.subscription_plan_prices pp on pp.plan_key = p.plan_key
 where pp.lessons_per_week = 1
 order by p.plan_key, pp.term_months;
