export const frenchA1U2L2 = {
  metadata: {
    course: "fr-a1",
    unit: 2,
    lesson: 2,
    title: "Nationalities & Countries",
    slug: "nationalities-countries",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },
  content: {
    introduction: {
      text: "Where are you from? In this lesson you will learn country names, nationalities in both masculine and feminine forms, and how to ask and answer questions about origin. Nationalities in French change form based on gender — a key concept you will use constantly.",
      image: "/images/lessons/nationalities.svg",
      culturalNote: "🇫🇷 French is spoken in over 30 countries worldwide! This community is called 'la Francophonie' and includes Canada, Belgium, Switzerland, Senegal, and many more.",
    },

    vocabulary: [
      {
        term: "Français / Française",
        translation: "French (m/f)",
        pronunciation: "frahn-SAY / frahn-SEZ",
        partOfSpeech: "adjective",
        image: "/images/vocab/french-flag.svg",
        audio: "/audio/fr/francais.mp3",
        exampleSentence: {
          original: "Je suis français.",
          translation: "I am French. (male speaking)",
        },
        tip: "Masculine ends in consonant sound, feminine adds '-e' and you hear the final consonant.",
      },
      {
        term: "Anglais / Anglaise",
        translation: "English (m/f)",
        pronunciation: "ahn-GLAY / ahn-GLEZ",
        partOfSpeech: "adjective",
        image: "/images/vocab/english-flag.svg",
        audio: "/audio/fr/anglais.mp3",
        exampleSentence: {
          original: "Elle est anglaise.",
          translation: "She is English.",
        },
        tip: "Same pattern: masculine '-ais', feminine '-aise'.",
      },
      {
        term: "Américain / Américaine",
        translation: "American (m/f)",
        pronunciation: "ah-may-ree-KAN / ah-may-ree-KEN",
        partOfSpeech: "adjective",
        image: "/images/vocab/american-flag.svg",
        audio: "/audio/fr/americain.mp3",
        exampleSentence: {
          original: "Il est américain.",
          translation: "He is American.",
        },
        tip: "Masculine '-ain', feminine '-aine'. The pronunciation changes!",
      },
      {
        term: "Espagnol / Espagnole",
        translation: "Spanish (m/f)",
        pronunciation: "es-pah-NYOL",
        partOfSpeech: "adjective",
        image: "/images/vocab/spanish-flag.svg",
        audio: "/audio/fr/espagnol.mp3",
        exampleSentence: {
          original: "Tu es espagnol ?",
          translation: "Are you Spanish?",
        },
        tip: "Add '-e' for feminine. The pronunciation barely changes for this one.",
      },
      {
        term: "Allemand / Allemande",
        translation: "German (m/f)",
        pronunciation: "al-MAHN / al-MAHND",
        partOfSpeech: "adjective",
        image: "/images/vocab/german-flag.svg",
        audio: "/audio/fr/allemand.mp3",
        exampleSentence: {
          original: "Elle est allemande.",
          translation: "She is German.",
        },
        tip: "Feminine '-ande' — you hear the 'd' sound in the feminine form.",
      },
      {
        term: "La France",
        translation: "France",
        pronunciation: "lah FRAHNSS",
        partOfSpeech: "noun",
        image: "/images/vocab/france.svg",
        audio: "/audio/fr/la-france.mp3",
        exampleSentence: {
          original: "J'habite en France.",
          translation: "I live in France.",
        },
        tip: "Feminine country — use 'en' (not 'à') before country names: 'en France'.",
      },
      {
        term: "Les États-Unis",
        translation: "The United States",
        pronunciation: "lay zay-tah-zoo-NEE",
        partOfSpeech: "noun",
        image: "/images/vocab/usa.svg",
        audio: "/audio/fr/etats-unis.mp3",
        exampleSentence: {
          original: "Il vient des États-Unis.",
          translation: "He comes from the United States.",
        },
        tip: "Always used with 'les'. Use 'aux' before it: 'J'habite aux États-Unis.'",
      },
      {
        term: "D'où",
        translation: "From where",
        pronunciation: "DOO",
        partOfSpeech: "adverb",
        image: "/images/vocab/where-from.svg",
        audio: "/audio/fr/dou.mp3",
        exampleSentence: {
          original: "Tu es d'où ?",
          translation: "Where are you from?",
        },
        tip: "The essential question for asking about someone's origin.",
      },
      {
        term: "Je viens de",
        translation: "I come from",
        pronunciation: "zhuh vee-EHN duh",
        partOfSpeech: "verb phrase",
        image: "/images/vocab/come-from.svg",
        audio: "/audio/fr/je-viens-de.mp3",
        exampleSentence: {
          original: "Je viens de Paris.",
          translation: "I come from Paris.",
        },
        tip: "From the verb 'venir' (to come). An alternative way to state your origin.",
      },
    ],

    grammar: [
      {
        title: "Nationalities — Masculine & Feminine Forms",
        explanation: "In French, nationalities are adjectives and must agree in gender with the person they describe. Most masculine forms end in a consonant, and the feminine adds an '-e'. Nationalities ending in '-ien' become '-ienne'. Important: nationalities are NOT capitalized in French (unlike English), but country names ARE capitalized.",
        examples: [
          {
            original: "Il est français. / Elle est française.",
            translation: "He is French. / She is French.",
            breakdown: "Masculine '-ais' → feminine '-aise'",
          },
          {
            original: "Il est américain. / Elle est américaine.",
            translation: "He is American. / She is American.",
            breakdown: "Masculine '-ain' → feminine '-aine'",
          },
          {
            original: "Il est canadien. / Elle est canadienne.",
            translation: "He is Canadian. / She is Canadian.",
            breakdown: "Masculine '-ien' → feminine '-ienne' (double n)",
          },
        ],
        table: {
          headers: ["Masculine", "Feminine", "Country"],
          rows: [
            ["français", "française", "la France"],
            ["anglais", "anglaise", "l'Angleterre"],
            ["américain", "américaine", "les États-Unis"],
            ["espagnol", "espagnole", "l'Espagne"],
            ["allemand", "allemande", "l'Allemagne"],
            ["canadien", "canadienne", "le Canada"],
          ],
        },
        commonMistakes: [
          "❌ Don't capitalize nationalities: 'je suis français' (not 'Français').",
          "✅ DO capitalize country names: 'la France', 'le Canada'.",
          "❌ Don't forget the gender change: a woman says 'française', not 'français'.",
        ],
      },
    ],

    dialogue: {
      title: "Where Are You From?",
      context: "Thomas and Marie meet at an international event in Paris.",
      image: "/images/dialogues/international-event.svg",
      lines: [
        {
          speaker: "Thomas",
          text: "Bonjour ! Tu es d'où ?",
          translation: "Hello! Where are you from?",
          audio: "/audio/fr/dialogue/u2l2-line1.mp3",
        },
        {
          speaker: "Marie",
          text: "Je suis canadienne. Je viens de Montréal.",
          translation: "I am Canadian. I come from Montreal.",
          audio: "/audio/fr/dialogue/u2l2-line2.mp3",
        },
        {
          speaker: "Thomas",
          text: "Ah super ! Moi, je suis français. J'habite à Paris.",
          translation: "Oh great! I'm French. I live in Paris.",
          audio: "/audio/fr/dialogue/u2l2-line3.mp3",
        },
        {
          speaker: "Marie",
          text: "Tu parles anglais aussi ?",
          translation: "Do you speak English too?",
          audio: "/audio/fr/dialogue/u2l2-line4.mp3",
        },
        {
          speaker: "Thomas",
          text: "Oui, je parle français et anglais. Et toi ?",
          translation: "Yes, I speak French and English. And you?",
          audio: "/audio/fr/dialogue/u2l2-line5.mp3",
        },
        {
          speaker: "Marie",
          text: "Je parle français, anglais et un peu espagnol.",
          translation: "I speak French, English, and a little Spanish.",
          audio: "/audio/fr/dialogue/u2l2-line6.mp3",
        },
      ],
      comprehensionQuestions: [
        {
          question: "Where is Marie from?",
          options: ["Paris", "Montreal", "Lyon", "Quebec City"],
          correctIndex: 1,
        },
        {
          question: "How many languages does Marie speak?",
          options: ["One", "Two", "Two and a bit of a third", "Four"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "La Francophonie",
      text: "French is spoken on every continent! The community of French-speaking nations is called 'la Francophonie' and includes 88 member states. Major French-speaking regions include France, Quebec (Canada), Belgium, Switzerland, and many African countries such as Senegal, Côte d'Ivoire, and the Democratic Republic of Congo. Each region has its own accent and local expressions, but the grammar stays mostly the same.",
      image: "/images/culture/francophonie.svg",
      funFact: "🤯 Africa has more French speakers than Europe! By 2050, there could be over 700 million French speakers worldwide, mostly in Africa.",
    },

    summary: {
      keyPoints: [
        "Nationalities change form based on gender: français/française",
        "Nationalities are NOT capitalized in French",
        "Country names ARE capitalized: la France, le Canada",
        "'Tu es d'où ?' is the informal way to ask where someone is from",
        "'Je viens de + place' means 'I come from'",
        "Use 'en' before feminine countries: 'en France', 'en Angleterre'",
      ],
      practicePrompt: "Write your nationality in both masculine and feminine forms. Practice saying 'Je suis [nationality]. Je viens de [city/country].' out loud!",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What is the feminine form of 'français'?",
      content: {
        options: ["françoise", "française", "francaise", "françaisse"],
        correctIndex: 1,
      },
      explanation: "Masculine 'français' becomes feminine 'française' — add '-e' and the final 's' sound becomes 'z'.",
      hint: "The pattern is '-ais' → '-aise'.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "How do you say 'Where are you from?' informally in French?",
      content: {
        options: ["Où habites-tu ?", "Tu es d'où ?", "Comment tu t'appelles ?", "Tu parles français ?"],
        correctIndex: 1,
      },
      explanation: "'Tu es d'où ?' literally means 'You are from where?' It is the standard informal way to ask about origin.",
      hint: "'D'où' means 'from where'.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Elle est _____. (She is American.)",
      content: {
        sentence: "Elle est _____.",
        answer: "américaine",
        options: ["américain", "américaine", "amerique", "américan"],
        caseSensitive: false,
      },
      explanation: "For a woman, 'américain' becomes 'américaine' — add '-e' for feminine.",
      hint: "Feminine form of 'américain'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Tu es _____ ? (Where are you from?)",
      content: {
        sentence: "Tu es _____ ?",
        answer: "d'où",
        options: ["d'où", "comment", "quand", "pourquoi"],
        caseSensitive: false,
      },
      explanation: "'D'où' means 'from where'. 'Tu es d'où ?' is the informal question for origin.",
      hint: "A two-letter word meaning 'from where'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "MATCHING",
      question: "Match the nationality to its English meaning:",
      content: {
        pairs: [
          { left: "français", right: "French (m)" },
          { left: "anglaise", right: "English (f)" },
          { left: "américain", right: "American (m)" },
          { left: "espagnole", right: "Spanish (f)" },
          { left: "allemand", right: "German (m)" },
        ],
      },
      explanation: "Notice how masculine and feminine forms differ. Pay attention to the endings!",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'She is English.'",
      content: {
        correctAnswer: "Elle est anglaise.",
        acceptableAnswers: ["Elle est anglaise.", "Elle est anglaise", "elle est anglaise"],
        direction: "to_target",
      },
      explanation: "'Anglais' becomes 'anglaise' for feminine. No article before nationalities after 'être'.",
      hint: "She = Elle. Use the feminine form of the nationality.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I come from Paris.'",
      content: {
        correctAnswer: "Je viens de Paris.",
        acceptableAnswers: ["Je viens de Paris.", "Je viens de Paris", "je viens de Paris"],
        direction: "to_target",
      },
      explanation: "'Je viens de' means 'I come from'. Use 'de' before city names.",
      hint: "Venir + de + city.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in the correct order:",
      content: {
        words: ["suis", "Je", "française"],
        correctOrder: ["Je", "suis", "française"],
        translation: "I am French. (feminine)",
      },
      explanation: "Subject + verb + nationality: Je suis française.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 8,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and select what you hear:",
      content: {
        ttsText: "Je suis américaine et j'habite en France.",
        ttsLang: "fr-FR",
        options: [
          "I am American and I live in France.",
          "I am French and I live in America.",
          "I am American and I live in England.",
          "I am Spanish and I live in France.",
        ],
        correctIndex: 0,
      },
      explanation: "'Je suis américaine et j'habite en France' — I am American (f) and I live in France.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and answer: Where does he come from?",
      content: {
        ttsText: "Il est espagnol. Il vient de Madrid.",
        ttsLang: "fr-FR",
        options: ["Paris", "Madrid", "London", "Montreal"],
        correctIndex: 1,
      },
      explanation: "'Il vient de Madrid' — He comes from Madrid.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
    {
      exercise_type: "SPEAK",
      question: "Say your nationality in French:",
      content: {
        targetText: "Je suis français",
        targetTranslation: "I am French (masculine)",
        acceptableVariants: ["je suis français", "Je suis français!", "je suis francais"],
      },
      hint: "Pronounce it: zhuh swee frahn-SAY",
      explanation: "'Je suis français' — use the masculine form if you are male.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 11,
    },
    {
      exercise_type: "SPEAK",
      question: "Now say where you come from:",
      content: {
        targetText: "Je viens de Paris",
        targetTranslation: "I come from Paris",
        acceptableVariants: ["je viens de Paris", "Je viens de Paris!"],
      },
      hint: "Pronounce it: zhuh vee-EHN duh pah-REE",
      explanation: "'Je viens de Paris' — use 'de' before city names.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 12,
    },
  ],
};
