export const frenchA1U2L8 = {
  metadata: {
    course: "fr-a1",
    unit: 2,
    lesson: 8,
    title: "Unit 2 Review — About Me",
    slug: "unit-2-review",
    type: "REVIEW",
    estimatedMinutes: 20,
    xpReward: 30,
  },
  content: {
    introduction: {
      text: "Congratulations on completing all lessons in Unit 2! This review will test everything you have learned: self-introductions, nationalities, professions, family, descriptions, ages, and hobbies. Take your time and remember — making mistakes is the best way to learn!",
      image: "/images/lessons/review-u2.svg",
      culturalNote: "🇫🇷 You now have enough French to introduce yourself at a dinner party in Paris! Name, origin, job, family, age, and hobbies — that covers most small talk topics.",
    },

    vocabulary: [
      {
        term: "Se présenter",
        translation: "To introduce oneself",
        pronunciation: "suh pray-zahn-TAY",
        partOfSpeech: "verb",
        image: "/images/vocab/introduce.svg",
        audio: "/audio/fr/se-presenter.mp3",
        exampleSentence: {
          original: "Je me présente : je m'appelle Lucas.",
          translation: "Let me introduce myself: my name is Lucas.",
        },
        tip: "A reflexive verb. 'Je me présente' is a polished way to start an introduction.",
      },
      {
        term: "Le métier",
        translation: "Profession / Job",
        pronunciation: "luh may-tee-AY",
        partOfSpeech: "noun",
        image: "/images/vocab/job.svg",
        audio: "/audio/fr/metier.mp3",
        exampleSentence: {
          original: "Mon métier, c'est professeur.",
          translation: "My job is teacher.",
        },
        tip: "More elegant than 'travail' (work). 'Quel est ton métier ?' = What is your profession?",
      },
      {
        term: "Les loisirs",
        translation: "Hobbies / Leisure activities",
        pronunciation: "lay lwah-ZEER",
        partOfSpeech: "noun",
        image: "/images/vocab/hobbies.svg",
        audio: "/audio/fr/loisirs.mp3",
        exampleSentence: {
          original: "Mes loisirs sont la lecture et le sport.",
          translation: "My hobbies are reading and sports.",
        },
        tip: "'Loisirs' is always plural. 'Temps libre' = free time.",
      },
      {
        term: "Parce que",
        translation: "Because",
        pronunciation: "pars-KUH",
        partOfSpeech: "conjunction",
        image: "/images/vocab/because.svg",
        audio: "/audio/fr/parce-que.mp3",
        exampleSentence: {
          original: "J'aime Paris parce que c'est beau.",
          translation: "I like Paris because it's beautiful.",
        },
        tip: "Essential connector! Helps you explain WHY you like or dislike something.",
      },
      {
        term: "Préféré / Préférée",
        translation: "Favorite (m/f)",
        pronunciation: "pray-fay-RAY",
        partOfSpeech: "adjective",
        image: "/images/vocab/favorite.svg",
        audio: "/audio/fr/prefere.mp3",
        exampleSentence: {
          original: "Mon sport préféré est le football.",
          translation: "My favorite sport is football.",
        },
        tip: "Goes AFTER the noun: 'mon film préféré' (my favorite movie).",
      },
    ],

    grammar: [
      {
        title: "Review: Être vs Avoir — The Key Differences",
        explanation: "This is the most important distinction in basic French. 'Être' (to be) describes identity, nationality, profession, and characteristics. 'Avoir' (to have) is used for age, possessions, and many expressions. The #1 mistake: saying 'Je suis 20 ans' instead of 'J'ai 20 ans.'",
        examples: [
          {
            original: "Je suis français.",
            translation: "I am French. (identity → être)",
            breakdown: "Être for nationality and identity",
          },
          {
            original: "Je suis professeur.",
            translation: "I am a teacher. (profession → être, no article!)",
            breakdown: "Être for profession, but no article",
          },
          {
            original: "J'ai vingt ans.",
            translation: "I am twenty. (age → avoir!)",
            breakdown: "Avoir for age — literally 'I have 20 years'",
          },
          {
            original: "J'ai un frère.",
            translation: "I have a brother. (possession → avoir)",
            breakdown: "Avoir for what you possess",
          },
        ],
        table: {
          headers: ["Use", "Verb", "Example"],
          rows: [
            ["Identity", "être", "Je suis Sophie."],
            ["Nationality", "être", "Elle est française."],
            ["Profession", "être", "Il est médecin."],
            ["Description", "être", "Elle est grande."],
            ["Age", "avoir", "J'ai 25 ans."],
            ["Possession", "avoir", "J'ai une sœur."],
            ["Hobbies", "aimer", "J'aime lire."],
          ],
        },
        commonMistakes: [
          "❌ 'Je suis 20 ans' → ✅ 'J'ai 20 ans' (age = avoir)",
          "❌ 'Je suis un professeur' → ✅ 'Je suis professeur' (no article with profession)",
          "❌ 'Elle est grand' → ✅ 'Elle est grande' (feminine agreement)",
          "❌ 'J'aime musique' → ✅ 'J'aime la musique' (article with noun after aimer)",
        ],
      },
    ],

    dialogue: {
      title: "A Complete Self-Introduction",
      context: "At a language exchange event, Thomas gives a full self-introduction to Marie.",
      image: "/images/dialogues/language-exchange.svg",
      lines: [
        {
          speaker: "Thomas",
          text: "Bonjour ! Je me présente. Je m'appelle Thomas.",
          translation: "Hello! Let me introduce myself. My name is Thomas.",
          audio: "/audio/fr/dialogue/u2l8-line1.mp3",
        },
        {
          speaker: "Marie",
          text: "Enchantée, Thomas ! Moi, c'est Marie. Tu es d'où ?",
          translation: "Nice to meet you, Thomas! I'm Marie. Where are you from?",
          audio: "/audio/fr/dialogue/u2l8-line2.mp3",
        },
        {
          speaker: "Thomas",
          text: "Je suis français, de Lyon. J'ai vingt-quatre ans et je suis ingénieur.",
          translation: "I'm French, from Lyon. I'm 24 and I'm an engineer.",
          audio: "/audio/fr/dialogue/u2l8-line3.mp3",
        },
        {
          speaker: "Marie",
          text: "Intéressant ! Tu as des frères et sœurs ?",
          translation: "Interesting! Do you have brothers and sisters?",
          audio: "/audio/fr/dialogue/u2l8-line4.mp3",
        },
        {
          speaker: "Thomas",
          text: "Oui, j'ai une sœur. Elle est grande et blonde. Elle est étudiante.",
          translation: "Yes, I have a sister. She is tall and blonde. She is a student.",
          audio: "/audio/fr/dialogue/u2l8-line5.mp3",
        },
        {
          speaker: "Marie",
          text: "Et qu'est-ce que tu aimes faire ?",
          translation: "And what do you like to do?",
          audio: "/audio/fr/dialogue/u2l8-line6.mp3",
        },
        {
          speaker: "Thomas",
          text: "J'adore voyager et jouer au football. Et toi ?",
          translation: "I love traveling and playing football. And you?",
          audio: "/audio/fr/dialogue/u2l8-line7.mp3",
        },
        {
          speaker: "Marie",
          text: "Moi, j'aime lire et cuisiner. Ravie de te connaître !",
          translation: "Me, I like reading and cooking. Pleased to know you!",
          audio: "/audio/fr/dialogue/u2l8-line8.mp3",
        },
      ],
      comprehensionQuestions: [
        {
          question: "What is Thomas's profession?",
          options: ["Teacher", "Doctor", "Engineer", "Lawyer"],
          correctIndex: 2,
        },
        {
          question: "What does Thomas's sister look like?",
          options: ["Short and brunette", "Tall and blonde", "Short and blonde", "Tall and brunette"],
          correctIndex: 1,
        },
      ],
    },

    culture: {
      title: "The Art of Self-Introduction in France",
      text: "French self-introductions follow a natural flow: name, origin, profession, then personal details. The French generally share less personal information quickly compared to some cultures. Topics like salary, religion, or politics are considered inappropriate when first meeting someone. The phrase 'Enchanté(e)' (pleased to meet you) is the standard polite response. Add '-e' if you are a woman: 'Enchantée.'",
      image: "/images/culture/introduction.svg",
      funFact: "🤯 The French expression 'Moi, c'est...' (Me, it's...) is an increasingly popular casual way to introduce yourself, especially among younger people. It sounds more relaxed than 'Je m'appelle.'",
    },

    summary: {
      keyPoints: [
        "Self-introduction flow: name → origin → profession → family → hobbies",
        "'Être' for identity, nationality, profession, description",
        "'Avoir' for age and possessions",
        "No article after 'être' + profession",
        "Possessive adjectives agree with the NOUN (mon/ma/mes)",
        "Adjectives agree in gender (grand/grande)",
        "'Aimer/adorer/détester' + infinitive for hobbies",
        "'Quel âge as-tu ?' uses 'avoir', not 'être'",
      ],
      practicePrompt: "Write and say a complete self-introduction in French: name, nationality, age, profession, family, one thing you love, and one thing you hate. Time yourself — aim for under 30 seconds!",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "Which sentence correctly states someone's age?",
      content: {
        options: ["Je suis trente ans", "J'ai trente ans", "Je suis trente", "J'ai trente"],
        correctIndex: 1,
      },
      explanation: "Age uses 'avoir': J'ai + number + ans. Not 'être'!",
      hint: "Remember: age = avoir.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "How do you say 'My sister is tall' in French?",
      content: {
        options: ["Ma sœur est grand", "Ma sœur est grande", "Mon sœur est grande", "Ma sœur a grande"],
        correctIndex: 1,
      },
      explanation: "'Sœur' is feminine → 'ma' (not 'mon'). 'Grand' becomes 'grande' for feminine.",
      hint: "Sister = feminine. Adjective must match!",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "Which is correct for 'She is a doctor'?",
      content: {
        options: ["Elle est une médecin", "Elle est médecin", "Elle a médecin", "Elle est la médecin"],
        correctIndex: 1,
      },
      explanation: "No article after 'être' + profession: Elle est médecin.",
      hint: "What's the rule about articles and professions?",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Je _____ de Paris. (I come from Paris.)",
      content: {
        sentence: "Je _____ de Paris.",
        answer: "viens",
        options: ["viens", "suis", "habite", "parle"],
        caseSensitive: false,
      },
      explanation: "'Venir' with 'je' → 'viens'. 'Je viens de Paris' = I come from Paris.",
      hint: "The verb 'venir' (to come), conjugated with 'je'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: J'_____ voyager. (I love traveling.)",
      content: {
        sentence: "J'_____ voyager.",
        answer: "adore",
        options: ["adore", "aime", "ai", "suis"],
        caseSensitive: false,
      },
      explanation: "'Adorer' with 'je' → 'j'adore'. Strongest positive feeling!",
      hint: "The verb meaning 'to love/adore'.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 5,
    },
    {
      exercise_type: "MATCHING",
      question: "Match each French phrase to its English meaning:",
      content: {
        pairs: [
          { left: "Je m'appelle", right: "My name is" },
          { left: "J'ai 25 ans", right: "I am 25 years old" },
          { left: "Je suis ingénieur", right: "I am an engineer" },
          { left: "Ma sœur", right: "My sister" },
          { left: "J'adore lire", right: "I love reading" },
        ],
      },
      explanation: "These phrases cover all the key topics from Unit 2: introductions, age, profession, family, hobbies.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 6,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'My name is Marie. I am French. I am 22 years old.'",
      content: {
        correctAnswer: "Je m'appelle Marie. Je suis française. J'ai vingt-deux ans.",
        acceptableAnswers: [
          "Je m'appelle Marie. Je suis française. J'ai vingt-deux ans.",
          "Je m'appelle Marie. Je suis française. J'ai vingt-deux ans",
          "Je m'appelle Marie. Je suis française. J'ai 22 ans.",
        ],
        direction: "to_target",
      },
      explanation: "Name → je m'appelle. Nationality → être + feminine form. Age → avoir + ans.",
      hint: "Three sentences: name (m'appelle), nationality (suis), age (ai...ans).",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 7,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'My father is a teacher. He is tall.'",
      content: {
        correctAnswer: "Mon père est professeur. Il est grand.",
        acceptableAnswers: [
          "Mon père est professeur. Il est grand.",
          "Mon père est professeur. Il est grand",
          "mon père est professeur. il est grand",
        ],
        direction: "to_target",
      },
      explanation: "Profession → no article after être. Adjective → masculine form 'grand' matches 'il'.",
      hint: "No article for profession! Adjective matches gender.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 8,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in the correct order:",
      content: {
        words: ["française", "suis", "Je", "et", "à", "Paris", "j'habite"],
        correctOrder: ["Je", "suis", "française", "et", "j'habite", "à", "Paris"],
        translation: "I am French and I live in Paris.",
      },
      explanation: "Two clauses joined by 'et': Je suis française + et + j'habite à Paris.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen carefully. What is NOT true about Sophie?",
      content: {
        ttsText: "Je m'appelle Sophie. Je suis canadienne. J'ai vingt-trois ans. Je suis étudiante et j'adore voyager.",
        ttsLang: "fr-FR",
        options: [
          "She is Canadian",
          "She is 23 years old",
          "She is a teacher",
          "She loves traveling",
        ],
        correctIndex: 2,
      },
      explanation: "Sophie is 'étudiante' (student), NOT 'professeur' (teacher).",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and answer: What does the brother do?",
      content: {
        ttsText: "Mon frère a trente ans. Il est grand et brun. Il est médecin.",
        ttsLang: "fr-FR",
        options: ["Teacher", "Engineer", "Doctor", "Lawyer"],
        correctIndex: 2,
      },
      explanation: "'Médecin' = doctor. He is 30, tall, dark-haired, and a doctor.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 11,
    },
    {
      exercise_type: "SPEAK",
      question: "Give a complete introduction — say your name, nationality, and age:",
      content: {
        targetText: "Je m'appelle Thomas. Je suis français. J'ai vingt-cinq ans.",
        targetTranslation: "My name is Thomas. I am French. I am 25 years old.",
        acceptableVariants: [
          "je m'appelle Thomas. je suis français. j'ai vingt-cinq ans",
          "Je m'appelle Thomas. Je suis français. J'ai vingt-cinq ans!",
        ],
      },
      hint: "Three sentences: name + nationality + age. Take your time!",
      explanation: "A complete self-introduction: m'appelle (name) + suis (nationality) + ai...ans (age).",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 12,
    },
    {
      exercise_type: "SPEAK",
      question: "Say you have a brother and a sister:",
      content: {
        targetText: "J'ai un frère et une sœur",
        targetTranslation: "I have a brother and a sister",
        acceptableVariants: ["j'ai un frère et une sœur", "J'ai un frère et une sœur!", "j'ai un frere et une soeur"],
      },
      hint: "Pronounce it: ZHAY uhn FRAIR ay oon SUHR",
      explanation: "'J'ai' (I have) + 'un frère' (a brother) + 'et' (and) + 'une sœur' (a sister).",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 13,
    },
  ],
};
