export const frenchA1U2L3 = {
  metadata: {
    course: "fr-a1",
    unit: 2,
    lesson: 3,
    title: "Professions",
    slug: "professions",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },
  content: {
    introduction: {
      text: "What do you do for a living? In this lesson you will learn common professions in French, including their masculine and feminine forms. You will also discover an important French grammar rule: you do NOT use an article before professions after the verb 'être'. By the end, you can talk about your job and ask about others.",
      image: "/images/lessons/professions.svg",
      culturalNote: "🇫🇷 The French work week is 35 hours — one of the shortest in Europe. French workers also enjoy at least 5 weeks of paid vacation per year!",
    },

    vocabulary: [
      {
        term: "Un professeur",
        translation: "A teacher / professor",
        pronunciation: "uhn proh-feh-SUHR",
        partOfSpeech: "noun",
        image: "/images/vocab/teacher.svg",
        audio: "/audio/fr/professeur.mp3",
        exampleSentence: {
          original: "Je suis professeur de français.",
          translation: "I am a French teacher.",
        },
        tip: "Can be used for both genders, though 'professeure' is increasingly used for women.",
      },
      {
        term: "Un médecin",
        translation: "A doctor",
        pronunciation: "uhn mayd-SAN",
        partOfSpeech: "noun",
        image: "/images/vocab/doctor.svg",
        audio: "/audio/fr/medecin.mp3",
        exampleSentence: {
          original: "Elle est médecin.",
          translation: "She is a doctor.",
        },
        tip: "Used for both genders traditionally. 'Médecine' is the field of medicine, not a female doctor.",
      },
      {
        term: "Un étudiant / Une étudiante",
        translation: "A student (m/f)",
        pronunciation: "uhn ay-too-dee-AHN / oon ay-too-dee-AHNT",
        partOfSpeech: "noun",
        image: "/images/vocab/student.svg",
        audio: "/audio/fr/etudiant.mp3",
        exampleSentence: {
          original: "Il est étudiant à l'université.",
          translation: "He is a university student.",
        },
        tip: "Feminine adds '-e': étudiant → étudiante. You hear the final 't' in the feminine.",
      },
      {
        term: "Un ingénieur",
        translation: "An engineer",
        pronunciation: "uhn an-zhay-NYUHR",
        partOfSpeech: "noun",
        image: "/images/vocab/engineer.svg",
        audio: "/audio/fr/ingenieur.mp3",
        exampleSentence: {
          original: "Mon père est ingénieur.",
          translation: "My father is an engineer.",
        },
        tip: "The feminine form 'ingénieure' is now officially accepted.",
      },
      {
        term: "Un avocat / Une avocate",
        translation: "A lawyer (m/f)",
        pronunciation: "uhn ah-voh-KAH / oon ah-voh-KAT",
        partOfSpeech: "noun",
        image: "/images/vocab/lawyer.svg",
        audio: "/audio/fr/avocat.mp3",
        exampleSentence: {
          original: "Elle est avocate.",
          translation: "She is a lawyer.",
        },
        tip: "Fun fact: 'un avocat' also means 'an avocado'! Context makes it clear.",
      },
      {
        term: "Un serveur / Une serveuse",
        translation: "A waiter / waitress",
        pronunciation: "uhn sair-VUHR / oon sair-VUHZ",
        partOfSpeech: "noun",
        image: "/images/vocab/waiter.svg",
        audio: "/audio/fr/serveur.mp3",
        exampleSentence: {
          original: "Le serveur est très sympa.",
          translation: "The waiter is very nice.",
        },
        tip: "Masculine '-eur' → feminine '-euse'. A very common pattern!",
      },
      {
        term: "Un boulanger / Une boulangère",
        translation: "A baker (m/f)",
        pronunciation: "uhn boo-lahn-ZHAY / oon boo-lahn-ZHAIR",
        partOfSpeech: "noun",
        image: "/images/vocab/baker.svg",
        audio: "/audio/fr/boulanger.mp3",
        exampleSentence: {
          original: "Le boulanger fait du pain.",
          translation: "The baker makes bread.",
        },
        tip: "Masculine '-er' → feminine '-ère'. A boulangerie is a bakery!",
      },
      {
        term: "Travailler",
        translation: "To work",
        pronunciation: "trah-vah-YAY",
        partOfSpeech: "verb",
        image: "/images/vocab/work.svg",
        audio: "/audio/fr/travailler.mp3",
        exampleSentence: {
          original: "Je travaille dans un bureau.",
          translation: "I work in an office.",
        },
        tip: "Regular -er verb. 'Je travaille' sounds like 'zhuh trah-VYE'.",
      },
      {
        term: "Un bureau",
        translation: "An office / a desk",
        pronunciation: "uhn boo-ROH",
        partOfSpeech: "noun",
        image: "/images/vocab/office.svg",
        audio: "/audio/fr/bureau.mp3",
        exampleSentence: {
          original: "Il travaille dans un grand bureau.",
          translation: "He works in a big office.",
        },
        tip: "Can mean both 'office' and 'desk' depending on context.",
      },
    ],

    grammar: [
      {
        title: "No Article Before Professions After 'Être'",
        explanation: "In French, when stating someone's profession with the verb 'être', you do NOT use an article (un/une). This is different from English where you say 'I am A teacher.' However, if you add a descriptive adjective, you need the article back.",
        examples: [
          {
            original: "Je suis professeur.",
            translation: "I am a teacher. (no article!)",
            breakdown: "Je (I) + suis (am) + professeur (teacher) — no 'un' or 'une'",
          },
          {
            original: "Elle est médecin.",
            translation: "She is a doctor. (no article!)",
            breakdown: "Elle (she) + est (is) + médecin (doctor)",
          },
          {
            original: "Il est un bon avocat.",
            translation: "He is a good lawyer. (article returns with adjective)",
            breakdown: "With adjective 'bon' → article comes back",
          },
        ],
        table: {
          headers: ["Correct ✅", "Incorrect ❌", "Why"],
          rows: [
            ["Je suis médecin.", "Je suis un médecin.", "No article after être + profession"],
            ["Elle est avocate.", "Elle est une avocate.", "No article after être + profession"],
            ["Il est un bon professeur.", "—", "Article OK when adjective is present"],
          ],
        },
        commonMistakes: [
          "❌ Don't say 'Je suis un professeur' — drop the article!",
          "✅ Say 'Je suis professeur' — no article needed.",
          "❌ Don't forget feminine forms: 'Elle est avocate' (not 'avocat').",
        ],
      },
    ],

    dialogue: {
      title: "What Do You Do?",
      context: "Pierre and Claire talk about their jobs at a dinner party in Paris.",
      image: "/images/dialogues/dinner-party.svg",
      lines: [
        {
          speaker: "Pierre",
          text: "Qu'est-ce que tu fais dans la vie ?",
          translation: "What do you do for a living?",
          audio: "/audio/fr/dialogue/u2l3-line1.mp3",
        },
        {
          speaker: "Claire",
          text: "Je suis avocate. Je travaille dans un cabinet à Paris.",
          translation: "I am a lawyer. I work in a firm in Paris.",
          audio: "/audio/fr/dialogue/u2l3-line2.mp3",
        },
        {
          speaker: "Pierre",
          text: "Ah, intéressant ! Moi, je suis ingénieur.",
          translation: "Ah, interesting! I'm an engineer.",
          audio: "/audio/fr/dialogue/u2l3-line3.mp3",
        },
        {
          speaker: "Claire",
          text: "Tu travailles où ?",
          translation: "Where do you work?",
          audio: "/audio/fr/dialogue/u2l3-line4.mp3",
        },
        {
          speaker: "Pierre",
          text: "Je travaille dans un bureau à Lyon.",
          translation: "I work in an office in Lyon.",
          audio: "/audio/fr/dialogue/u2l3-line5.mp3",
        },
        {
          speaker: "Claire",
          text: "C'est bien ! Tu aimes ton travail ?",
          translation: "That's nice! Do you like your job?",
          audio: "/audio/fr/dialogue/u2l3-line6.mp3",
        },
      ],
      comprehensionQuestions: [
        {
          question: "What is Claire's profession?",
          options: ["Engineer", "Lawyer", "Teacher", "Doctor"],
          correctIndex: 1,
        },
        {
          question: "Where does Pierre work?",
          options: ["Paris", "Lyon", "Marseille", "Nice"],
          correctIndex: 1,
        },
      ],
    },

    culture: {
      title: "Work Culture in France",
      text: "France has a 35-hour work week (les 35 heures), one of the shortest in Europe. French workers enjoy a minimum of 5 weeks paid vacation per year. Lunch breaks are typically longer — sometimes an hour or more. The French value a clear separation between work life and personal life. It is considered impolite to call colleagues about work matters during evenings or weekends.",
      image: "/images/culture/work-france.svg",
      funFact: "🤯 In 2017, France passed the 'right to disconnect' law, making it illegal for companies to send work emails to employees outside business hours!",
    },

    summary: {
      keyPoints: [
        "No article after 'être' + profession: 'Je suis médecin' (not 'un médecin')",
        "Most professions have masculine and feminine forms",
        "Common patterns: -eur/-euse (serveur/serveuse), -er/-ère (boulanger/boulangère)",
        "'Qu'est-ce que tu fais dans la vie ?' = What do you do for a living?",
        "'Je travaille dans...' = I work in...",
        "'Un bureau' can mean office or desk",
      ],
      practicePrompt: "Say your profession in French (or a profession you want). Practice: 'Je suis [profession]. Je travaille dans [place].' Say it five times!",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "Which is correct for 'I am a doctor'?",
      content: {
        options: ["Je suis un médecin", "Je suis médecin", "J'ai médecin", "Je suis le médecin"],
        correctIndex: 1,
      },
      explanation: "No article is used after 'être' when stating a profession. 'Je suis médecin.'",
      hint: "Remember the rule about articles and professions.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What is the feminine form of 'boulanger'?",
      content: {
        options: ["boulangère", "boulangeuse", "boulangesse", "boulangerine"],
        correctIndex: 0,
      },
      explanation: "'Boulanger' becomes 'boulangère' in the feminine — the pattern is '-er' → '-ère'.",
      hint: "The '-er' ending changes to what in feminine?",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 2,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Elle est _____. (She is a lawyer.)",
      content: {
        sentence: "Elle est _____.",
        answer: "avocate",
        options: ["avocat", "avocate", "avocatte", "avocade"],
        caseSensitive: false,
      },
      explanation: "'Avocat' becomes 'avocate' for feminine — add '-e'.",
      hint: "Add '-e' to the masculine form.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Je _____ dans un bureau. (I work in an office.)",
      content: {
        sentence: "Je _____ dans un bureau.",
        answer: "travaille",
        options: ["travaille", "travailles", "travailler", "travaillé"],
        caseSensitive: false,
      },
      explanation: "'Travailler' with 'je' becomes 'travaille'. Regular -er verb conjugation.",
      hint: "Regular -er verb with 'je'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "MATCHING",
      question: "Match each profession to its English meaning:",
      content: {
        pairs: [
          { left: "professeur", right: "teacher" },
          { left: "médecin", right: "doctor" },
          { left: "avocat", right: "lawyer" },
          { left: "serveur", right: "waiter" },
          { left: "boulanger", right: "baker" },
        ],
      },
      explanation: "These are some of the most common professions in French.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'She is a musician.'",
      content: {
        correctAnswer: "Elle est musicienne.",
        acceptableAnswers: ["Elle est musicienne.", "Elle est musicienne", "elle est musicienne"],
        direction: "to_target",
      },
      explanation: "No article after 'être'. 'Musicien' becomes 'musicienne' for feminine (-ien → -ienne).",
      hint: "No article! And use the feminine form.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I work in an office.'",
      content: {
        correctAnswer: "Je travaille dans un bureau.",
        acceptableAnswers: ["Je travaille dans un bureau.", "Je travaille dans un bureau", "je travaille dans un bureau"],
        direction: "to_target",
      },
      explanation: "'Travailler dans' = to work in. 'Un bureau' = an office.",
      hint: "Travailler + dans + un bureau.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in the correct order:",
      content: {
        words: ["est", "Elle", "professeur"],
        correctOrder: ["Elle", "est", "professeur"],
        translation: "She is a teacher.",
      },
      explanation: "Subject + verb + profession (no article!): Elle est professeur.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 8,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and answer: What is this person's job?",
      content: {
        ttsText: "Je suis boulanger. Je travaille dans une boulangerie.",
        ttsLang: "fr-FR",
        options: ["Baker", "Doctor", "Teacher", "Lawyer"],
        correctIndex: 0,
      },
      explanation: "'Boulanger' means baker. 'Boulangerie' is a bakery.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and identify the question being asked:",
      content: {
        ttsText: "Qu'est-ce que tu fais dans la vie ?",
        ttsLang: "fr-FR",
        options: [
          "What do you do for a living?",
          "Where do you live?",
          "How are you?",
          "What is your name?",
        ],
        correctIndex: 0,
      },
      explanation: "'Qu'est-ce que tu fais dans la vie ?' is the common way to ask about someone's profession.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
    {
      exercise_type: "SPEAK",
      question: "Say your profession:",
      content: {
        targetText: "Je suis étudiant",
        targetTranslation: "I am a student (masculine)",
        acceptableVariants: ["je suis étudiant", "Je suis étudiant!", "je suis etudiant"],
      },
      hint: "Pronounce it: zhuh swee ay-too-dee-AHN",
      explanation: "No article! 'Je suis étudiant' — not 'Je suis un étudiant'.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 11,
    },
    {
      exercise_type: "SPEAK",
      question: "Say where you work:",
      content: {
        targetText: "Je travaille dans un bureau",
        targetTranslation: "I work in an office",
        acceptableVariants: ["je travaille dans un bureau", "Je travaille dans un bureau!"],
      },
      hint: "Pronounce it: zhuh trah-VYE dahn uhn boo-ROH",
      explanation: "'Travaille' is pronounced 'trah-VYE'. The '-aille' ending sounds like 'eye'.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 12,
    },
  ],
};
