export const frenchA1U2L5 = {
  metadata: {
    course: "fr-a1",
    unit: 2,
    lesson: 5,
    title: "Describing People",
    slug: "describing-people",
    type: "GRAMMAR",
    estimatedMinutes: 15,
    xpReward: 20,
  },
  content: {
    introduction: {
      text: "How do you describe someone in French? In this lesson you will learn adjectives for physical appearance and personality. The key challenge: French adjectives must agree in gender with the noun they describe. A tall man is 'grand' but a tall woman is 'grande'. Master this rule and you unlock the ability to describe anyone!",
      image: "/images/lessons/describing.svg",
      culturalNote: "🇫🇷 In France, people are generally more reserved with personal compliments, especially about physical appearance. Among friends, common compliments include 'Tu es sympa' (you're nice) or 'Tu es drôle' (you're funny).",
    },

    vocabulary: [
      {
        term: "Grand / Grande",
        translation: "Tall / Big (m/f)",
        pronunciation: "GRAHN / GRAHND",
        partOfSpeech: "adjective",
        image: "/images/vocab/tall.svg",
        audio: "/audio/fr/grand.mp3",
        exampleSentence: {
          original: "Il est grand.",
          translation: "He is tall.",
        },
        tip: "You hear the 'd' only in the feminine: 'grande'. In 'grand', the 'd' is silent.",
      },
      {
        term: "Petit / Petite",
        translation: "Short / Small (m/f)",
        pronunciation: "puh-TEE / puh-TEET",
        partOfSpeech: "adjective",
        image: "/images/vocab/short.svg",
        audio: "/audio/fr/petit.mp3",
        exampleSentence: {
          original: "Elle est petite.",
          translation: "She is short.",
        },
        tip: "Masculine: silent 't'. Feminine: you hear the 't' in 'petite'.",
      },
      {
        term: "Beau / Belle",
        translation: "Handsome / Beautiful (m/f)",
        pronunciation: "BOH / BELL",
        partOfSpeech: "adjective",
        image: "/images/vocab/beautiful.svg",
        audio: "/audio/fr/beau.mp3",
        exampleSentence: {
          original: "Elle est très belle.",
          translation: "She is very beautiful.",
        },
        tip: "Irregular! Masculine 'beau' → feminine 'belle'. Before a masculine vowel word: 'bel' (un bel homme).",
      },
      {
        term: "Jeune",
        translation: "Young",
        pronunciation: "ZHUHN",
        partOfSpeech: "adjective",
        image: "/images/vocab/young.svg",
        audio: "/audio/fr/jeune.mp3",
        exampleSentence: {
          original: "Il est jeune.",
          translation: "He is young.",
        },
        tip: "Same form for masculine and feminine! 'Il est jeune' / 'Elle est jeune'.",
      },
      {
        term: "Sympa",
        translation: "Nice / Friendly",
        pronunciation: "sam-PAH",
        partOfSpeech: "adjective",
        image: "/images/vocab/nice.svg",
        audio: "/audio/fr/sympa.mp3",
        exampleSentence: {
          original: "Mon professeur est sympa.",
          translation: "My teacher is nice.",
        },
        tip: "Short for 'sympathique'. Invariable — same for masculine and feminine.",
      },
      {
        term: "Intelligent / Intelligente",
        translation: "Intelligent (m/f)",
        pronunciation: "an-teh-lee-ZHAHN / an-teh-lee-ZHAHNT",
        partOfSpeech: "adjective",
        image: "/images/vocab/smart.svg",
        audio: "/audio/fr/intelligent.mp3",
        exampleSentence: {
          original: "Elle est intelligente.",
          translation: "She is intelligent.",
        },
        tip: "Add '-e' for feminine. The final 't' becomes audible.",
      },
      {
        term: "Drôle",
        translation: "Funny",
        pronunciation: "DROHL",
        partOfSpeech: "adjective",
        image: "/images/vocab/funny.svg",
        audio: "/audio/fr/drole.mp3",
        exampleSentence: {
          original: "Mon frère est drôle.",
          translation: "My brother is funny.",
        },
        tip: "Same form for both genders. 'Il est drôle' / 'Elle est drôle'.",
      },
      {
        term: "Les cheveux",
        translation: "Hair",
        pronunciation: "lay shuh-VUH",
        partOfSpeech: "noun",
        image: "/images/vocab/hair.svg",
        audio: "/audio/fr/cheveux.mp3",
        exampleSentence: {
          original: "Elle a les cheveux blonds.",
          translation: "She has blonde hair.",
        },
        tip: "Always plural in French! 'Les cheveux' (the hairs). Use 'avoir' (to have) with hair.",
      },
      {
        term: "Les yeux",
        translation: "Eyes",
        pronunciation: "lay ZYUH",
        partOfSpeech: "noun",
        image: "/images/vocab/eyes.svg",
        audio: "/audio/fr/yeux.mp3",
        exampleSentence: {
          original: "Il a les yeux bleus.",
          translation: "He has blue eyes.",
        },
        tip: "Irregular plural! One eye = 'un œil', multiple = 'les yeux'.",
      },
      {
        term: "Blond / Blonde",
        translation: "Blonde (m/f)",
        pronunciation: "BLOHN / BLOHND",
        partOfSpeech: "adjective",
        image: "/images/vocab/blonde.svg",
        audio: "/audio/fr/blond.mp3",
        exampleSentence: {
          original: "Elle est blonde.",
          translation: "She is blonde.",
        },
        tip: "Final 'd' is silent in masculine but heard in feminine 'blonde'.",
      },
    ],

    grammar: [
      {
        title: "Adjective Agreement — Masculine & Feminine",
        explanation: "French adjectives must agree with the noun they describe in gender and number. Most adjectives add '-e' for feminine. Some adjectives like 'sympa', 'drôle', and 'jeune' are invariable (same for both). Important: most French adjectives go AFTER the noun, but common ones like grand, petit, beau, jeune go BEFORE the noun.",
        examples: [
          {
            original: "Il est grand. / Elle est grande.",
            translation: "He is tall. / She is tall.",
            breakdown: "Add '-e' for feminine: grand → grande",
          },
          {
            original: "Un homme intelligent. / Une femme intelligente.",
            translation: "An intelligent man. / An intelligent woman.",
            breakdown: "Add '-e', final consonant becomes audible",
          },
          {
            original: "Une belle fille.",
            translation: "A beautiful girl.",
            breakdown: "'Beau' → 'belle' (irregular). Goes BEFORE the noun.",
          },
        ],
        table: {
          headers: ["Masculine", "Feminine", "Position"],
          rows: [
            ["grand", "grande", "BEFORE noun"],
            ["petit", "petite", "BEFORE noun"],
            ["beau", "belle", "BEFORE noun"],
            ["intelligent", "intelligente", "AFTER noun"],
            ["sympa", "sympa", "AFTER noun (invariable)"],
            ["drôle", "drôle", "AFTER noun (invariable)"],
          ],
        },
        commonMistakes: [
          "❌ Don't say 'Elle est grand' — adjectives MUST match gender: 'Elle est grande'.",
          "✅ Some adjectives don't change: 'Il est sympa' / 'Elle est sympa'.",
          "❌ Don't put all adjectives before the noun — most go AFTER: 'un homme intelligent'.",
          "✅ BANGS adjectives go before: Beauty, Age, Number, Goodness, Size.",
        ],
      },
    ],

    dialogue: {
      title: "Describing a Friend",
      context: "Thomas describes his best friend to Marie.",
      image: "/images/dialogues/describing-friend.svg",
      lines: [
        {
          speaker: "Marie",
          text: "Ton ami Pierre, il est comment ?",
          translation: "Your friend Pierre, what is he like?",
          audio: "/audio/fr/dialogue/u2l5-line1.mp3",
        },
        {
          speaker: "Thomas",
          text: "Il est grand et brun. Il a les yeux verts.",
          translation: "He is tall and dark-haired. He has green eyes.",
          audio: "/audio/fr/dialogue/u2l5-line2.mp3",
        },
        {
          speaker: "Marie",
          text: "Il est sympa ?",
          translation: "Is he nice?",
          audio: "/audio/fr/dialogue/u2l5-line3.mp3",
        },
        {
          speaker: "Thomas",
          text: "Oui, très sympa ! Et il est très drôle aussi.",
          translation: "Yes, very nice! And he is very funny too.",
          audio: "/audio/fr/dialogue/u2l5-line4.mp3",
        },
        {
          speaker: "Marie",
          text: "Et ta sœur, elle est comment ?",
          translation: "And your sister, what is she like?",
          audio: "/audio/fr/dialogue/u2l5-line5.mp3",
        },
        {
          speaker: "Thomas",
          text: "Elle est petite et blonde. Elle est très intelligente.",
          translation: "She is short and blonde. She is very intelligent.",
          audio: "/audio/fr/dialogue/u2l5-line6.mp3",
        },
      ],
      comprehensionQuestions: [
        {
          question: "What color are Pierre's eyes?",
          options: ["Blue", "Green", "Brown", "Grey"],
          correctIndex: 1,
        },
        {
          question: "How is Thomas's sister described?",
          options: ["Tall and brunette", "Short and blonde", "Tall and blonde", "Short and brunette"],
          correctIndex: 1,
        },
      ],
    },

    culture: {
      title: "The Question 'Il/Elle est comment ?'",
      text: "The phrase 'Il est comment ?' or 'Elle est comment ?' is the casual French way to ask 'What is he/she like?' It can refer to both physical appearance and personality. In more formal French, you might hear 'Comment est-il/elle ?' instead. When describing someone, the French tend to mention personality traits (sympa, drôle, gentil) more often than physical features.",
      image: "/images/culture/descriptions.svg",
      funFact: "🤯 The French have a saying: 'L'habit ne fait pas le moine' — 'The clothes don't make the monk.' It means you shouldn't judge people by appearances!",
    },

    summary: {
      keyPoints: [
        "Adjectives agree in gender: grand/grande, petit/petite, blond/blonde",
        "Some adjectives are invariable: sympa, drôle, jeune",
        "Irregular adjectives: beau/belle",
        "Most adjectives go AFTER the noun; common ones (grand, petit, beau, jeune) go BEFORE",
        "Hair: 'Il/Elle a les cheveux + color' (uses avoir, not être)",
        "Eyes: 'Il/Elle a les yeux + color' (uses avoir, not être)",
        "'Il/Elle est comment ?' = What is he/she like?",
      ],
      practicePrompt: "Describe a family member or friend in French using at least three adjectives. Remember to adjust for gender! Example: 'Ma mère est grande, intelligente et sympa.'",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What is the feminine form of 'grand'?",
      content: {
        options: ["grand", "grande", "grands", "grander"],
        correctIndex: 1,
      },
      explanation: "Add '-e' for feminine: grand → grande.",
      hint: "Most adjectives simply add '-e' for feminine.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What does 'Il a les yeux bleus' mean?",
      content: {
        options: ["He has blue eyes", "He has green eyes", "He has blue hair", "He is blue"],
        correctIndex: 0,
      },
      explanation: "'Les yeux' = eyes, 'bleus' = blue. Note: French uses 'avoir' (to have) for eyes and hair.",
      hint: "'Yeux' = eyes. 'Bleus' = blue.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Elle est très _____. (She is very intelligent.)",
      content: {
        sentence: "Elle est très _____.",
        answer: "intelligente",
        options: ["intelligent", "intelligente", "intelligents", "intelligentes"],
        caseSensitive: false,
      },
      explanation: "'Intelligent' → 'intelligente' for feminine — add '-e'.",
      hint: "Elle = she (feminine). Which form matches?",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Il a les cheveux _____. (He has blond hair.)",
      content: {
        sentence: "Il a les cheveux _____.",
        answer: "blonds",
        options: ["blond", "blonds", "blonde", "blondes"],
        caseSensitive: false,
      },
      explanation: "'Cheveux' is masculine plural → 'blonds' (masculine plural).",
      hint: "Cheveux is masculine AND plural.",
      difficulty: "HARD",
      xp_reward: 4,
      order_index: 4,
    },
    {
      exercise_type: "MATCHING",
      question: "Match each adjective to its English meaning:",
      content: {
        pairs: [
          { left: "grand", right: "tall" },
          { left: "petit", right: "short" },
          { left: "beau", right: "handsome" },
          { left: "drôle", right: "funny" },
          { left: "gentil", right: "kind" },
        ],
      },
      explanation: "These are common adjectives for describing people in French.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'She is tall and beautiful.'",
      content: {
        correctAnswer: "Elle est grande et belle.",
        acceptableAnswers: ["Elle est grande et belle.", "Elle est grande et belle", "elle est grande et belle"],
        direction: "to_target",
      },
      explanation: "Both adjectives take feminine forms: grande, belle. 'Elle' triggers feminine agreement.",
      hint: "Both adjectives must be feminine!",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'He has brown hair.'",
      content: {
        correctAnswer: "Il a les cheveux bruns.",
        acceptableAnswers: ["Il a les cheveux bruns.", "Il a les cheveux bruns", "il a les cheveux bruns"],
        direction: "to_target",
      },
      explanation: "Use 'avoir' (not 'être') with hair. 'Les cheveux' is always plural in French.",
      hint: "Hair uses 'avoir': il A les cheveux...",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in the correct order:",
      content: {
        words: ["est", "petite", "Elle", "et", "blonde"],
        correctOrder: ["Elle", "est", "petite", "et", "blonde"],
        translation: "She is short and blonde.",
      },
      explanation: "Subject + être + adjective + et + adjective.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 8,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and identify: How is the brother described?",
      content: {
        ttsText: "Mon frère est grand et brun. Il est très sympa.",
        ttsLang: "fr-FR",
        options: [
          "Tall, dark-haired, and nice",
          "Short, blonde, and funny",
          "Tall, blonde, and intelligent",
          "Short, dark-haired, and kind",
        ],
        correctIndex: 0,
      },
      explanation: "'Grand' = tall, 'brun' = dark-haired, 'sympa' = nice.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and identify what is being asked:",
      content: {
        ttsText: "Elle est comment, ta mère ?",
        ttsLang: "fr-FR",
        options: [
          "What is your mother like?",
          "Where is your mother?",
          "Who is your mother?",
          "How old is your mother?",
        ],
        correctIndex: 0,
      },
      explanation: "'Elle est comment ?' asks for a description of someone — their appearance or personality.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
    {
      exercise_type: "SPEAK",
      question: "Describe someone as tall and intelligent:",
      content: {
        targetText: "Elle est grande et intelligente",
        targetTranslation: "She is tall and intelligent",
        acceptableVariants: ["elle est grande et intelligente", "Elle est grande et intelligente!"],
      },
      hint: "Both adjectives must be feminine to match 'elle'.",
      explanation: "Feminine forms: grande, intelligente. Both match 'elle'.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 11,
    },
    {
      exercise_type: "SPEAK",
      question: "Say someone is very funny:",
      content: {
        targetText: "Il est très drôle",
        targetTranslation: "He is very funny",
        acceptableVariants: ["il est très drôle", "Il est très drôle!"],
      },
      hint: "Pronounce it: eel ay TRAY DROHL",
      explanation: "'Drôle' is invariable — same form for masculine and feminine.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 12,
    },
  ],
};
