export const frenchA1U2L4 = {
  metadata: {
    course: "fr-a1",
    unit: 2,
    lesson: 4,
    title: "Family Members",
    slug: "family-members",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },
  content: {
    introduction: {
      text: "Family is at the heart of French life! In this lesson you will learn the vocabulary for family members and how to use possessive adjectives (my, your, his/her) to talk about the people closest to you. You will be able to describe your family in French by the end of this lesson.",
      image: "/images/lessons/family.svg",
      culturalNote: "🇫🇷 Sunday lunch with the extended family is a cherished French tradition. These meals can last several hours with multiple courses — from apéritif to dessert!",
    },

    vocabulary: [
      {
        term: "La famille",
        translation: "The family",
        pronunciation: "lah fah-MEE",
        partOfSpeech: "noun",
        image: "/images/vocab/family.svg",
        audio: "/audio/fr/famille.mp3",
        exampleSentence: {
          original: "Ma famille est grande.",
          translation: "My family is big.",
        },
        tip: "Feminine noun. 'Ma famille' = my family.",
      },
      {
        term: "Le père",
        translation: "The father",
        pronunciation: "luh PAIR",
        partOfSpeech: "noun",
        image: "/images/vocab/father.svg",
        audio: "/audio/fr/pere.mp3",
        exampleSentence: {
          original: "Mon père s'appelle Jean.",
          translation: "My father's name is Jean.",
        },
        tip: "Masculine — use 'mon' (my) before it.",
      },
      {
        term: "La mère",
        translation: "The mother",
        pronunciation: "lah MAIR",
        partOfSpeech: "noun",
        image: "/images/vocab/mother.svg",
        audio: "/audio/fr/mere.mp3",
        exampleSentence: {
          original: "Ma mère est professeur.",
          translation: "My mother is a teacher.",
        },
        tip: "Feminine — use 'ma' (my) before it.",
      },
      {
        term: "Le frère",
        translation: "The brother",
        pronunciation: "luh FRAIR",
        partOfSpeech: "noun",
        image: "/images/vocab/brother.svg",
        audio: "/audio/fr/frere.mp3",
        exampleSentence: {
          original: "J'ai un frère.",
          translation: "I have a brother.",
        },
        tip: "'Mon frère' = my brother. The accent grave (è) is important!",
      },
      {
        term: "La sœur",
        translation: "The sister",
        pronunciation: "lah SUHR",
        partOfSpeech: "noun",
        image: "/images/vocab/sister.svg",
        audio: "/audio/fr/soeur.mp3",
        exampleSentence: {
          original: "Ma sœur a quinze ans.",
          translation: "My sister is fifteen years old.",
        },
        tip: "The 'œ' is a special French letter. 'Sœur' rhymes with 'heure' (hour).",
      },
      {
        term: "Les parents",
        translation: "The parents",
        pronunciation: "lay pah-RAHN",
        partOfSpeech: "noun",
        image: "/images/vocab/parents.svg",
        audio: "/audio/fr/parents.mp3",
        exampleSentence: {
          original: "Mes parents habitent à Nice.",
          translation: "My parents live in Nice.",
        },
        tip: "Plural — use 'mes' (my). Can also mean 'relatives' in some contexts.",
      },
      {
        term: "Le fils",
        translation: "The son",
        pronunciation: "luh FEESS",
        partOfSpeech: "noun",
        image: "/images/vocab/son.svg",
        audio: "/audio/fr/fils.mp3",
        exampleSentence: {
          original: "Il a un fils.",
          translation: "He has a son.",
        },
        tip: "The 'l' and 's' are pronounced! Unlike most French words where final consonants are silent.",
      },
      {
        term: "La fille",
        translation: "The daughter / girl",
        pronunciation: "lah FEE-yuh",
        partOfSpeech: "noun",
        image: "/images/vocab/daughter.svg",
        audio: "/audio/fr/fille.mp3",
        exampleSentence: {
          original: "Elle a une fille.",
          translation: "She has a daughter.",
        },
        tip: "Means both 'daughter' and 'girl'. Context makes it clear.",
      },
      {
        term: "Le grand-père",
        translation: "The grandfather",
        pronunciation: "luh grahn-PAIR",
        partOfSpeech: "noun",
        image: "/images/vocab/grandfather.svg",
        audio: "/audio/fr/grand-pere.mp3",
        exampleSentence: {
          original: "Mon grand-père a quatre-vingts ans.",
          translation: "My grandfather is eighty years old.",
        },
        tip: "'Grand' + 'père' = grandfather. Simple compound word!",
      },
      {
        term: "La grand-mère",
        translation: "The grandmother",
        pronunciation: "lah grahn-MAIR",
        partOfSpeech: "noun",
        image: "/images/vocab/grandmother.svg",
        audio: "/audio/fr/grand-mere.mp3",
        exampleSentence: {
          original: "Ma grand-mère cuisine très bien.",
          translation: "My grandmother cooks very well.",
        },
        tip: "Note: 'grand-mère' keeps 'grand' (not 'grande') — it is an exception!",
      },
    ],

    grammar: [
      {
        title: "Possessive Adjectives (mon, ma, mes / ton, ta, tes)",
        explanation: "In French, possessive adjectives agree with the noun they describe (not the owner!). 'Mon' is for masculine singular nouns, 'ma' for feminine singular, and 'mes' for plural. Important: before feminine words starting with a vowel or silent 'h', use 'mon' instead of 'ma' for easier pronunciation.",
        examples: [
          {
            original: "Mon père est grand.",
            translation: "My father is tall.",
            breakdown: "Mon (my, masc.) + père (father, masc.) → 'mon' matches the noun",
          },
          {
            original: "Ma mère est française.",
            translation: "My mother is French.",
            breakdown: "Ma (my, fem.) + mère (mother, fem.) → 'ma' matches the noun",
          },
          {
            original: "Mes parents sont gentils.",
            translation: "My parents are nice.",
            breakdown: "Mes (my, plural) + parents (plural) → 'mes' for any plural noun",
          },
          {
            original: "Mon amie s'appelle Marie.",
            translation: "My (female) friend is named Marie.",
            breakdown: "Mon (not 'ma') before 'amie' because it starts with a vowel",
          },
        ],
        table: {
          headers: ["Owner", "Masculine Sing.", "Feminine Sing.", "Plural"],
          rows: [
            ["my", "mon", "ma", "mes"],
            ["your (informal)", "ton", "ta", "tes"],
            ["his / her", "son", "sa", "ses"],
          ],
        },
        commonMistakes: [
          "❌ Don't say 'ma ami' — say 'mon amie' (use 'mon' before vowels even for feminine).",
          "✅ The possessive agrees with the NOUN, not the owner. A man says 'ma mère' just like a woman does.",
          "❌ Don't confuse 'son père' — it means both 'his father' AND 'her father'!",
        ],
      },
    ],

    dialogue: {
      title: "Talking About Family",
      context: "Lucas tells Sophie about his family over coffee.",
      image: "/images/dialogues/coffee-family.svg",
      lines: [
        {
          speaker: "Sophie",
          text: "Tu as des frères et sœurs ?",
          translation: "Do you have brothers and sisters?",
          audio: "/audio/fr/dialogue/u2l4-line1.mp3",
        },
        {
          speaker: "Lucas",
          text: "Oui, j'ai un frère et une sœur.",
          translation: "Yes, I have a brother and a sister.",
          audio: "/audio/fr/dialogue/u2l4-line2.mp3",
        },
        {
          speaker: "Sophie",
          text: "Ils s'appellent comment ?",
          translation: "What are their names?",
          audio: "/audio/fr/dialogue/u2l4-line3.mp3",
        },
        {
          speaker: "Lucas",
          text: "Mon frère s'appelle Thomas et ma sœur s'appelle Julie.",
          translation: "My brother is called Thomas and my sister is called Julie.",
          audio: "/audio/fr/dialogue/u2l4-line4.mp3",
        },
        {
          speaker: "Sophie",
          text: "Et tes parents, ils habitent où ?",
          translation: "And your parents, where do they live?",
          audio: "/audio/fr/dialogue/u2l4-line5.mp3",
        },
        {
          speaker: "Lucas",
          text: "Mes parents habitent à Marseille. Et toi, tu as une grande famille ?",
          translation: "My parents live in Marseille. And you, do you have a big family?",
          audio: "/audio/fr/dialogue/u2l4-line6.mp3",
        },
      ],
      comprehensionQuestions: [
        {
          question: "How many siblings does Lucas have?",
          options: ["None", "One brother", "One brother and one sister", "Two brothers"],
          correctIndex: 2,
        },
        {
          question: "Where do Lucas's parents live?",
          options: ["Paris", "Lyon", "Marseille", "Nice"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "Family in French Culture",
      text: "Family is central to French life. Grandparents ('les grands-parents') often play an active role in childcare. The French government provides significant family support, including 'allocations familiales' (family allowances) for families with children. Extended family gatherings, especially during holidays like Christmas and Easter, are important social occasions.",
      image: "/images/culture/french-family.svg",
      funFact: "🤯 France has one of the highest birth rates in Europe! The average French family has about two children. The government actively encourages families through financial incentives.",
    },

    summary: {
      keyPoints: [
        "'Mon' (masculine), 'ma' (feminine), 'mes' (plural) = my",
        "'Ton', 'ta', 'tes' = your (informal)",
        "Possessive adjectives agree with the NOUN, not the owner",
        "Use 'mon' before feminine nouns starting with a vowel: 'mon amie'",
        "Key family vocab: père, mère, frère, sœur, fils, fille, parents",
        "'Tu as des frères et sœurs ?' = Do you have brothers and sisters?",
      ],
      practicePrompt: "Draw a simple family tree and label each member in French using possessive adjectives: mon père, ma mère, mon frère, ma sœur, etc.",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "How do you say 'my mother' in French?",
      content: {
        options: ["mon mère", "ma mère", "mes mère", "la mère"],
        correctIndex: 1,
      },
      explanation: "'Mère' is feminine singular, so use 'ma' — ma mère.",
      hint: "Which possessive adjective is used for feminine singular nouns?",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "Which possessive adjective completes: '_____ parents habitent à Lyon.'?",
      content: {
        options: ["Mon", "Ma", "Mes", "Ton"],
        correctIndex: 2,
      },
      explanation: "'Parents' is plural, so use 'mes' — mes parents.",
      hint: "Parents is a plural noun. Which form is for plural?",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: _____ frère s'appelle Thomas. (My brother is called Thomas.)",
      content: {
        sentence: "_____ frère s'appelle Thomas.",
        answer: "Mon",
        options: ["Mon", "Ma", "Mes", "Ton"],
        caseSensitive: false,
      },
      explanation: "'Frère' is masculine singular → 'mon frère'.",
      hint: "Brother is masculine. Which possessive goes with masculine singular?",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: J'ai un frère et une _____. (I have a brother and a sister.)",
      content: {
        sentence: "J'ai un frère et une _____.",
        answer: "sœur",
        options: ["sœur", "frère", "père", "fille"],
        caseSensitive: false,
      },
      explanation: "'Sœur' means sister. 'Une sœur' = a sister.",
      hint: "The word for 'sister' in French.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 4,
    },
    {
      exercise_type: "MATCHING",
      question: "Match the French family words to their English meanings:",
      content: {
        pairs: [
          { left: "le père", right: "the father" },
          { left: "la mère", right: "the mother" },
          { left: "le frère", right: "the brother" },
          { left: "la sœur", right: "the sister" },
          { left: "les enfants", right: "the children" },
        ],
      },
      explanation: "Notice how family members use different articles: le (masc.), la (fem.), les (plural).",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'My parents live in Paris.'",
      content: {
        correctAnswer: "Mes parents habitent à Paris.",
        acceptableAnswers: ["Mes parents habitent à Paris.", "Mes parents habitent à Paris", "mes parents habitent à Paris", "Mes parents habitent a Paris"],
        direction: "to_target",
      },
      explanation: "'Parents' is plural → 'mes'. 'Habiter à' for cities.",
      hint: "Plural noun = 'mes'. City = 'à'.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I have a brother.'",
      content: {
        correctAnswer: "J'ai un frère.",
        acceptableAnswers: ["J'ai un frère.", "J'ai un frère", "j'ai un frère"],
        direction: "to_target",
      },
      explanation: "'J'ai' = I have. 'Un frère' = a brother.",
      hint: "I have = J'ai.",
      difficulty: "EASY",
      xp_reward: 3,
      order_index: 7,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in the correct order:",
      content: {
        words: ["s'appelle", "sœur", "Julie", "Ma"],
        correctOrder: ["Ma", "sœur", "s'appelle", "Julie"],
        translation: "My sister is called Julie.",
      },
      explanation: "Possessive + noun + verb + name: Ma sœur s'appelle Julie.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 8,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and answer: How many siblings does this person have?",
      content: {
        ttsText: "J'ai un frère et deux sœurs.",
        ttsLang: "fr-FR",
        options: ["1 brother and 1 sister", "2 brothers and 1 sister", "1 brother and 2 sisters", "2 brothers and 2 sisters"],
        correctIndex: 2,
      },
      explanation: "'Un frère' = 1 brother, 'deux sœurs' = 2 sisters.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and answer: What does the mother do?",
      content: {
        ttsText: "Mon père est médecin et ma mère est professeur.",
        ttsLang: "fr-FR",
        options: ["Doctor", "Teacher", "Lawyer", "Engineer"],
        correctIndex: 1,
      },
      explanation: "'Ma mère est professeur' — My mother is a teacher.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence about your brother:",
      content: {
        targetText: "Mon frère s'appelle Thomas",
        targetTranslation: "My brother is called Thomas",
        acceptableVariants: ["mon frère s'appelle Thomas", "Mon frère s'appelle Thomas!"],
      },
      hint: "Pronounce it: mohn FRAIR sah-PELL toh-MAH",
      explanation: "'Mon frère' = my brother. 'S'appelle' = is called.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 11,
    },
    {
      exercise_type: "SPEAK",
      question: "Say you have a sister:",
      content: {
        targetText: "J'ai une sœur",
        targetTranslation: "I have a sister",
        acceptableVariants: ["j'ai une sœur", "J'ai une sœur!", "j'ai une soeur"],
      },
      hint: "Pronounce it: ZHAY oon SUHR",
      explanation: "'J'ai' = I have. 'Une sœur' = a sister.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 12,
    },
  ],
};
