export const frenchA1U2L7 = {
  metadata: {
    course: "fr-a1",
    unit: 2,
    lesson: 7,
    title: "Hobbies & Interests",
    slug: "hobbies-interests",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },
  content: {
    introduction: {
      text: "What do you like to do in your free time? In this lesson you will learn to express likes and dislikes using the verbs 'aimer' (to like), 'adorer' (to love), and 'détester' (to hate). The key structure is simple: aimer + infinitive verb. By the end, you can talk about your hobbies and interests entirely in French!",
      image: "/images/lessons/hobbies.svg",
      culturalNote: "🇫🇷 The French take their leisure time seriously! 'Le temps libre' (free time) is essential for quality of life. Popular hobbies include reading, cinema, and gastronomy. The expression 'la joie de vivre' (the joy of living) captures the French philosophy of savoring life.",
    },

    vocabulary: [
      {
        term: "Aimer",
        translation: "To like / To love",
        pronunciation: "ay-MAY",
        partOfSpeech: "verb",
        image: "/images/vocab/like.svg",
        audio: "/audio/fr/aimer.mp3",
        exampleSentence: {
          original: "J'aime la musique.",
          translation: "I like music.",
        },
        tip: "'J'aime' can mean both 'I like' and 'I love' depending on context. With people it means 'I love.'",
      },
      {
        term: "Adorer",
        translation: "To love / To adore",
        pronunciation: "ah-doh-RAY",
        partOfSpeech: "verb",
        image: "/images/vocab/love.svg",
        audio: "/audio/fr/adorer.mp3",
        exampleSentence: {
          original: "J'adore voyager.",
          translation: "I love traveling.",
        },
        tip: "Stronger than 'aimer'. Use for things you are really passionate about.",
      },
      {
        term: "Détester",
        translation: "To hate",
        pronunciation: "day-tes-TAY",
        partOfSpeech: "verb",
        image: "/images/vocab/hate.svg",
        audio: "/audio/fr/detester.mp3",
        exampleSentence: {
          original: "Je déteste le froid.",
          translation: "I hate the cold.",
        },
        tip: "Strong word! For something milder, use 'ne pas aimer' (to not like).",
      },
      {
        term: "Lire",
        translation: "To read",
        pronunciation: "LEER",
        partOfSpeech: "verb",
        image: "/images/vocab/read.svg",
        audio: "/audio/fr/lire.mp3",
        exampleSentence: {
          original: "J'aime lire des livres.",
          translation: "I like reading books.",
        },
        tip: "Irregular verb! But you only need the infinitive form for now: 'aimer lire'.",
      },
      {
        term: "Voyager",
        translation: "To travel",
        pronunciation: "vwah-yah-ZHAY",
        partOfSpeech: "verb",
        image: "/images/vocab/travel.svg",
        audio: "/audio/fr/voyager.mp3",
        exampleSentence: {
          original: "J'adore voyager en Europe.",
          translation: "I love traveling in Europe.",
        },
        tip: "Regular -er verb. 'Un voyage' = a trip.",
      },
      {
        term: "Cuisiner",
        translation: "To cook",
        pronunciation: "kwee-zee-NAY",
        partOfSpeech: "verb",
        image: "/images/vocab/cook.svg",
        audio: "/audio/fr/cuisiner.mp3",
        exampleSentence: {
          original: "Ma mère aime cuisiner.",
          translation: "My mother likes cooking.",
        },
        tip: "'La cuisine' means both 'the kitchen' and 'cooking/cuisine.'",
      },
      {
        term: "Regarder",
        translation: "To watch",
        pronunciation: "ruh-gar-DAY",
        partOfSpeech: "verb",
        image: "/images/vocab/watch.svg",
        audio: "/audio/fr/regarder.mp3",
        exampleSentence: {
          original: "J'aime regarder des films.",
          translation: "I like watching movies.",
        },
        tip: "'Un film' = a movie. 'Un film français' = a French movie.",
      },
      {
        term: "Écouter",
        translation: "To listen to",
        pronunciation: "ay-koo-TAY",
        partOfSpeech: "verb",
        image: "/images/vocab/listen.svg",
        audio: "/audio/fr/ecouter.mp3",
        exampleSentence: {
          original: "J'écoute de la musique.",
          translation: "I listen to music.",
        },
        tip: "No preposition needed! In English you 'listen TO', but French just says 'écouter'.",
      },
      {
        term: "Jouer",
        translation: "To play",
        pronunciation: "zhoo-AY",
        partOfSpeech: "verb",
        image: "/images/vocab/play.svg",
        audio: "/audio/fr/jouer.mp3",
        exampleSentence: {
          original: "Il aime jouer au football.",
          translation: "He likes playing football.",
        },
        tip: "'Jouer à' = play a sport. 'Jouer de' = play an instrument.",
      },
      {
        term: "La musique",
        translation: "Music",
        pronunciation: "lah moo-ZEEK",
        partOfSpeech: "noun",
        image: "/images/vocab/music.svg",
        audio: "/audio/fr/musique.mp3",
        exampleSentence: {
          original: "J'adore la musique française.",
          translation: "I love French music.",
        },
        tip: "Feminine noun. Use 'la' when talking about music in general: 'J'aime la musique.'",
      },
    ],

    grammar: [
      {
        title: "Aimer + Infinitive (Liking to Do Something)",
        explanation: "To express what you like to do, use 'aimer' (conjugated) + infinitive verb. The same pattern works with 'adorer' (love doing) and 'détester' (hate doing). When 'aimer' is followed by a noun instead of a verb, use the definite article (le, la, les). Scale of preference: adorer > aimer bien > aimer > ne pas aimer > détester.",
        examples: [
          {
            original: "J'aime lire.",
            translation: "I like to read.",
            breakdown: "J'aime (I like) + lire (to read) — conjugated verb + infinitive",
          },
          {
            original: "J'adore voyager.",
            translation: "I love to travel.",
            breakdown: "J'adore (I love) + voyager (to travel)",
          },
          {
            original: "Je déteste cuisiner.",
            translation: "I hate cooking.",
            breakdown: "Je déteste (I hate) + cuisiner (to cook)",
          },
          {
            original: "J'aime la musique.",
            translation: "I like music.",
            breakdown: "J'aime (I like) + la musique (music) — article needed before nouns",
          },
        ],
        table: {
          headers: ["Level", "French", "English"],
          rows: [
            ["❤️❤️❤️", "J'adore", "I love / I adore"],
            ["❤️❤️", "J'aime beaucoup", "I really like"],
            ["❤️", "J'aime", "I like"],
            ["😐", "J'aime bien", "I kind of like"],
            ["👎", "Je n'aime pas", "I don't like"],
            ["💔", "Je déteste", "I hate"],
          ],
        },
        commonMistakes: [
          "❌ Don't say 'J'aime lire livres' — after 'aimer + verb', add 'des': 'J'aime lire des livres.'",
          "✅ With nouns, use the article: 'J'aime LA musique' (not 'j'aime musique').",
          "❌ Don't confuse: 'J'aime bien' (I kind of like) is WEAKER than 'J'aime' (I like)!",
        ],
      },
    ],

    dialogue: {
      title: "What Do You Like to Do?",
      context: "Lucas and Sophie talk about their hobbies at a park in Lyon.",
      image: "/images/dialogues/park-hobbies.svg",
      lines: [
        {
          speaker: "Lucas",
          text: "Qu'est-ce que tu aimes faire le week-end ?",
          translation: "What do you like to do on the weekend?",
          audio: "/audio/fr/dialogue/u2l7-line1.mp3",
        },
        {
          speaker: "Sophie",
          text: "J'adore lire et écouter de la musique. Et toi ?",
          translation: "I love reading and listening to music. And you?",
          audio: "/audio/fr/dialogue/u2l7-line2.mp3",
        },
        {
          speaker: "Lucas",
          text: "Moi, j'aime jouer au football et regarder des films.",
          translation: "Me, I like playing football and watching movies.",
          audio: "/audio/fr/dialogue/u2l7-line3.mp3",
        },
        {
          speaker: "Sophie",
          text: "Tu aimes cuisiner ?",
          translation: "Do you like cooking?",
          audio: "/audio/fr/dialogue/u2l7-line4.mp3",
        },
        {
          speaker: "Lucas",
          text: "Non, je déteste cuisiner ! Mais j'adore manger !",
          translation: "No, I hate cooking! But I love eating!",
          audio: "/audio/fr/dialogue/u2l7-line5.mp3",
        },
        {
          speaker: "Sophie",
          text: "Ha ha ! Moi aussi, j'adore manger !",
          translation: "Ha ha! Me too, I love eating!",
          audio: "/audio/fr/dialogue/u2l7-line6.mp3",
        },
      ],
      comprehensionQuestions: [
        {
          question: "What does Sophie love doing?",
          options: ["Cooking and sports", "Reading and listening to music", "Watching movies", "Playing football"],
          correctIndex: 1,
        },
        {
          question: "Does Lucas like cooking?",
          options: ["Yes, he loves it", "He likes it a little", "No, he hates it", "He doesn't mention it"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "Leisure & 'La Joie de Vivre'",
      text: "The French have a deep appreciation for leisure and pleasure. France has the most-visited museums in the world, and going to a café just to people-watch is a beloved pastime. French people typically take a full hour for lunch, and weekends are for family, friends, and hobbies. The concept of 'la joie de vivre' (the joy of living) means savoring good food, good company, and the simple pleasures of life.",
      image: "/images/culture/joie-de-vivre.svg",
      funFact: "🤯 France invented cinema! The Lumière brothers held the first public movie screening in Paris in 1895. Today, France produces more films per year than any other European country.",
    },

    summary: {
      keyPoints: [
        "'Aimer + infinitive' = to like doing something: 'J'aime lire'",
        "'Adorer + infinitive' = to love doing something: 'J'adore voyager'",
        "'Détester + infinitive' = to hate doing something: 'Je déteste cuisiner'",
        "With nouns, use the article: 'J'aime LA musique' (not just 'musique')",
        "'Qu'est-ce que tu aimes faire ?' = What do you like to do?",
        "Scale: adorer > aimer > aimer bien > ne pas aimer > détester",
      ],
      practicePrompt: "List three things you love, three things you like, and three things you hate in French. Example: 'J'adore voyager. J'aime la musique. Je déteste cuisiner.'",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "How do you say 'I love to travel' in French?",
      content: {
        options: ["Je suis voyager", "J'adore voyager", "J'ai voyager", "Je voyage adorer"],
        correctIndex: 1,
      },
      explanation: "'Adorer' + infinitive: J'adore voyager. The first verb is conjugated, the second stays in infinitive.",
      hint: "Conjugated verb + infinitive. Which means 'to love/adore'?",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What is the correct order of preference from strongest to weakest?",
      content: {
        options: [
          "adorer > aimer > détester",
          "aimer > adorer > détester",
          "détester > aimer > adorer",
          "adorer > détester > aimer",
        ],
        correctIndex: 0,
      },
      explanation: "Adorer (love) > aimer (like) > détester (hate). From most positive to most negative.",
      hint: "Which word means the strongest positive feeling?",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: J'_____ lire des livres. (I like to read books.)",
      content: {
        sentence: "J'_____ lire des livres.",
        answer: "aime",
        options: ["aime", "adore", "ai", "suis"],
        caseSensitive: false,
      },
      explanation: "'Aimer' with 'je' → 'j'aime'. The apostrophe replaces the 'e' before a vowel.",
      hint: "The verb meaning 'to like', conjugated with 'je'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Elle _____ de la musique. (She listens to music.)",
      content: {
        sentence: "Elle _____ de la musique.",
        answer: "écoute",
        options: ["écoute", "écouter", "écoutes", "écouté"],
        caseSensitive: false,
      },
      explanation: "'Écouter' with 'elle' → 'écoute'. Regular -er verb conjugation.",
      hint: "Third person singular of 'écouter'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "MATCHING",
      question: "Match each hobby verb to its English meaning:",
      content: {
        pairs: [
          { left: "lire", right: "to read" },
          { left: "voyager", right: "to travel" },
          { left: "cuisiner", right: "to cook" },
          { left: "danser", right: "to dance" },
          { left: "regarder", right: "to watch" },
        ],
      },
      explanation: "Most of these are regular -er verbs. 'Lire' is the exception — it is irregular.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I hate cooking.'",
      content: {
        correctAnswer: "Je déteste cuisiner.",
        acceptableAnswers: ["Je déteste cuisiner.", "Je déteste cuisiner", "je déteste cuisiner", "Je deteste cuisiner"],
        direction: "to_target",
      },
      explanation: "'Détester' + infinitive: Je déteste cuisiner.",
      hint: "Détester + the infinitive of 'to cook'.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'She loves to dance.'",
      content: {
        correctAnswer: "Elle adore danser.",
        acceptableAnswers: ["Elle adore danser.", "Elle adore danser", "elle adore danser"],
        direction: "to_target",
      },
      explanation: "'Adorer' + infinitive: Elle adore danser.",
      hint: "She = Elle. Loves = adore. To dance = danser.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in the correct order:",
      content: {
        words: ["regarder", "aime", "des", "J'", "films"],
        correctOrder: ["J'", "aime", "regarder", "des", "films"],
        translation: "I like to watch movies.",
      },
      explanation: "Subject + conjugated verb + infinitive + object: J'aime regarder des films.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 8,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and answer: What does this person like and dislike?",
      content: {
        ttsText: "J'adore cuisiner et voyager. Je déteste le sport.",
        ttsLang: "fr-FR",
        options: [
          "Loves cooking and traveling, hates sport",
          "Loves sport and traveling, hates cooking",
          "Loves cooking and sport, hates traveling",
          "Loves reading and traveling, hates cooking",
        ],
        correctIndex: 0,
      },
      explanation: "'Adore cuisiner et voyager' = loves cooking and traveling. 'Déteste le sport' = hates sport.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and identify the question:",
      content: {
        ttsText: "Qu'est-ce que tu aimes faire le week-end ?",
        ttsLang: "fr-FR",
        options: [
          "What do you like to do on the weekend?",
          "What did you do on the weekend?",
          "Where do you go on the weekend?",
          "When is the weekend?",
        ],
        correctIndex: 0,
      },
      explanation: "'Qu'est-ce que tu aimes faire' = What do you like to do. 'Le week-end' = on the weekend.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
    {
      exercise_type: "SPEAK",
      question: "Say what you love to do:",
      content: {
        targetText: "J'adore lire",
        targetTranslation: "I love to read",
        acceptableVariants: ["j'adore lire", "J'adore lire!", "j adore lire"],
      },
      hint: "Pronounce it: zhah-DOR LEER",
      explanation: "'J'adore' + infinitive. Simple and expressive!",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 11,
    },
    {
      exercise_type: "SPEAK",
      question: "Say you like listening to music:",
      content: {
        targetText: "J'aime écouter de la musique",
        targetTranslation: "I like to listen to music",
        acceptableVariants: ["j'aime écouter de la musique", "J'aime écouter de la musique!", "j'aime ecouter de la musique"],
      },
      hint: "Pronounce it: ZHEM ay-koo-TAY duh lah moo-ZEEK",
      explanation: "'Écouter de la musique' = to listen to music. No preposition like 'to' needed in French!",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 12,
    },
  ],
};
