export const frenchA1U2L1 = {
  metadata: {
    course: "fr-a1",
    unit: 2,
    lesson: 1,
    title: "Talking About Yourself",
    slug: "talking-about-yourself",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },
  content: {
    introduction: {
      text: "Time to talk about yourself! In this lesson you will learn to share your name, where you live, and what languages you speak. These are the building blocks of every French conversation. By the end, you will be able to give a short self-introduction entirely in French.",
      image: "/images/lessons/about-yourself.svg",
      culturalNote: "🇫🇷 In France, when meeting someone new in a casual setting, it is common to quickly share your name, where you are from, and what you do. The French appreciate concise, warm introductions.",
    },

    vocabulary: [
      {
        term: "Je suis",
        translation: "I am",
        pronunciation: "zhuh SWEE",
        partOfSpeech: "verb phrase",
        image: "/images/vocab/i-am.svg",
        audio: "/audio/fr/je-suis.mp3",
        exampleSentence: {
          original: "Je suis étudiant.",
          translation: "I am a student.",
        },
        tip: "From the verb 'être' (to be). You will use this constantly!",
      },
      {
        term: "Je m'appelle",
        translation: "My name is",
        pronunciation: "zhuh mah-PELL",
        partOfSpeech: "verb phrase",
        image: "/images/vocab/name.svg",
        audio: "/audio/fr/je-mappelle.mp3",
        exampleSentence: {
          original: "Je m'appelle Sophie.",
          translation: "My name is Sophie.",
        },
        tip: "Literally means 'I call myself.' This is the standard way to give your name.",
      },
      {
        term: "J'habite à",
        translation: "I live in",
        pronunciation: "zhah-BEET ah",
        partOfSpeech: "verb phrase",
        image: "/images/vocab/live.svg",
        audio: "/audio/fr/jhabite.mp3",
        exampleSentence: {
          original: "J'habite à Paris.",
          translation: "I live in Paris.",
        },
        tip: "Use 'à' before city names: j'habite à Lyon, j'habite à Marseille.",
      },
      {
        term: "Je parle",
        translation: "I speak",
        pronunciation: "zhuh PARL",
        partOfSpeech: "verb phrase",
        image: "/images/vocab/speak.svg",
        audio: "/audio/fr/je-parle.mp3",
        exampleSentence: {
          original: "Je parle français et anglais.",
          translation: "I speak French and English.",
        },
        tip: "Regular -er verb. No article needed before language names after 'parler'.",
      },
      {
        term: "J'ai",
        translation: "I have",
        pronunciation: "ZHAY",
        partOfSpeech: "verb phrase",
        image: "/images/vocab/i-have.svg",
        audio: "/audio/fr/jai.mp3",
        exampleSentence: {
          original: "J'ai vingt ans.",
          translation: "I am twenty years old.",
        },
        tip: "From the verb 'avoir' (to have). Also used for age in French!",
      },
      {
        term: "Et toi ?",
        translation: "And you? (informal)",
        pronunciation: "ay TWAH",
        partOfSpeech: "phrase",
        image: "/images/vocab/and-you.svg",
        audio: "/audio/fr/et-toi.mp3",
        exampleSentence: {
          original: "Je suis française. Et toi ?",
          translation: "I am French. And you?",
        },
        tip: "Use 'Et vous ?' in formal situations. 'Toi' is for friends and peers.",
      },
      {
        term: "Un peu",
        translation: "A little",
        pronunciation: "uhn PUH",
        partOfSpeech: "adverb",
        image: "/images/vocab/a-little.svg",
        audio: "/audio/fr/un-peu.mp3",
        exampleSentence: {
          original: "Je parle un peu français.",
          translation: "I speak a little French.",
        },
        tip: "Very useful when you are learning! 'Je comprends un peu' = I understand a little.",
      },
      {
        term: "Aussi",
        translation: "Also / Too",
        pronunciation: "oh-SEE",
        partOfSpeech: "adverb",
        image: "/images/vocab/also.svg",
        audio: "/audio/fr/aussi.mp3",
        exampleSentence: {
          original: "Moi aussi, je parle anglais.",
          translation: "Me too, I speak English.",
        },
        tip: "'Moi aussi' = 'Me too.' Very common in conversation.",
      },
      {
        term: "Une ville",
        translation: "A city",
        pronunciation: "oon VEEL",
        partOfSpeech: "noun",
        image: "/images/vocab/city.svg",
        audio: "/audio/fr/ville.mp3",
        exampleSentence: {
          original: "Paris est une grande ville.",
          translation: "Paris is a big city.",
        },
        tip: "Feminine noun — 'une' ville, 'la' ville.",
      },
    ],

    grammar: [
      {
        title: "The Verb 'Être' (To Be) — Present Tense",
        explanation: "Être is one of the two most important French verbs. It is irregular, meaning you must memorize each form. Use 'être' to describe identity, nationality, profession, and characteristics.",
        examples: [
          {
            original: "Je suis français.",
            translation: "I am French.",
            breakdown: "Je (I) + suis (am) + français (French)",
          },
          {
            original: "Tu es étudiant ?",
            translation: "Are you a student?",
            breakdown: "Tu (you) + es (are) + étudiant (student)",
          },
          {
            original: "Elle est professeur.",
            translation: "She is a teacher.",
            breakdown: "Elle (she) + est (is) + professeur (teacher)",
          },
        ],
        table: {
          headers: ["Pronoun", "Form", "Example"],
          rows: [
            ["je", "suis", "Je suis grand."],
            ["tu", "es", "Tu es française ?"],
            ["il / elle", "est", "Il est sympa."],
            ["nous", "sommes", "Nous sommes étudiants."],
            ["vous", "êtes", "Vous êtes français ?"],
            ["ils / elles", "sont", "Ils sont contents."],
          ],
        },
        commonMistakes: [
          "❌ Don't say 'Je suis vingt ans' — age uses 'avoir' not 'être'.",
          "✅ Say 'J'ai vingt ans' (I have twenty years).",
          "❌ Don't confuse 'es' (tu) with 'est' (il/elle) — they sound different!",
        ],
      },
    ],

    dialogue: {
      title: "Meeting at a Café",
      context: "Lucas and Sophie meet for the first time at a café in Lyon.",
      image: "/images/dialogues/cafe-meeting.svg",
      lines: [
        {
          speaker: "Lucas",
          text: "Bonjour ! Je m'appelle Lucas. Et toi ?",
          translation: "Hello! My name is Lucas. And you?",
          audio: "/audio/fr/dialogue/u2l1-line1.mp3",
        },
        {
          speaker: "Sophie",
          text: "Salut ! Je m'appelle Sophie. Je suis étudiante.",
          translation: "Hi! My name is Sophie. I am a student.",
          audio: "/audio/fr/dialogue/u2l1-line2.mp3",
        },
        {
          speaker: "Lucas",
          text: "Moi aussi ! J'habite à Lyon. Et toi ?",
          translation: "Me too! I live in Lyon. And you?",
          audio: "/audio/fr/dialogue/u2l1-line3.mp3",
        },
        {
          speaker: "Sophie",
          text: "J'habite à Paris. Je parle français et anglais.",
          translation: "I live in Paris. I speak French and English.",
          audio: "/audio/fr/dialogue/u2l1-line4.mp3",
        },
        {
          speaker: "Lucas",
          text: "Super ! Je parle un peu espagnol aussi.",
          translation: "Great! I speak a little Spanish too.",
          audio: "/audio/fr/dialogue/u2l1-line5.mp3",
        },
        {
          speaker: "Sophie",
          text: "C'est génial ! Enchantée, Lucas !",
          translation: "That's awesome! Nice to meet you, Lucas!",
          audio: "/audio/fr/dialogue/u2l1-line6.mp3",
        },
      ],
      comprehensionQuestions: [
        {
          question: "Where does Sophie live?",
          options: ["Lyon", "Paris", "Marseille", "Nice"],
          correctIndex: 1,
        },
        {
          question: "What languages does Lucas speak?",
          options: ["French only", "French and English", "French and a little Spanish", "French, English and Spanish"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "Tutoyer vs Vouvoyer",
      text: "In French, there are two ways to say 'you'. 'Tu' is informal — used with friends, family, and people your age. 'Vous' is formal — used with strangers, elders, and in professional settings. When meeting someone your age in a casual setting, it is common to switch to 'tu' quickly. Using 'tu' is called 'tutoyer' and using 'vous' is called 'vouvoyer'. If unsure, start with 'vous' — the other person may say 'On peut se tutoyer' (We can use tu).",
      image: "/images/culture/tu-vous.svg",
      funFact: "🤯 Some French couples who met in a formal setting continue to use 'vous' with each other for years — even after getting married!",
    },

    summary: {
      keyPoints: [
        "'Je m'appelle...' is the standard way to give your name",
        "'J'habite à + city' tells where you live",
        "'Je parle + language' describes what languages you speak",
        "The verb 'être' (to be) is irregular — memorize je suis, tu es, il/elle est",
        "'Et toi ?' (informal) or 'Et vous ?' (formal) to ask 'And you?'",
        "'Un peu' means 'a little' — great for when you are still learning!",
      ],
      practicePrompt: "Try writing a short self-introduction in French: your name, where you live, and what languages you speak. Say it out loud three times!",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "How do you say 'My name is Marie' in French?",
      content: {
        options: ["Je suis Marie", "Je m'appelle Marie", "J'habite Marie", "Je parle Marie"],
        correctIndex: 1,
      },
      explanation: "'Je m'appelle' means 'my name is' (literally: I call myself). 'Je suis Marie' can work but 'Je m'appelle' is the standard way.",
      hint: "Which phrase literally means 'I call myself'?",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What does 'J'habite à Paris' mean?",
      content: {
        options: ["I love Paris", "I live in Paris", "I visit Paris", "I am from Paris"],
        correctIndex: 1,
      },
      explanation: "'J'habite à' means 'I live in'. The verb 'habiter' means 'to live (somewhere)'. Use 'à' before city names.",
      hint: "'Habiter' is about where you reside.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Je _____ étudiant. (I am a student.)",
      content: {
        sentence: "Je _____ étudiant.",
        answer: "suis",
        options: ["suis", "ai", "parle", "habite"],
        caseSensitive: false,
      },
      explanation: "'Je suis' means 'I am'. The verb 'être' with 'je' becomes 'suis'.",
      hint: "Conjugation of 'être' with 'je'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Je _____ français et anglais. (I speak French and English.)",
      content: {
        sentence: "Je _____ français et anglais.",
        answer: "parle",
        options: ["parle", "suis", "habite", "appelle"],
        caseSensitive: false,
      },
      explanation: "'Je parle' means 'I speak'. Regular -er verb conjugation with 'je'.",
      hint: "The verb meaning 'to speak'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "MATCHING",
      question: "Match each French phrase to its English meaning:",
      content: {
        pairs: [
          { left: "Je m'appelle", right: "My name is" },
          { left: "J'habite à", right: "I live in" },
          { left: "Je parle", right: "I speak" },
          { left: "Je suis", right: "I am" },
          { left: "J'ai", right: "I have" },
        ],
      },
      explanation: "These five phrases are the building blocks of any self-introduction in French.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I live in Paris.'",
      content: {
        correctAnswer: "J'habite à Paris.",
        acceptableAnswers: ["J'habite à Paris.", "J'habite à Paris", "j'habite à Paris", "J'habite a Paris"],
        direction: "to_target",
      },
      explanation: "'J'habite à Paris' — use 'habiter' + 'à' + city name.",
      hint: "'I live' = j'habite, 'in' (before a city) = à.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I speak a little French.'",
      content: {
        correctAnswer: "Je parle un peu français.",
        acceptableAnswers: ["Je parle un peu français.", "Je parle un peu français", "je parle un peu français", "Je parle un peu francais"],
        direction: "to_target",
      },
      explanation: "'Un peu' means 'a little'. Place it between the verb and the language.",
      hint: "'Un peu' goes after the verb.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in the correct order:",
      content: {
        words: ["m'appelle", "Sophie", "Je"],
        correctOrder: ["Je", "m'appelle", "Sophie"],
        translation: "My name is Sophie.",
      },
      explanation: "French word order: Subject + Verb + Name. 'Je m'appelle Sophie.'",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 8,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and select what you hear:",
      content: {
        ttsText: "Je m'appelle Lucas et j'habite à Lyon.",
        ttsLang: "fr-FR",
        options: [
          "My name is Lucas and I live in Lyon.",
          "My name is Lucas and I live in Paris.",
          "My name is Sophie and I live in Lyon.",
          "My name is Lucas and I speak French.",
        ],
        correctIndex: 0,
      },
      explanation: "'Je m'appelle Lucas et j'habite à Lyon' = My name is Lucas and I live in Lyon.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and answer: What does this person speak?",
      content: {
        ttsText: "Je parle français et un peu anglais.",
        ttsLang: "fr-FR",
        options: [
          "French and a little English",
          "French and Spanish",
          "English and a little French",
          "French and German",
        ],
        correctIndex: 0,
      },
      explanation: "'Je parle français et un peu anglais' = I speak French and a little English.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this introduction out loud:",
      content: {
        targetText: "Je m'appelle Sophie",
        targetTranslation: "My name is Sophie",
        acceptableVariants: ["je m'appelle Sophie", "Je m'appelle Sophie!", "je m'appelle sophie"],
      },
      hint: "Pronounce it: zhuh mah-PELL soh-FEE",
      explanation: "'Je m'appelle' is pronounced 'zhuh mah-PELL'. This is the standard way to give your name.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 11,
    },
    {
      exercise_type: "SPEAK",
      question: "Now say where you live:",
      content: {
        targetText: "J'habite à Paris",
        targetTranslation: "I live in Paris",
        acceptableVariants: ["j'habite à Paris", "J'habite à Paris!", "j'habite a Paris"],
      },
      hint: "Pronounce it: zhah-BEET ah pah-REE",
      explanation: "'J'habite à Paris' — the 'h' in 'habite' is silent.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 12,
    },
  ],
};
