export const frenchA1U2L6 = {
  metadata: {
    course: "fr-a1",
    unit: 2,
    lesson: 6,
    title: "Ages & Birthdays",
    slug: "ages-birthdays",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },
  content: {
    introduction: {
      text: "How old are you? Here is the tricky part — French uses the verb 'avoir' (to have) for age, NOT 'être' (to be)! You literally say 'I have 20 years.' In this lesson you will master this essential structure, learn numbers by tens up to fifty, months of the year, and birthday vocabulary.",
      image: "/images/lessons/birthday.svg",
      culturalNote: "🇫🇷 In France, the birthday person often brings the cake! At work, it is traditional to bring treats for your colleagues on your birthday. The big milestone birthday is 18 — when you become a legal adult.",
    },

    vocabulary: [
      {
        term: "Quel âge as-tu ?",
        translation: "How old are you? (informal)",
        pronunciation: "kell AHZH ah-TOO",
        partOfSpeech: "phrase",
        image: "/images/vocab/age-question.svg",
        audio: "/audio/fr/quel-age.mp3",
        exampleSentence: {
          original: "Quel âge as-tu ? — J'ai vingt ans.",
          translation: "How old are you? — I am twenty.",
        },
        tip: "Literally means 'What age do you have?' French uses 'avoir' for age!",
      },
      {
        term: "J'ai ... ans",
        translation: "I am ... years old",
        pronunciation: "ZHAY ... AHN",
        partOfSpeech: "phrase",
        image: "/images/vocab/years-old.svg",
        audio: "/audio/fr/jai-ans.mp3",
        exampleSentence: {
          original: "J'ai vingt-cinq ans.",
          translation: "I am twenty-five years old.",
        },
        tip: "Literally 'I have ... years.' Never say 'Je suis vingt ans'!",
      },
      {
        term: "Vingt",
        translation: "Twenty (20)",
        pronunciation: "VAN",
        partOfSpeech: "number",
        image: "/images/vocab/twenty.svg",
        audio: "/audio/fr/vingt.mp3",
        exampleSentence: {
          original: "Elle a vingt ans.",
          translation: "She is twenty years old.",
        },
        tip: "The 'gt' is silent when alone, but pronounced in 'vingt et un' (21).",
      },
      {
        term: "Trente",
        translation: "Thirty (30)",
        pronunciation: "TRAHNT",
        partOfSpeech: "number",
        image: "/images/vocab/thirty.svg",
        audio: "/audio/fr/trente.mp3",
        exampleSentence: {
          original: "Il a trente-deux ans.",
          translation: "He is thirty-two years old.",
        },
        tip: "Add a hyphen and a number for 31-39: trente-et-un, trente-deux, etc.",
      },
      {
        term: "Quarante",
        translation: "Forty (40)",
        pronunciation: "kah-RAHNT",
        partOfSpeech: "number",
        image: "/images/vocab/forty.svg",
        audio: "/audio/fr/quarante.mp3",
        exampleSentence: {
          original: "Mon père a quarante-cinq ans.",
          translation: "My father is forty-five years old.",
        },
        tip: "Starts with 'qua-' like 'quatre' (four). Same pattern: quarante-et-un, quarante-deux...",
      },
      {
        term: "Cinquante",
        translation: "Fifty (50)",
        pronunciation: "san-KAHNT",
        partOfSpeech: "number",
        image: "/images/vocab/fifty.svg",
        audio: "/audio/fr/cinquante.mp3",
        exampleSentence: {
          original: "Ma mère a cinquante ans.",
          translation: "My mother is fifty years old.",
        },
        tip: "Starts with 'cinq-' like 'cinq' (five).",
      },
      {
        term: "Un anniversaire",
        translation: "A birthday",
        pronunciation: "uhn ah-nee-vair-SAIR",
        partOfSpeech: "noun",
        image: "/images/vocab/birthday.svg",
        audio: "/audio/fr/anniversaire.mp3",
        exampleSentence: {
          original: "Mon anniversaire est en mars.",
          translation: "My birthday is in March.",
        },
        tip: "Also used for anniversaries. 'Joyeux anniversaire !' = Happy birthday!",
      },
      {
        term: "Janvier",
        translation: "January",
        pronunciation: "zhahn-vee-AY",
        partOfSpeech: "noun",
        image: "/images/vocab/january.svg",
        audio: "/audio/fr/janvier.mp3",
        exampleSentence: {
          original: "Mon anniversaire est en janvier.",
          translation: "My birthday is in January.",
        },
        tip: "Months are NOT capitalized in French! Use 'en' before months: 'en janvier'.",
      },
      {
        term: "Joyeux anniversaire !",
        translation: "Happy birthday!",
        pronunciation: "zhwah-YUH ah-nee-vair-SAIR",
        partOfSpeech: "phrase",
        image: "/images/vocab/happy-birthday.svg",
        audio: "/audio/fr/joyeux-anniversaire.mp3",
        exampleSentence: {
          original: "Joyeux anniversaire, Sophie !",
          translation: "Happy birthday, Sophie!",
        },
        tip: "'Joyeux' means 'joyful/happy'. The song is the same melody as in English!",
      },
    ],

    grammar: [
      {
        title: "Expressing Age with 'Avoir' (To Have)",
        explanation: "This is one of the biggest differences between French and English. In English you say 'I AM 20 years old' (using 'to be'). In French you say 'J'AI 20 ans' (using 'to have'). You literally 'have' years. This is a very common mistake for English speakers — always use 'avoir' for age!",
        examples: [
          {
            original: "J'ai vingt ans.",
            translation: "I am twenty years old.",
            breakdown: "J'ai (I have) + vingt (20) + ans (years) — literally 'I have 20 years'",
          },
          {
            original: "Quel âge as-tu ?",
            translation: "How old are you? (informal)",
            breakdown: "Quel (what) + âge (age) + as-tu (do you have) — 'What age do you have?'",
          },
          {
            original: "Mon père a cinquante ans.",
            translation: "My father is fifty years old.",
            breakdown: "Mon père (my father) + a (has) + cinquante (50) + ans (years)",
          },
        ],
        table: {
          headers: ["Pronoun", "Avoir", "Example"],
          rows: [
            ["j'", "ai", "J'ai vingt ans."],
            ["tu", "as", "Tu as quel âge ?"],
            ["il / elle", "a", "Il a trente ans."],
            ["nous", "avons", "Nous avons vingt-cinq ans."],
            ["vous", "avez", "Vous avez quel âge ?"],
            ["ils / elles", "ont", "Ils ont quarante ans."],
          ],
        },
        commonMistakes: [
          "❌ NEVER say 'Je suis vingt ans' — this is the #1 mistake!",
          "✅ ALWAYS say 'J'ai vingt ans' — age uses 'avoir'.",
          "❌ Don't forget 'ans' at the end: 'J'ai vingt' is incomplete. Say 'J'ai vingt ANS.'",
        ],
      },
    ],

    dialogue: {
      title: "Happy Birthday!",
      context: "Pierre and Claire discuss ages and birthdays at a party.",
      image: "/images/dialogues/birthday-party.svg",
      lines: [
        {
          speaker: "Pierre",
          text: "Joyeux anniversaire, Claire !",
          translation: "Happy birthday, Claire!",
          audio: "/audio/fr/dialogue/u2l6-line1.mp3",
        },
        {
          speaker: "Claire",
          text: "Merci beaucoup, Pierre !",
          translation: "Thank you very much, Pierre!",
          audio: "/audio/fr/dialogue/u2l6-line2.mp3",
        },
        {
          speaker: "Pierre",
          text: "Quel âge as-tu maintenant ?",
          translation: "How old are you now?",
          audio: "/audio/fr/dialogue/u2l6-line3.mp3",
        },
        {
          speaker: "Claire",
          text: "J'ai vingt-cinq ans ! Et toi, ton anniversaire, c'est quand ?",
          translation: "I'm twenty-five! And you, when is your birthday?",
          audio: "/audio/fr/dialogue/u2l6-line4.mp3",
        },
        {
          speaker: "Pierre",
          text: "Mon anniversaire est en septembre. J'ai vingt-sept ans.",
          translation: "My birthday is in September. I'm twenty-seven.",
          audio: "/audio/fr/dialogue/u2l6-line5.mp3",
        },
        {
          speaker: "Claire",
          text: "On est jeunes ! Allez, on fait la fête !",
          translation: "We're young! Come on, let's party!",
          audio: "/audio/fr/dialogue/u2l6-line6.mp3",
        },
      ],
      comprehensionQuestions: [
        {
          question: "How old is Claire?",
          options: ["23", "25", "27", "30"],
          correctIndex: 1,
        },
        {
          question: "When is Pierre's birthday?",
          options: ["January", "March", "September", "December"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "Birthdays and Name Days",
      text: "In France, each day of the calendar is associated with a saint's name. If your name matches the saint of the day, people might wish you 'Bonne fête !' (Happy name day!). While less common now, it is still a charming tradition. For birthdays, the French sing the same 'Happy Birthday' melody but with the words 'Joyeux anniversaire !' The 18th birthday is the most significant — it marks legal adulthood.",
      image: "/images/culture/birthday-france.svg",
      funFact: "🤯 At a French birthday party, the birthday person blows out all candles at once while making a secret wish. If even one stays lit, the wish won't come true!",
    },

    summary: {
      keyPoints: [
        "Age uses 'avoir' NOT 'être': 'J'ai 20 ans' (NOT 'Je suis 20 ans')",
        "'Quel âge as-tu ?' = How old are you? (informal)",
        "Numbers by tens: vingt (20), trente (30), quarante (40), cinquante (50)",
        "'Mon anniversaire est en + month' = My birthday is in...",
        "Months are NOT capitalized in French",
        "'Joyeux anniversaire !' = Happy birthday!",
      ],
      practicePrompt: "Say your age and birthday in French: 'J'ai [number] ans. Mon anniversaire est en [month].' Practice with family members' ages too!",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "How do you say 'I am 25 years old' in French?",
      content: {
        options: ["Je suis vingt-cinq ans", "J'ai vingt-cinq ans", "J'ai vingt-cinq", "Je suis vingt-cinq"],
        correctIndex: 1,
      },
      explanation: "French uses 'avoir' for age: J'ai + number + ans. Never use 'être' for age!",
      hint: "Age uses 'avoir' (to have), not 'être' (to be).",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What does 'Quel âge as-tu ?' mean?",
      content: {
        options: ["What is your name?", "How old are you?", "Where are you from?", "What do you do?"],
        correctIndex: 1,
      },
      explanation: "'Quel âge as-tu ?' literally means 'What age do you have?' It's how you ask someone's age.",
      hint: "'Âge' = age. 'As-tu' = do you have.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Mon père _____ cinquante ans. (My father is fifty.)",
      content: {
        sentence: "Mon père _____ cinquante ans.",
        answer: "a",
        options: ["a", "est", "ai", "as"],
        caseSensitive: false,
      },
      explanation: "'Avoir' with il/elle → 'a'. Mon père a cinquante ans.",
      hint: "Third person singular of 'avoir'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete: Mon anniversaire est en _____. (My birthday is in January.)",
      content: {
        sentence: "Mon anniversaire est en _____.",
        answer: "janvier",
        options: ["janvier", "Janvier", "janvié", "januier"],
        caseSensitive: false,
      },
      explanation: "'Janvier' = January. Remember: months are not capitalized in French!",
      hint: "First month of the year. Not capitalized in French.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "MATCHING",
      question: "Match the French numbers to their values:",
      content: {
        pairs: [
          { left: "vingt", right: "20" },
          { left: "trente", right: "30" },
          { left: "quarante", right: "40" },
          { left: "cinquante", right: "50" },
          { left: "janvier", right: "January" },
        ],
      },
      explanation: "These numbers follow a pattern similar to the single digits you already know.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I am thirty years old.'",
      content: {
        correctAnswer: "J'ai trente ans.",
        acceptableAnswers: ["J'ai trente ans.", "J'ai trente ans", "j'ai trente ans"],
        direction: "to_target",
      },
      explanation: "Use 'avoir' for age: J'ai trente ans. Not 'Je suis trente ans'!",
      hint: "Avoir + number + ans.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'Happy birthday!'",
      content: {
        correctAnswer: "Joyeux anniversaire !",
        acceptableAnswers: ["Joyeux anniversaire !", "Joyeux anniversaire", "joyeux anniversaire", "Joyeux anniversaire!"],
        direction: "to_target",
      },
      explanation: "'Joyeux' = happy/joyful. 'Anniversaire' = birthday/anniversary.",
      hint: "Joyeux + the French word for birthday.",
      difficulty: "EASY",
      xp_reward: 3,
      order_index: 7,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in the correct order:",
      content: {
        words: ["vingt", "J'ai", "ans"],
        correctOrder: ["J'ai", "vingt", "ans"],
        translation: "I am twenty years old.",
      },
      explanation: "J'ai (I have) + number + ans (years): J'ai vingt ans.",
      difficulty: "EASY",
      xp_reward: 4,
      order_index: 8,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and answer: How old is this person and when is their birthday?",
      content: {
        ttsText: "J'ai trente-deux ans. Mon anniversaire est en mars.",
        ttsLang: "fr-FR",
        options: [
          "32 years old, birthday in March",
          "22 years old, birthday in March",
          "32 years old, birthday in May",
          "42 years old, birthday in March",
        ],
        correctIndex: 0,
      },
      explanation: "'Trente-deux' = 32. 'En mars' = in March.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and identify what is being asked:",
      content: {
        ttsText: "Quel âge a ta mère ?",
        ttsLang: "fr-FR",
        options: [
          "How old is your mother?",
          "Where is your mother?",
          "What is your mother's name?",
          "What does your mother do?",
        ],
        correctIndex: 0,
      },
      explanation: "'Quel âge a ta mère ?' = How old is your mother? (Literally: What age has your mother?)",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
    {
      exercise_type: "SPEAK",
      question: "Say your age in French:",
      content: {
        targetText: "J'ai vingt ans",
        targetTranslation: "I am twenty years old",
        acceptableVariants: ["j'ai vingt ans", "J'ai vingt ans!", "j ai vingt ans"],
      },
      hint: "Pronounce it: ZHAY van AHN",
      explanation: "Remember: 'J'ai' (I have) NOT 'Je suis' (I am). Age uses 'avoir'!",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 11,
    },
    {
      exercise_type: "SPEAK",
      question: "Wish someone a happy birthday:",
      content: {
        targetText: "Joyeux anniversaire",
        targetTranslation: "Happy birthday",
        acceptableVariants: ["joyeux anniversaire", "Joyeux anniversaire!", "Joyeux anniversaire !"],
      },
      hint: "Pronounce it: zhwah-YUH ah-nee-vair-SAIR",
      explanation: "This is the standard French birthday greeting. Same melody as the English song!",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 12,
    },
  ],
};
