export const frenchA1U8L3 = {
  metadata: {
    course: "fr-a1",
    unit: 8,
    lesson: 3,
    title: "At the Doctor's Office",
    slug: "at-the-doctor",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },

  content: {
    introduction: {
      text: "In this lesson, you'll learn essential vocabulary for visiting a doctor in France. From making an appointment to describing your symptoms, these words will help you navigate the French healthcare system with confidence.",
      image: "/images/lessons/doctor-office.svg",
      culturalNote: "🇫🇷 In France, you usually need to see a 'médecin traitant' (general practitioner) first before seeing a specialist. Most doctor visits cost around €25, and the national health insurance (Sécurité sociale) reimburses about 70%.",
    },

    vocabulary: [
      {
        term: "un médecin",
        translation: "a doctor",
        pronunciation: "uhn mayd-SAHN",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/doctor.svg",
        exampleSentence: {
          original: "Je vais chez le médecin.",
          translation: "I'm going to the doctor.",
        },
        tip: "'Aller chez le médecin' = to go to the doctor. Use 'chez' for people.",
      },
      {
        term: "un rendez-vous",
        translation: "an appointment",
        pronunciation: "uhn rahn-day-VOO",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/appointment.svg",
        exampleSentence: {
          original: "J'ai un rendez-vous à quatorze heures.",
          translation: "I have an appointment at 2 PM.",
        },
        tip: "Abbreviated as 'RDV'. Also means 'a date' in romantic contexts!",
      },
      {
        term: "un cabinet médical",
        translation: "a doctor's office",
        pronunciation: "uhn kah-bee-NEH may-dee-KAL",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/medical-office.svg",
        exampleSentence: {
          original: "Le cabinet médical est près de chez moi.",
          translation: "The doctor's office is near my home.",
        },
        tip: "'Cabinet' alone can mean office or practice for any professional.",
      },
      {
        term: "un médicament",
        translation: "a medicine / medication",
        pronunciation: "uhn may-dee-kah-MAHN",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/medicine.svg",
        exampleSentence: {
          original: "Le médecin prescrit un médicament.",
          translation: "The doctor prescribes a medicine.",
        },
        tip: "Plural: 'des médicaments'. Only available at pharmacies in France!",
      },
      {
        term: "une ordonnance",
        translation: "a prescription",
        pronunciation: "ewn or-doh-NAHNS",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/prescription.svg",
        exampleSentence: {
          original: "Le médecin écrit une ordonnance.",
          translation: "The doctor writes a prescription.",
        },
        tip: "You need this to buy prescription medicines at the pharmacy.",
      },
      {
        term: "examiner",
        translation: "to examine",
        pronunciation: "eg-zah-mee-NAY",
        partOfSpeech: "verb",
        image: "/images/vocab/examine.svg",
        exampleSentence: {
          original: "Le médecin examine le patient.",
          translation: "The doctor examines the patient.",
        },
        tip: "Regular -er verb. 'Un examen' = an exam/test (medical or school).",
      },
      {
        term: "un symptôme",
        translation: "a symptom",
        pronunciation: "uhn sahmp-TOHM",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/symptom.svg",
        exampleSentence: {
          original: "Quels sont vos symptômes ?",
          translation: "What are your symptoms?",
        },
        tip: "Cognate with English 'symptom'. The circumflex (ô) replaces a historical 's'.",
      },
      {
        term: "respirer",
        translation: "to breathe",
        pronunciation: "reh-spee-RAY",
        partOfSpeech: "verb",
        image: "/images/vocab/breathe.svg",
        exampleSentence: {
          original: "Respirez profondément.",
          translation: "Breathe deeply.",
        },
        tip: "Regular -er verb. The doctor will say this: 'Respirez !' (Breathe!)",
      },
      {
        term: "la salle d'attente",
        translation: "the waiting room",
        pronunciation: "lah sahl dah-TAHNT",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/waiting-room.svg",
        exampleSentence: {
          original: "Je suis dans la salle d'attente.",
          translation: "I'm in the waiting room.",
        },
        tip: "Literally 'room of waiting'. You'll spend time here at French medical offices!",
      },
      {
        term: "prendre la température",
        translation: "to take the temperature",
        pronunciation: "PRAHN-druh lah tahm-pay-rah-TEWR",
        partOfSpeech: "expression",
        image: "/images/vocab/temperature.svg",
        exampleSentence: {
          original: "L'infirmière prend ma température.",
          translation: "The nurse takes my temperature.",
        },
        tip: "In France, temperature is measured in Celsius. Normal is 37°C.",
      },
    ],

    grammar: [
      {
        title: "Medical Vocabulary with 'aller chez' and 'aller à'",
        explanation: "In French, you go 'chez' a person (doctor, dentist) but 'à' a place (hospital, pharmacy). This distinction is important for medical contexts.",
        examples: [
          {
            original: "Je vais chez le médecin.",
            translation: "I'm going to the doctor.",
            breakdown: "chez (at/to the place of) + le médecin (the doctor) — person",
          },
          {
            original: "Je vais à l'hôpital.",
            translation: "I'm going to the hospital.",
            breakdown: "à (to) + l'hôpital (the hospital) — place",
          },
          {
            original: "Je vais à la pharmacie.",
            translation: "I'm going to the pharmacy.",
            breakdown: "à (to) + la pharmacie (the pharmacy) — place",
          },
        ],
        commonMistakes: [
          "❌ Je vais au médecin (wrong — use 'chez' for people)",
          "✅ Je vais chez le médecin (correct — 'chez' for people)",
          "❌ Je vais chez l'hôpital (wrong — use 'à' for places)",
          "✅ Je vais à l'hôpital (correct — 'à' for places)",
        ],
      },
    ],

    dialogue: {
      title: "The Doctor's Visit",
      context: "Pierre visits his doctor because he doesn't feel well.",
      image: "/images/dialogues/doctor-visit.svg",
      lines: [
        {
          speaker: "pierre",
          text: "Bonjour, docteur. J'ai un rendez-vous à dix heures.",
          translation: "Hello, doctor. I have an appointment at ten.",
        },
        {
          speaker: "marie",
          text: "Bonjour, Pierre. Asseyez-vous. Qu'est-ce qui ne va pas ?",
          translation: "Hello, Pierre. Sit down. What's wrong?",
        },
        {
          speaker: "pierre",
          text: "Je ne me sens pas bien. J'ai mal à la gorge et je tousse.",
          translation: "I don't feel well. My throat hurts and I cough.",
        },
        {
          speaker: "marie",
          text: "Depuis quand ?",
          translation: "Since when?",
        },
        {
          speaker: "pierre",
          text: "Depuis trois jours. Et j'ai de la fièvre.",
          translation: "For three days. And I have a fever.",
        },
        {
          speaker: "marie",
          text: "Je vais vous examiner. Ouvrez la bouche. Respirez profondément.",
          translation: "I'm going to examine you. Open your mouth. Breathe deeply.",
        },
        {
          speaker: "pierre",
          text: "C'est grave, docteur ?",
          translation: "Is it serious, doctor?",
        },
        {
          speaker: "marie",
          text: "Non, c'est un rhume. Je vous fais une ordonnance. Allez à la pharmacie.",
          translation: "No, it's a cold. I'll write you a prescription. Go to the pharmacy.",
        },
      ],
      comprehensionQuestions: [
        {
          question: "How long has Pierre been sick?",
          options: ["One day", "Two days", "Three days", "A week"],
          correctIndex: 2,
        },
        {
          question: "What does the doctor diagnose?",
          options: ["The flu", "A cold", "An allergy", "A broken bone"],
          correctIndex: 1,
        },
      ],
    },

    culture: {
      title: "Visiting the Doctor in France",
      text: "In France, the healthcare system is one of the best in the world. Most people have a 'médecin traitant' (family doctor) whom they see for general health issues. A standard consultation costs about €25, of which the 'Sécurité sociale' (national health insurance) reimburses about 70%. Most French people also have a 'mutuelle' (supplementary insurance) that covers the rest. You usually don't need an appointment for your médecin traitant — many accept walk-ins during consultation hours.",
      image: "/images/culture/french-doctor.svg",
      funFact: "🎉 France has the green cross (croix verte) as the symbol for pharmacies. These illuminated green crosses are everywhere and often display the temperature and time — making French pharmacies easy to spot, even at night!",
    },

    summary: {
      keyPoints: [
        "'Aller chez le médecin' = to go to the doctor (chez for people)",
        "'Aller à l'hôpital / à la pharmacie' = to go to the hospital/pharmacy (à for places)",
        "Un rendez-vous = an appointment",
        "Une ordonnance = a prescription",
        "Un médicament = a medicine",
        "'Respirez' = Breathe!, 'Ouvrez la bouche' = Open your mouth",
        "Normal body temperature in France: 37°C",
      ],
      practicePrompt: "Imagine you're at the doctor. Practice: 'Bonjour, docteur. Je ne me sens pas bien. J'ai mal à... J'ai de la fièvre. J'ai besoin d'une ordonnance.'",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "How do you say 'I'm going to the doctor' in French?",
      content: {
        options: [
          "Je vais au médecin",
          "Je vais chez le médecin",
          "Je vais à le médecin",
          "Je vais dans le médecin",
        ],
        correctIndex: 1,
      },
      hint: "Use 'chez' for going to a person",
      explanation: "'Je vais chez le médecin' — use 'chez' when going to see a person.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What is 'une ordonnance'?",
      content: {
        options: ["An appointment", "A prescription", "A medicine", "A symptom"],
        correctIndex: 1,
      },
      hint: "The doctor writes this for you to take to the pharmacy",
      explanation: "'Une ordonnance' = a prescription. You need it to get medication at the pharmacy.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "MATCHING",
      question: "Match the French medical words with their meanings:",
      content: {
        pairs: [
          { left: "un rendez-vous", right: "an appointment" },
          { left: "un médicament", right: "a medicine" },
          { left: "examiner", right: "to examine" },
          { left: "la salle d'attente", right: "waiting room" },
        ],
      },
      hint: "Think about what happens at a doctor's visit",
      explanation: "Rendez-vous = appointment, médicament = medicine, examiner = examine, salle d'attente = waiting room.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "Je vais ___ la pharmacie.",
        answer: "à",
        options: ["à", "chez", "dans", "au"],
        caseSensitive: false,
      },
      hint: "Pharmacy is a place, not a person",
      explanation: "'À la pharmacie' — use 'à' for places, 'chez' for people.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "Le médecin écrit une ___.",
        answer: "ordonnance",
        options: ["ordonnance", "médicament", "rendez-vous", "pharmacie"],
        caseSensitive: false,
      },
      hint: "The doctor writes this so you can get medicine",
      explanation: "'Le médecin écrit une ordonnance' = The doctor writes a prescription.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I have an appointment at the doctor.'",
      content: {
        correctAnswer: "J'ai un rendez-vous chez le médecin.",
        acceptableAnswers: [
          "J'ai un rendez-vous chez le médecin",
          "j'ai un rendez-vous chez le médecin",
        ],
        direction: "to_target",
      },
      hint: "Use 'chez' for the doctor (a person) and 'rendez-vous' for appointment",
      explanation: "'J'ai un rendez-vous chez le médecin.' — 'chez' for people, 'rendez-vous' for appointment.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in order:",
      content: {
        words: ["ordonnance", "une", "écrit", "médecin", "le"],
        correctOrder: ["le", "médecin", "écrit", "une", "ordonnance"],
        translation: "The doctor writes a prescription",
      },
      hint: "Subject + verb + object",
      explanation: "Correct order: Le médecin écrit une ordonnance. (The doctor writes a prescription.)",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and select the correct answer:",
      content: {
        ttsText: "Bonjour. J'ai un rendez-vous à quatorze heures. Je ne me sens pas bien.",
        ttsLang: "fr-FR",
        options: [
          "Hello. I have an appointment at 2 PM. I don't feel well.",
          "Hello. I need medicine. I feel fine.",
          "Goodbye. My appointment is at 4 PM. I feel great.",
          "Hello. I have a prescription. I feel tired.",
        ],
        correctIndex: 0,
      },
      hint: "Listen for 'rendez-vous', 'quatorze heures', and 'ne me sens pas bien'",
      explanation: "Arrival at the doctor: appointment time + stating you don't feel well.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 8,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "J'ai un rendez-vous chez le médecin.",
        targetTranslation: "I have an appointment at the doctor.",
        acceptableVariants: ["j'ai un rendez-vous chez le médecin"],
      },
      hint: "Remember: 'chez' for people",
      explanation: "Great! 'Chez le médecin' — correct use of 'chez' for a person.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "Ouvrez la bouche et respirez profondément.",
        targetTranslation: "Open your mouth and breathe deeply.",
        acceptableVariants: ["ouvrez la bouche et respirez profondément"],
      },
      hint: "Doctor's instructions — imperative form",
      explanation: "Excellent! These are common instructions you'll hear from a French doctor.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
  ],
};
