export const frenchA1U8L5 = {
  metadata: {
    course: "fr-a1",
    unit: 8,
    lesson: 5,
    title: "Pharmacy Vocabulary",
    slug: "pharmacy-vocabulary",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },

  content: {
    introduction: {
      text: "In this lesson, you'll learn essential vocabulary for visiting a French pharmacy. Pharmacies in France are much more than just shops — pharmacists are trained health professionals who can give medical advice, recommend treatments, and even help in emergencies.",
      image: "/images/lessons/pharmacy.svg",
      culturalNote: "🇫🇷 French pharmacies are identified by a glowing green cross. Pharmacists can diagnose minor illnesses, recommend over-the-counter medicines, and even measure your blood pressure. They're often the first stop for health advice before seeing a doctor!",
    },

    vocabulary: [
      {
        term: "la pharmacie",
        translation: "the pharmacy",
        pronunciation: "lah far-mah-SEE",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/pharmacy.svg",
        exampleSentence: {
          original: "Je vais à la pharmacie.",
          translation: "I'm going to the pharmacy.",
        },
        tip: "Look for the green cross (croix verte) to find a pharmacy in France.",
      },
      {
        term: "le pharmacien / la pharmacienne",
        translation: "the pharmacist (m/f)",
        pronunciation: "luh far-mah-SYAHN / lah far-mah-SYEN",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/pharmacist.svg",
        exampleSentence: {
          original: "Le pharmacien donne des conseils.",
          translation: "The pharmacist gives advice.",
        },
        tip: "French pharmacists study for 6 years and are highly qualified health professionals.",
      },
      {
        term: "un comprimé",
        translation: "a tablet / pill",
        pronunciation: "uhn kohm-pree-MAY",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/tablet.svg",
        exampleSentence: {
          original: "Prenez deux comprimés par jour.",
          translation: "Take two tablets per day.",
        },
        tip: "More specific than 'médicament'. Refers to the pill/tablet form.",
      },
      {
        term: "un sirop",
        translation: "a syrup",
        pronunciation: "uhn see-ROH",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/syrup.svg",
        exampleSentence: {
          original: "Prenez du sirop pour la toux.",
          translation: "Take syrup for the cough.",
        },
        tip: "'Sirop pour la toux' = cough syrup. A very common pharmacy purchase.",
      },
      {
        term: "un pansement",
        translation: "a bandage / plaster",
        pronunciation: "uhn pahn-suh-MAHN",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/bandage.svg",
        exampleSentence: {
          original: "J'ai besoin d'un pansement.",
          translation: "I need a bandage.",
        },
        tip: "For small cuts and scrapes. 'Un sparadrap' is specifically adhesive tape.",
      },
      {
        term: "la crème",
        translation: "the cream",
        pronunciation: "lah KREM",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/cream.svg",
        exampleSentence: {
          original: "Appliquez la crème deux fois par jour.",
          translation: "Apply the cream twice a day.",
        },
        tip: "'Crème solaire' = sunscreen. 'Crème hydratante' = moisturizer.",
      },
      {
        term: "la douleur",
        translation: "pain",
        pronunciation: "lah doo-LUR",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/pain-noun.svg",
        exampleSentence: {
          original: "J'ai une douleur au bras.",
          translation: "I have a pain in my arm.",
        },
        tip: "The pharmacist may ask: 'Où est la douleur ?' (Where is the pain?).",
      },
      {
        term: "la toux",
        translation: "the cough",
        pronunciation: "lah TOO",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/cough-noun.svg",
        exampleSentence: {
          original: "J'ai la toux depuis une semaine.",
          translation: "I've had a cough for a week.",
        },
        tip: "Related verb: 'tousser' (to cough). The 'x' is silent.",
      },
      {
        term: "sans ordonnance",
        translation: "without prescription / over-the-counter",
        pronunciation: "sahn or-doh-NAHNS",
        partOfSpeech: "expression",
        image: "/images/vocab/otc.svg",
        exampleSentence: {
          original: "Ce médicament est sans ordonnance.",
          translation: "This medicine is over-the-counter.",
        },
        tip: "Many common medicines in France require a prescription, even paracetamol in large quantities!",
      },
      {
        term: "trois fois par jour",
        translation: "three times a day",
        pronunciation: "trwah fwah par ZHOOR",
        partOfSpeech: "expression",
        image: "/images/vocab/three-times.svg",
        exampleSentence: {
          original: "Prenez ce médicament trois fois par jour.",
          translation: "Take this medicine three times a day.",
        },
        tip: "'Une fois' = once, 'deux fois' = twice, 'trois fois' = three times.",
      },
    ],

    grammar: [
      {
        title: "Dosage Instructions: 'fois par jour'",
        explanation: "Medication dosage in French follows a simple pattern: number + 'fois' (times) + 'par jour' (per day). You'll see this on every prescription and medication box in France.",
        examples: [
          {
            original: "Une fois par jour.",
            translation: "Once a day.",
            breakdown: "une fois (once) + par jour (per day)",
          },
          {
            original: "Deux comprimés, trois fois par jour.",
            translation: "Two tablets, three times a day.",
            breakdown: "deux comprimés (two tablets) + trois fois (three times) + par jour (per day)",
          },
          {
            original: "Avant les repas.",
            translation: "Before meals.",
            breakdown: "avant (before) + les repas (meals) — common timing instruction",
          },
        ],
        commonMistakes: [
          "❌ Trois temps par jour (wrong — 'temps' means time/weather, not 'times')",
          "✅ Trois fois par jour (correct — 'fois' means times/occasions)",
        ],
      },
    ],

    dialogue: {
      title: "At the Pharmacy Counter",
      context: "Emma goes to the pharmacy with her prescription.",
      image: "/images/dialogues/pharmacy-counter.svg",
      lines: [
        {
          speaker: "emma",
          text: "Bonjour ! J'ai une ordonnance de mon médecin.",
          translation: "Hello! I have a prescription from my doctor.",
        },
        {
          speaker: "julie",
          text: "Bonjour ! Donnez-moi votre ordonnance et votre carte vitale, s'il vous plaît.",
          translation: "Hello! Give me your prescription and your health card, please.",
        },
        {
          speaker: "emma",
          text: "Voilà. J'ai aussi mal à la tête. Vous avez quelque chose ?",
          translation: "Here you go. I also have a headache. Do you have something?",
        },
        {
          speaker: "julie",
          text: "Oui, je vous recommande du paracétamol. C'est sans ordonnance.",
          translation: "Yes, I recommend paracetamol. It's over-the-counter.",
        },
        {
          speaker: "emma",
          text: "Comment je prends le médicament ?",
          translation: "How do I take the medicine?",
        },
        {
          speaker: "julie",
          text: "Un comprimé, trois fois par jour, après les repas.",
          translation: "One tablet, three times a day, after meals.",
        },
        {
          speaker: "emma",
          text: "Et le sirop pour la toux ?",
          translation: "And the cough syrup?",
        },
        {
          speaker: "julie",
          text: "Deux cuillères, matin et soir. Bon rétablissement !",
          translation: "Two spoonfuls, morning and evening. Get well soon!",
        },
      ],
      comprehensionQuestions: [
        {
          question: "What does Emma bring to the pharmacy?",
          options: ["Money", "A prescription and health card", "Her ID", "A letter"],
          correctIndex: 1,
        },
        {
          question: "How often should Emma take the paracetamol?",
          options: ["Once a day", "Twice a day", "Three times a day", "Four times a day"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "The French Pharmacy",
      text: "French pharmacies are unique. They are identified by a green cross and are found in every neighborhood. Pharmacists are highly trained — they complete six years of study and can diagnose minor ailments, recommend treatments, and even perform basic health checks like measuring blood pressure. Many medicines that are over-the-counter in other countries require a prescription in France. Pharmacies also sell cosmetics, skincare, and baby products. There is always a 'pharmacie de garde' (duty pharmacy) open at night and on weekends for emergencies.",
      image: "/images/culture/french-pharmacy.svg",
      funFact: "🎉 In France, you can bring wild mushrooms you've picked to any pharmacy and the pharmacist will identify them for you for free — telling you which ones are safe to eat and which are poisonous! This service has been available for over 100 years.",
    },

    summary: {
      keyPoints: [
        "La pharmacie = pharmacy (look for the green cross)",
        "Essential items: comprimé (tablet), sirop (syrup), pansement (bandage), crème (cream)",
        "Dosage: 'fois par jour' = times per day",
        "'Sans ordonnance' = over-the-counter / without prescription",
        "'Carte vitale' = French health insurance card",
        "Pharmacists can give medical advice and recommend treatments",
      ],
      practicePrompt: "Practice a pharmacy conversation: 'Bonjour, j'ai une ordonnance. J'ai aussi mal à la tête. Comment je prends ce médicament ?' Describe your symptoms and ask for advice.",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What symbol identifies a French pharmacy?",
      content: {
        options: ["A red cross", "A green cross", "A blue sign", "A white flag"],
        correctIndex: 1,
      },
      hint: "It glows at night and often shows the temperature",
      explanation: "French pharmacies are identified by a glowing green cross (croix verte).",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What does 'un comprimé' mean?",
      content: {
        options: ["A syrup", "A cream", "A tablet/pill", "A bandage"],
        correctIndex: 2,
      },
      hint: "It's a solid form of medicine you swallow",
      explanation: "'Un comprimé' = a tablet or pill. 'Prenez deux comprimés' = Take two tablets.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "MATCHING",
      question: "Match the pharmacy items with their meanings:",
      content: {
        pairs: [
          { left: "un sirop", right: "a syrup" },
          { left: "un pansement", right: "a bandage" },
          { left: "la crème", right: "the cream" },
          { left: "une ordonnance", right: "a prescription" },
        ],
      },
      hint: "Think about different forms of medicine and medical documents",
      explanation: "Sirop = syrup, pansement = bandage, crème = cream, ordonnance = prescription.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "Prenez un comprimé trois ___ par jour.",
        answer: "fois",
        options: ["fois", "temps", "heures", "jours"],
        caseSensitive: false,
      },
      hint: "'Times' in the sense of 'occasions'",
      explanation: "'Trois fois par jour' = three times per day. 'Fois' = times/occasions.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "Ce médicament est ___ ordonnance.",
        answer: "sans",
        options: ["sans", "avec", "pour", "dans"],
        caseSensitive: false,
      },
      hint: "The medicine doesn't require a doctor's note",
      explanation: "'Sans ordonnance' = without prescription / over-the-counter.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I need cough syrup.'",
      content: {
        correctAnswer: "J'ai besoin de sirop pour la toux.",
        acceptableAnswers: [
          "J'ai besoin de sirop pour la toux",
          "j'ai besoin de sirop pour la toux",
          "J'ai besoin d'un sirop pour la toux.",
          "J'ai besoin d'un sirop pour la toux",
        ],
        direction: "to_target",
      },
      hint: "Use 'avoir besoin de' and 'sirop pour la toux'",
      explanation: "'J'ai besoin de sirop pour la toux.' — 'avoir besoin de' + item needed.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in order:",
      content: {
        words: ["jour", "comprimé", "par", "un", "fois", "trois"],
        correctOrder: ["un", "comprimé", "trois", "fois", "par", "jour"],
        translation: "One tablet three times per day",
      },
      hint: "Quantity + item + frequency",
      explanation: "Correct order: Un comprimé, trois fois par jour. (One tablet, three times a day.)",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and select the correct answer:",
      content: {
        ttsText: "Prenez deux comprimés, matin et soir, après les repas.",
        ttsLang: "fr-FR",
        options: [
          "Take two tablets, morning and evening, after meals",
          "Take one tablet, three times a day, before meals",
          "Take the syrup, once a day, before bed",
          "Take two spoonfuls, in the morning, with water",
        ],
        correctIndex: 0,
      },
      hint: "Listen for 'deux comprimés', 'matin et soir', 'après les repas'",
      explanation: "Dosage instructions: two tablets, morning and evening, after meals.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 8,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "J'ai besoin d'un pansement, s'il vous plaît.",
        targetTranslation: "I need a bandage, please.",
        acceptableVariants: ["j'ai besoin d'un pansement s'il vous plaît"],
      },
      hint: "A polite pharmacy request",
      explanation: "Great! A polite request at the pharmacy using 'avoir besoin de'.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "Comment je prends ce médicament ?",
        targetTranslation: "How do I take this medicine?",
        acceptableVariants: ["comment je prends ce médicament"],
      },
      hint: "An essential question to ask your pharmacist",
      explanation: "Excellent! Always ask this question when getting medicine at a French pharmacy.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
  ],
};
