export const frenchA1U8L2 = {
  metadata: {
    course: "fr-a1",
    unit: 8,
    lesson: 2,
    title: "Avoir mal à... Structure",
    slug: "avoir-mal-a",
    type: "GRAMMAR",
    estimatedMinutes: 15,
    xpReward: 25,
  },

  content: {
    introduction: {
      text: "In this lesson, you'll master the essential structure 'avoir mal à...' (to have pain in...) used to describe where you hurt. You'll also learn how to ask someone where they have pain, and how to describe symptoms. This is critical vocabulary for any health situation in France.",
      image: "/images/lessons/avoir-mal.svg",
      culturalNote: "🇫🇷 In France, when you visit a doctor, the first question is often 'Où avez-vous mal ?' (Where does it hurt?). Being able to answer precisely will make your medical visits much easier!",
    },

    vocabulary: [
      {
        term: "avoir mal à",
        translation: "to have pain in / to hurt",
        pronunciation: "ah-VWAHR mahl ah",
        partOfSpeech: "expression",
        image: "/images/vocab/pain.svg",
        exampleSentence: {
          original: "J'ai mal à la tête.",
          translation: "I have a headache.",
        },
        tip: "The 'à' contracts with articles: à + le = au, à + les = aux.",
      },
      {
        term: "malade",
        translation: "sick / ill",
        pronunciation: "mah-LAHD",
        partOfSpeech: "adjective",
        image: "/images/vocab/sick.svg",
        exampleSentence: {
          original: "Je suis malade.",
          translation: "I am sick.",
        },
        tip: "Same form for masculine and feminine. 'Je suis malade' is how you say you're ill.",
      },
      {
        term: "la fièvre",
        translation: "the fever",
        pronunciation: "lah FYEV-ruh",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/fever.svg",
        exampleSentence: {
          original: "J'ai de la fièvre.",
          translation: "I have a fever.",
        },
        tip: "Use 'avoir de la fièvre' (to have fever), not 'être fièvre'.",
      },
      {
        term: "la douleur",
        translation: "the pain",
        pronunciation: "lah doo-LUR",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/pain-noun.svg",
        exampleSentence: {
          original: "La douleur est forte.",
          translation: "The pain is strong.",
        },
        tip: "More formal than 'avoir mal'. Used by doctors: 'Décrivez la douleur.'",
      },
      {
        term: "tousser",
        translation: "to cough",
        pronunciation: "too-SAY",
        partOfSpeech: "verb",
        image: "/images/vocab/cough.svg",
        exampleSentence: {
          original: "Je tousse beaucoup.",
          translation: "I cough a lot.",
        },
        tip: "Regular -er verb. 'La toux' (the cough) is the noun form.",
      },
      {
        term: "éternuer",
        translation: "to sneeze",
        pronunciation: "ay-tehr-new-AY",
        partOfSpeech: "verb",
        image: "/images/vocab/sneeze.svg",
        exampleSentence: {
          original: "J'éternue souvent.",
          translation: "I sneeze often.",
        },
        tip: "Regular -er verb. Fun fact: the French say 'À tes souhaits !' (To your wishes!) when someone sneezes.",
      },
      {
        term: "fatigué / fatiguée",
        translation: "tired (m/f)",
        pronunciation: "fah-tee-GAY",
        partOfSpeech: "adjective",
        image: "/images/vocab/tired.svg",
        exampleSentence: {
          original: "Je suis très fatigué.",
          translation: "I am very tired.",
        },
        tip: "Add 'e' for feminine: fatigué → fatiguée. Pronunciation stays the same.",
      },
      {
        term: "un rhume",
        translation: "a cold",
        pronunciation: "uhn REWM",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/cold.svg",
        exampleSentence: {
          original: "J'ai un rhume.",
          translation: "I have a cold.",
        },
        tip: "'Attraper un rhume' = to catch a cold. Very common in French winter!",
      },
      {
        term: "se sentir",
        translation: "to feel",
        pronunciation: "suh sahn-TEER",
        partOfSpeech: "verb",
        image: "/images/vocab/feel.svg",
        exampleSentence: {
          original: "Je ne me sens pas bien.",
          translation: "I don't feel well.",
        },
        tip: "Reflexive verb: je me sens, tu te sens, il se sent. Irregular conjugation.",
      },
      {
        term: "avoir besoin de",
        translation: "to need",
        pronunciation: "ah-VWAHR buh-ZWAHN duh",
        partOfSpeech: "expression",
        image: "/images/vocab/need.svg",
        exampleSentence: {
          original: "J'ai besoin d'un médecin.",
          translation: "I need a doctor.",
        },
        tip: "Literally 'to have need of'. Always followed by 'de': j'ai besoin DE...",
      },
    ],

    grammar: [
      {
        title: "The 'Avoir mal à' Structure",
        explanation: "To express pain in French, use 'avoir mal à' + definite article + body part. The preposition 'à' contracts with articles: à + le = au, à + la = à la, à + l' = à l', à + les = aux.",
        examples: [
          {
            original: "J'ai mal au dos.",
            translation: "My back hurts.",
            breakdown: "J'ai mal (I have pain) + au (à + le) + dos (back) — masculine noun",
          },
          {
            original: "Elle a mal à la gorge.",
            translation: "Her throat hurts.",
            breakdown: "Elle a mal (she has pain) + à la + gorge (throat) — feminine noun",
          },
          {
            original: "Il a mal aux yeux.",
            translation: "His eyes hurt.",
            breakdown: "Il a mal (he has pain) + aux (à + les) + yeux (eyes) — plural noun",
          },
        ],
        commonMistakes: [
          "❌ J'ai mal à le dos (wrong — must contract: à + le = au)",
          "✅ J'ai mal au dos (correct contraction)",
          "❌ J'ai mal à les yeux (wrong — must contract: à + les = aux)",
          "✅ J'ai mal aux yeux (correct contraction)",
        ],
      },
      {
        title: "Describing Symptoms",
        explanation: "Beyond 'avoir mal à', you can describe symptoms using: 'je suis malade' (I'm sick), 'j'ai de la fièvre' (I have a fever), 'je tousse' (I cough), 'j'éternue' (I sneeze), 'je ne me sens pas bien' (I don't feel well).",
        examples: [
          {
            original: "Je suis malade. J'ai de la fièvre et je tousse.",
            translation: "I'm sick. I have a fever and I cough.",
            breakdown: "être malade + avoir de la fièvre + tousser — three symptom structures",
          },
          {
            original: "Je ne me sens pas bien. J'ai besoin d'un médecin.",
            translation: "I don't feel well. I need a doctor.",
            breakdown: "ne...pas around reflexive verb + avoir besoin de",
          },
        ],
        commonMistakes: [
          "❌ Je suis fièvre (wrong — use 'avoir', not 'être' for fever)",
          "✅ J'ai de la fièvre (correct — 'avoir' for symptoms)",
          "❌ Je sens pas bien (missing reflexive pronoun)",
          "✅ Je ne me sens pas bien (correct reflexive form)",
        ],
      },
    ],

    dialogue: {
      title: "Calling in Sick",
      context: "Clara calls her boss Marc because she's not feeling well.",
      image: "/images/dialogues/calling-sick.svg",
      lines: [
        {
          speaker: "clara",
          text: "Allô, Marc ? C'est Clara. Je ne me sens pas bien aujourd'hui.",
          translation: "Hello, Marc? It's Clara. I don't feel well today.",
        },
        {
          speaker: "marc",
          text: "Qu'est-ce qui ne va pas ?",
          translation: "What's wrong?",
        },
        {
          speaker: "clara",
          text: "J'ai mal à la tête et à la gorge. Et je tousse beaucoup.",
          translation: "I have a headache and a sore throat. And I cough a lot.",
        },
        {
          speaker: "marc",
          text: "Tu as de la fièvre ?",
          translation: "Do you have a fever?",
        },
        {
          speaker: "clara",
          text: "Oui, un peu. Je suis très fatiguée.",
          translation: "Yes, a little. I'm very tired.",
        },
        {
          speaker: "marc",
          text: "Reste à la maison et repose-toi. Tu as besoin de voir un médecin ?",
          translation: "Stay home and rest. Do you need to see a doctor?",
        },
        {
          speaker: "clara",
          text: "Je pense que j'ai un rhume. Je vais à la pharmacie.",
          translation: "I think I have a cold. I'm going to the pharmacy.",
        },
        {
          speaker: "marc",
          text: "D'accord. Bon rétablissement, Clara !",
          translation: "Okay. Get well soon, Clara!",
        },
      ],
      comprehensionQuestions: [
        {
          question: "What symptoms does Clara have?",
          options: [
            "Headache, sore throat, and cough",
            "Stomachache and back pain",
            "Broken arm and fever",
            "Earache and leg pain",
          ],
          correctIndex: 0,
        },
        {
          question: "Where is Clara going?",
          options: ["To the hospital", "To the doctor", "To the pharmacy", "To work"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "Health Expressions in French",
      text: "The French have many ways to talk about feeling unwell. The most common is 'Je ne me sens pas bien' (I don't feel well). When someone is sick, you say 'Bon rétablissement !' (Get well soon!). When someone sneezes, the French say 'À tes souhaits !' (To your wishes!) for the first sneeze, 'À tes amours !' (To your loves!) for the second, and 'Qu'elles durent toujours !' (May they last forever!) for the third.",
      image: "/images/culture/health-expressions.svg",
      funFact: "🎉 In France, when someone sneezes three times, the full sequence is: 'À tes souhaits ! À tes amours ! Qu'elles durent toujours !' — Wishes, loves, and forever! How romantic!",
    },

    summary: {
      keyPoints: [
        "'Avoir mal à' + article + body part: j'ai mal au dos, à la tête, aux yeux",
        "Contractions: à + le = au, à + les = aux",
        "'Je suis malade' = I'm sick (use 'être')",
        "'J'ai de la fièvre' = I have a fever (use 'avoir')",
        "Symptoms: tousser (cough), éternuer (sneeze), un rhume (cold)",
        "'Je ne me sens pas bien' = I don't feel well",
        "'Bon rétablissement !' = Get well soon!",
      ],
      practicePrompt: "Practice describing symptoms: 'Je suis malade. J'ai mal à la tête. J'ai de la fièvre. Je tousse.' Imagine you're calling your boss to say you're sick!",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "How do you say 'I have a stomachache' in French?",
      content: {
        options: [
          "J'ai mal à la ventre",
          "J'ai mal au ventre",
          "Je suis mal au ventre",
          "J'ai mal le ventre",
        ],
        correctIndex: 1,
      },
      hint: "'Ventre' is masculine — what is 'à + le'?",
      explanation: "'J'ai mal au ventre' — 'au' is the contraction of 'à + le' for masculine nouns.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What does 'Je suis malade' mean?",
      content: {
        options: ["I am tired", "I am sick", "I am hungry", "I am cold"],
        correctIndex: 1,
      },
      hint: "'Malade' is related to the English word 'malady'",
      explanation: "'Je suis malade' = I am sick. Use 'être' (not 'avoir') with 'malade'.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "MATCHING",
      question: "Match the symptoms with their French expressions:",
      content: {
        pairs: [
          { left: "J'ai mal à la tête", right: "I have a headache" },
          { left: "J'ai de la fièvre", right: "I have a fever" },
          { left: "Je tousse", right: "I cough" },
          { left: "J'ai un rhume", right: "I have a cold" },
        ],
      },
      hint: "Match the French symptom to its English meaning",
      explanation: "These are the most common ways to describe symptoms in French.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "J'ai mal ___ yeux.",
        answer: "aux",
        options: ["au", "à la", "aux", "à l'"],
        caseSensitive: false,
      },
      hint: "'Yeux' is plural — what is 'à + les'?",
      explanation: "'Aux' = à + les. J'ai mal aux yeux = My eyes hurt (plural).",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "Je ne me ___ pas bien.",
        answer: "sens",
        options: ["sens", "sent", "sentir", "sente"],
        caseSensitive: false,
      },
      hint: "'Je' takes which form of 'se sentir'?",
      explanation: "'Je me sens' — first person singular of 'se sentir'. Je ne me sens pas bien = I don't feel well.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'I'm sick. I have a fever and a sore throat.'",
      content: {
        correctAnswer: "Je suis malade. J'ai de la fièvre et mal à la gorge.",
        acceptableAnswers: [
          "Je suis malade. J'ai de la fièvre et mal à la gorge",
          "je suis malade. j'ai de la fièvre et mal à la gorge",
          "Je suis malade. J'ai de la fièvre et j'ai mal à la gorge.",
          "Je suis malade. J'ai de la fièvre et j'ai mal à la gorge",
        ],
        direction: "to_target",
      },
      hint: "Combine 'être malade', 'avoir de la fièvre', and 'avoir mal à'",
      explanation: "Three symptom structures combined: être malade + avoir de la fièvre + avoir mal à la gorge.",
      difficulty: "HARD",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in order:",
      content: {
        words: ["besoin", "j'ai", "médecin", "d'un"],
        correctOrder: ["j'ai", "besoin", "d'un", "médecin"],
        translation: "I need a doctor",
      },
      hint: "'Avoir besoin de' = to need",
      explanation: "Correct order: J'ai besoin d'un médecin. (I need a doctor.)",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and select the correct answer:",
      content: {
        ttsText: "Je suis malade. J'ai mal à la gorge et je tousse beaucoup.",
        ttsLang: "fr-FR",
        options: [
          "I'm sick. My throat hurts and I cough a lot.",
          "I'm tired. My head hurts and I sneeze.",
          "I'm sick. My back hurts and I have a fever.",
          "I'm fine. I feel well today.",
        ],
        correctIndex: 0,
      },
      hint: "Listen for 'malade', 'gorge', and 'tousse'",
      explanation: "'Je suis malade. J'ai mal à la gorge et je tousse beaucoup.' = I'm sick. Sore throat and coughing.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 8,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "J'ai mal au ventre et à la tête.",
        targetTranslation: "My stomach and head hurt.",
        acceptableVariants: ["j'ai mal au ventre et à la tête"],
      },
      hint: "Two body parts: 'au ventre' (masculine) and 'à la tête' (feminine)",
      explanation: "Great! You used the correct contractions for both masculine and feminine body parts.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "Je ne me sens pas bien. J'ai besoin d'un médecin.",
        targetTranslation: "I don't feel well. I need a doctor.",
        acceptableVariants: ["je ne me sens pas bien j'ai besoin d'un médecin"],
      },
      hint: "Reflexive negation + avoir besoin de",
      explanation: "Excellent! This is exactly what you'd say in a real medical emergency.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
  ],
};
