export const frenchA1U8L7 = {
  metadata: {
    course: "fr-a1",
    unit: 8,
    lesson: 7,
    title: "French Healthcare System",
    slug: "french-healthcare-system",
    type: "CULTURE",
    estimatedMinutes: 15,
    xpReward: 20,
  },

  content: {
    introduction: {
      text: "In this lesson, you'll learn about the French healthcare system — one of the best in the world. Understanding how healthcare works in France will help you navigate medical situations confidently and appreciate the cultural values behind the system.",
      image: "/images/lessons/healthcare-system.svg",
      culturalNote: "🇫🇷 France's healthcare system was ranked #1 in the world by the World Health Organization. It combines public and private care, giving residents access to high-quality treatment at affordable prices.",
    },

    vocabulary: [
      {
        term: "la Sécurité sociale",
        translation: "the national health insurance",
        pronunciation: "lah say-kew-ree-TAY soh-SYAHL",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/secu.svg",
        exampleSentence: {
          original: "La Sécurité sociale rembourse 70% des frais.",
          translation: "National health insurance reimburses 70% of costs.",
        },
        tip: "Nicknamed 'la Sécu'. Covers all residents of France.",
      },
      {
        term: "une mutuelle",
        translation: "supplementary health insurance",
        pronunciation: "ewn mew-TWEL",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/mutuelle.svg",
        exampleSentence: {
          original: "Ma mutuelle rembourse le reste.",
          translation: "My supplementary insurance covers the rest.",
        },
        tip: "Most French people have a mutuelle in addition to the Sécurité sociale.",
      },
      {
        term: "l'hôpital",
        translation: "the hospital",
        pronunciation: "loh-pee-TAL",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/hospital.svg",
        exampleSentence: {
          original: "Il est à l'hôpital.",
          translation: "He is in the hospital.",
        },
        tip: "Public hospitals are called 'hôpitaux publics'. Private ones: 'cliniques'.",
      },
      {
        term: "les urgences",
        translation: "the emergency room",
        pronunciation: "lay ewr-ZHAHNS",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/emergency.svg",
        exampleSentence: {
          original: "Allez aux urgences !",
          translation: "Go to the emergency room!",
        },
        tip: "For emergencies, call 15 (SAMU), 18 (firefighters), or 112 (European emergency).",
      },
      {
        term: "le SAMU",
        translation: "emergency medical service",
        pronunciation: "luh sah-MEW",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/samu.svg",
        exampleSentence: {
          original: "Appelez le SAMU ! Le numéro est le 15.",
          translation: "Call the emergency service! The number is 15.",
        },
        tip: "SAMU = Service d'Aide Médicale Urgente. Call 15 for medical emergencies in France.",
      },
      {
        term: "un médecin traitant",
        translation: "a family doctor / GP",
        pronunciation: "uhn mayd-SAHN treh-TAHN",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/family-doctor.svg",
        exampleSentence: {
          original: "Mon médecin traitant est le docteur Martin.",
          translation: "My family doctor is Dr. Martin.",
        },
        tip: "In France, you choose a 'médecin traitant' who manages your overall health.",
      },
      {
        term: "rembourser",
        translation: "to reimburse",
        pronunciation: "rahm-boor-SAY",
        partOfSpeech: "verb",
        image: "/images/vocab/reimburse.svg",
        exampleSentence: {
          original: "La Sécu rembourse la consultation.",
          translation: "The health service reimburses the consultation.",
        },
        tip: "Regular -er verb. Key concept in French healthcare — costs are reimbursed, not free.",
      },
      {
        term: "une consultation",
        translation: "a doctor's visit / consultation",
        pronunciation: "ewn kohn-sewl-tah-SYOHN",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/consultation.svg",
        exampleSentence: {
          original: "Une consultation coûte vingt-cinq euros.",
          translation: "A consultation costs twenty-five euros.",
        },
        tip: "Standard GP consultation: €25. Specialist: €30-50+.",
      },
      {
        term: "appeler",
        translation: "to call",
        pronunciation: "ah-puh-LAY",
        partOfSpeech: "verb",
        image: "/images/vocab/call.svg",
        exampleSentence: {
          original: "Appelez le 15 en cas d'urgence !",
          translation: "Call 15 in case of emergency!",
        },
        tip: "Irregular: j'appelle, tu appelles (double 'l' in some forms).",
      },
      {
        term: "en cas d'urgence",
        translation: "in case of emergency",
        pronunciation: "ahn kah dewr-ZHAHNS",
        partOfSpeech: "expression",
        image: "/images/vocab/emergency-case.svg",
        exampleSentence: {
          original: "En cas d'urgence, appelez le 15.",
          translation: "In case of emergency, call 15.",
        },
        tip: "Key emergency numbers: 15 (SAMU), 18 (pompiers/fire), 112 (European).",
      },
    ],

    grammar: [
      {
        title: "Emergency Vocabulary: Numbers and Commands",
        explanation: "In emergencies, you need to know key phone numbers and simple commands. French emergency numbers are different from other countries. The imperative form is used for urgent instructions.",
        examples: [
          {
            original: "Appelez le 15 !",
            translation: "Call 15!",
            breakdown: "Appelez (call — imperative) + le 15 (the number 15 — SAMU)",
          },
          {
            original: "Allez aux urgences !",
            translation: "Go to the emergency room!",
            breakdown: "Allez (go — imperative) + aux urgences (to the ER)",
          },
          {
            original: "C'est une urgence !",
            translation: "It's an emergency!",
            breakdown: "C'est (it is) + une urgence (an emergency)",
          },
        ],
        commonMistakes: [
          "❌ Appelez le 911 (wrong — that's the US number!)",
          "✅ Appelez le 15 (correct — SAMU for medical emergencies in France)",
        ],
      },
      {
        title: "Talking About Healthcare: Key Structures",
        explanation: "To discuss healthcare in French, use structures like 'aller chez/à' (go to), 'rembourser' (reimburse), and 'coûter' (to cost). Healthcare in France operates on a reimbursement model.",
        examples: [
          {
            original: "La consultation coûte vingt-cinq euros.",
            translation: "The consultation costs twenty-five euros.",
            breakdown: "La consultation (the visit) + coûte (costs) + vingt-cinq euros (€25)",
          },
          {
            original: "La Sécu rembourse soixante-dix pour cent.",
            translation: "National insurance reimburses seventy percent.",
            breakdown: "La Sécu (health insurance) + rembourse (reimburses) + 70%",
          },
        ],
        commonMistakes: [
          "❌ La santé est gratuite en France (not exactly — it's reimbursed, not free)",
          "✅ La Sécu rembourse la plupart des frais (correct — most costs are reimbursed)",
        ],
      },
    ],

    dialogue: {
      title: "Explaining the Healthcare System",
      context: "Sophie explains the French healthcare system to her American friend Lucas.",
      image: "/images/dialogues/healthcare-explain.svg",
      lines: [
        {
          speaker: "lucas",
          text: "Comment marche le système de santé en France ?",
          translation: "How does the healthcare system work in France?",
        },
        {
          speaker: "sophie",
          text: "C'est simple. Tout le monde a la Sécurité sociale. Elle rembourse environ 70% des frais médicaux.",
          translation: "It's simple. Everyone has national health insurance. It reimburses about 70% of medical costs.",
        },
        {
          speaker: "lucas",
          text: "Et les 30% restants ?",
          translation: "And the remaining 30%?",
        },
        {
          speaker: "sophie",
          text: "La plupart des gens ont une mutuelle. Elle rembourse le reste.",
          translation: "Most people have supplementary insurance. It covers the rest.",
        },
        {
          speaker: "lucas",
          text: "Et en cas d'urgence ?",
          translation: "And in case of emergency?",
        },
        {
          speaker: "sophie",
          text: "On appelle le 15 pour le SAMU ou on va aux urgences à l'hôpital.",
          translation: "You call 15 for the emergency service or go to the ER at the hospital.",
        },
        {
          speaker: "lucas",
          text: "C'est vraiment bien organisé !",
          translation: "It's really well organized!",
        },
        {
          speaker: "sophie",
          text: "Oui ! Et une consultation chez le médecin coûte seulement vingt-cinq euros.",
          translation: "Yes! And a doctor's visit costs only twenty-five euros.",
        },
      ],
      comprehensionQuestions: [
        {
          question: "What percentage does the Sécurité sociale reimburse?",
          options: ["50%", "60%", "70%", "100%"],
          correctIndex: 2,
        },
        {
          question: "What number do you call for medical emergencies in France?",
          options: ["911", "999", "15", "18"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "Healthcare in France: A National Pride",
      text: "The French healthcare system is a source of national pride. Created after World War II, it is based on the principle that everyone deserves access to quality healthcare. The system operates on a reimbursement model: you pay upfront and get reimbursed. The 'carte vitale' makes this process almost automatic. France has more doctors, pharmacies, and hospital beds per capita than most European countries. Emergency care is always available through the SAMU (call 15), pompiers/firefighters (call 18), or the European number (112). French hospitals are generally excellent, and waiting times — while not zero — are reasonable compared to many countries.",
      image: "/images/culture/healthcare-pride.svg",
      funFact: "🎉 The French fire brigade (pompiers) also functions as an emergency medical service! If you call 18 for the fire department, they send paramedics too. In fact, the Paris fire brigade (Brigade de Sapeurs-Pompiers) is actually part of the French Army!",
    },

    summary: {
      keyPoints: [
        "La Sécurité sociale ('la Sécu') = national health insurance — reimburses ~70%",
        "Une mutuelle = supplementary insurance — covers the remaining ~30%",
        "La carte vitale = health insurance card (green card with chip)",
        "Emergency numbers: 15 (SAMU), 18 (pompiers), 112 (European)",
        "Standard GP consultation: €25",
        "Un médecin traitant = family doctor / GP",
        "Healthcare is reimbursed, not completely free",
      ],
      practicePrompt: "Imagine explaining French healthcare to a friend. Practice: 'En France, tout le monde a la Sécurité sociale. Elle rembourse 70%. En cas d'urgence, on appelle le 15.'",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What is the emergency medical number in France?",
      content: {
        options: ["911", "999", "15", "112"],
        correctIndex: 2,
      },
      hint: "It's the SAMU number",
      explanation: "In France, call 15 for SAMU (medical emergencies). 112 also works (European number).",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What does 'la carte vitale' do?",
      content: {
        options: [
          "It's a credit card",
          "It stores health insurance information",
          "It's a library card",
          "It's a travel pass",
        ],
        correctIndex: 1,
      },
      hint: "It's a green card you bring to the doctor and pharmacy",
      explanation: "'La carte vitale' is the French health insurance card — it stores your healthcare information.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "MATCHING",
      question: "Match the French healthcare terms with their meanings:",
      content: {
        pairs: [
          { left: "la Sécurité sociale", right: "national health insurance" },
          { left: "une mutuelle", right: "supplementary insurance" },
          { left: "les urgences", right: "emergency room" },
          { left: "un médecin traitant", right: "family doctor" },
        ],
      },
      hint: "Think about the different parts of the healthcare system",
      explanation: "Sécu = national insurance, mutuelle = supplementary, urgences = ER, médecin traitant = GP.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "En cas d'urgence, ___ le 15.",
        answer: "appelez",
        options: ["appelez", "appeler", "appelle", "appellent"],
        caseSensitive: false,
      },
      hint: "Imperative 'vous' form of 'appeler'",
      explanation: "'Appelez le 15' — imperative form for emergency instructions.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "La Sécu ___ environ 70% des frais.",
        answer: "rembourse",
        options: ["rembourse", "rembourses", "remboursent", "rembourser"],
        caseSensitive: false,
      },
      hint: "'La Sécu' is singular — third person",
      explanation: "'La Sécu rembourse' — third person singular of 'rembourser'.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'It's an emergency! Call 15!'",
      content: {
        correctAnswer: "C'est une urgence ! Appelez le 15 !",
        acceptableAnswers: [
          "C'est une urgence ! Appelez le 15 !",
          "C'est une urgence ! Appelez le 15",
          "C'est une urgence! Appelez le 15!",
          "c'est une urgence appelez le 15",
        ],
        direction: "to_target",
      },
      hint: "Two short sentences: statement + command",
      explanation: "'C'est une urgence ! Appelez le 15 !' — essential emergency French.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in order:",
      content: {
        words: ["urgences", "aux", "allez", "l'hôpital", "de"],
        correctOrder: ["allez", "aux", "urgences", "de", "l'hôpital"],
        translation: "Go to the hospital emergency room",
      },
      hint: "Imperative verb first, then destination",
      explanation: "Correct order: Allez aux urgences de l'hôpital. (Go to the hospital ER.)",
      difficulty: "HARD",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and select the correct answer:",
      content: {
        ttsText: "En France, tout le monde a la Sécurité sociale. Une consultation coûte vingt-cinq euros.",
        ttsLang: "fr-FR",
        options: [
          "In France, everyone has national health insurance. A consultation costs €25.",
          "In France, healthcare is free. A consultation costs €50.",
          "In France, only workers have insurance. A consultation costs €100.",
          "In France, you need private insurance. A consultation costs €25.",
        ],
        correctIndex: 0,
      },
      hint: "Listen for 'tout le monde', 'Sécurité sociale', and 'vingt-cinq euros'",
      explanation: "Key facts: universal coverage through Sécurité sociale, standard GP visit €25.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 8,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "En cas d'urgence, appelez le quinze.",
        targetTranslation: "In case of emergency, call 15.",
        acceptableVariants: ["en cas d'urgence appelez le quinze"],
      },
      hint: "This could save a life — practice it well!",
      explanation: "Great! 'Appelez le 15' — the most important emergency phrase in France.",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "La Sécurité sociale rembourse soixante-dix pour cent.",
        targetTranslation: "National health insurance reimburses 70%.",
        acceptableVariants: ["la sécurité sociale rembourse soixante-dix pour cent"],
      },
      hint: "A key fact about French healthcare",
      explanation: "Excellent! You can now explain the basics of French healthcare.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
  ],
};
