export const frenchA1U8L1 = {
  metadata: {
    course: "fr-a1",
    unit: 8,
    lesson: 1,
    title: "Body Parts",
    slug: "body-parts",
    type: "VOCABULARY",
    estimatedMinutes: 15,
    xpReward: 20,
  },

  content: {
    introduction: {
      text: "In this lesson, you'll learn the French words for body parts. This vocabulary is essential for describing pain, visiting the doctor, and talking about health. Knowing body parts will also help you understand common French expressions!",
      image: "/images/lessons/body-parts.svg",
      culturalNote: "🇫🇷 The French have many expressions using body parts: 'avoir le bras long' (to have a long arm = to have influence), 'coûter les yeux de la tête' (to cost the eyes from the head = to be very expensive)!",
    },

    vocabulary: [
      {
        term: "la tête",
        translation: "the head",
        pronunciation: "lah TET",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/head.svg",
        exampleSentence: {
          original: "J'ai mal à la tête.",
          translation: "I have a headache.",
        },
        tip: "'Avoir mal à la tête' is one of the most common health complaints in French.",
      },
      {
        term: "le ventre",
        translation: "the stomach / belly",
        pronunciation: "luh VAHN-truh",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/stomach.svg",
        exampleSentence: {
          original: "J'ai mal au ventre.",
          translation: "I have a stomachache.",
        },
        tip: "'L'estomac' is the anatomical stomach. 'Le ventre' is more casual and common.",
      },
      {
        term: "le dos",
        translation: "the back",
        pronunciation: "luh DOH",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/back.svg",
        exampleSentence: {
          original: "Mon dos me fait mal.",
          translation: "My back hurts.",
        },
        tip: "The 's' is silent. 'Mal de dos' (back pain) is very common in French.",
      },
      {
        term: "le bras",
        translation: "the arm",
        pronunciation: "luh BRAH",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/arm.svg",
        exampleSentence: {
          original: "J'ai mal au bras droit.",
          translation: "My right arm hurts.",
        },
        tip: "The 's' is silent. Plural: 'les bras' (same pronunciation).",
      },
      {
        term: "la jambe",
        translation: "the leg",
        pronunciation: "lah ZHAHMB",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/leg.svg",
        exampleSentence: {
          original: "Elle a mal à la jambe.",
          translation: "Her leg hurts.",
        },
        tip: "Don't confuse with 'le jambon' (ham) — though they share a root!",
      },
      {
        term: "la main",
        translation: "the hand",
        pronunciation: "lah MAHN",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/hand.svg",
        exampleSentence: {
          original: "Je me lave les mains.",
          translation: "I wash my hands.",
        },
        tip: "In French, you wash 'the hands' (les mains), not 'my hands'.",
      },
      {
        term: "le pied",
        translation: "the foot",
        pronunciation: "luh PYAY",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/foot.svg",
        exampleSentence: {
          original: "J'ai mal au pied gauche.",
          translation: "My left foot hurts.",
        },
        tip: "'À pied' means 'on foot': 'Je vais à pied' (I go on foot).",
      },
      {
        term: "la gorge",
        translation: "the throat",
        pronunciation: "lah GORZH",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/throat.svg",
        exampleSentence: {
          original: "J'ai mal à la gorge.",
          translation: "I have a sore throat.",
        },
        tip: "Very common in winter! 'Avoir mal à la gorge' = to have a sore throat.",
      },
      {
        term: "le genou",
        translation: "the knee",
        pronunciation: "luh zhuh-NOO",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/knee.svg",
        exampleSentence: {
          original: "Mon genou est blessé.",
          translation: "My knee is injured.",
        },
        tip: "Plural: 'les genoux' (add 'x', not 's'). One of the irregular plurals.",
      },
      {
        term: "l'oreille",
        translation: "the ear",
        pronunciation: "loh-RAY-yuh",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/ear.svg",
        exampleSentence: {
          original: "J'ai mal à l'oreille.",
          translation: "My ear hurts.",
        },
        tip: "Feminine noun. 'Les oreilles' = the ears.",
      },
      {
        term: "le cœur",
        translation: "the heart",
        pronunciation: "luh KUR",
        partOfSpeech: "noun",
        gender: "masculine",
        image: "/images/vocab/heart.svg",
        exampleSentence: {
          original: "Mon cœur bat vite.",
          translation: "My heart is beating fast.",
        },
        tip: "Also used figuratively: 'avoir bon cœur' (to have a good heart = to be kind).",
      },
      {
        term: "la bouche",
        translation: "the mouth",
        pronunciation: "lah BOOSH",
        partOfSpeech: "noun",
        gender: "feminine",
        image: "/images/vocab/mouth.svg",
        exampleSentence: {
          original: "Ouvrez la bouche, s'il vous plaît.",
          translation: "Open your mouth, please.",
        },
        tip: "A doctor will say this during an examination!",
      },
    ],

    grammar: [
      {
        title: "Body Parts with Definite Articles",
        explanation: "In French, when talking about body parts (especially with reflexive verbs or 'avoir mal'), you use the definite article (le/la/les) instead of possessive adjectives. The French say 'I wash THE hands' not 'I wash MY hands'.",
        examples: [
          {
            original: "Je me lave les mains.",
            translation: "I wash my hands.",
            breakdown: "Je me lave (I wash myself) + les mains (the hands) — NOT 'mes mains'",
          },
          {
            original: "J'ai mal à la tête.",
            translation: "I have a headache.",
            breakdown: "J'ai mal (I have pain) + à la tête (in the head) — definite article",
          },
        ],
        commonMistakes: [
          "❌ Je me lave mes mains (wrong — use definite article with body parts)",
          "✅ Je me lave les mains (correct — 'les' not 'mes')",
        ],
      },
    ],

    dialogue: {
      title: "At the Sports Club",
      context: "Hugo has hurt himself playing football. He tells Sophie about his injuries.",
      image: "/images/dialogues/sports-injury.svg",
      lines: [
        {
          speaker: "sophie",
          text: "Hugo, ça va ? Tu as l'air fatigué !",
          translation: "Hugo, are you okay? You look tired!",
        },
        {
          speaker: "hugo",
          text: "Non, j'ai mal partout ! J'ai joué au football hier.",
          translation: "No, I hurt everywhere! I played football yesterday.",
        },
        {
          speaker: "sophie",
          text: "Où est-ce que tu as mal ?",
          translation: "Where does it hurt?",
        },
        {
          speaker: "hugo",
          text: "J'ai mal à la jambe et au genou droit.",
          translation: "My leg and right knee hurt.",
        },
        {
          speaker: "sophie",
          text: "Et ton bras ?",
          translation: "And your arm?",
        },
        {
          speaker: "hugo",
          text: "Oui, j'ai mal au bras aussi. Et j'ai mal à la tête.",
          translation: "Yes, my arm hurts too. And I have a headache.",
        },
        {
          speaker: "sophie",
          text: "Tu dois aller chez le médecin !",
          translation: "You should go to the doctor!",
        },
        {
          speaker: "hugo",
          text: "Tu as raison. J'ai vraiment mal au dos aussi.",
          translation: "You're right. My back really hurts too.",
        },
      ],
      comprehensionQuestions: [
        {
          question: "What sport did Hugo play?",
          options: ["Tennis", "Football", "Basketball", "Rugby"],
          correctIndex: 1,
        },
        {
          question: "Where does Hugo NOT have pain?",
          options: ["His leg", "His head", "His stomach", "His back"],
          correctIndex: 2,
        },
      ],
    },

    culture: {
      title: "Health and the Body in French Culture",
      text: "The French are very open about discussing health. It's common to describe your symptoms in detail, and pharmacists are trained to give health advice. Body-related expressions are everywhere in French: 'avoir le cœur sur la main' (to have the heart on the hand = to be generous), 'avoir la tête dans les nuages' (to have the head in the clouds = to be a daydreamer).",
      image: "/images/culture/health-body.svg",
      funFact: "🎉 The French expression 'avoir la chair de poule' literally means 'to have chicken flesh' — it's the French way of saying 'to have goosebumps'!",
    },

    summary: {
      keyPoints: [
        "Key body parts: la tête, le ventre, le dos, le bras, la jambe",
        "More body parts: la main, le pied, la gorge, le genou, l'oreille",
        "Use definite articles (le/la/les) with body parts, not possessives",
        "'J'ai mal à...' = I have pain in... (coming up in detail next lesson!)",
        "Irregular plural: le genou → les genoux (x, not s)",
      ],
      practicePrompt: "Point to different body parts and name them in French. Try: 'la tête, le bras, la jambe...' Then practice: 'J'ai mal à la tête, j'ai mal au dos.'",
    },
  },

  exercises: [
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "What does 'la tête' mean?",
      content: {
        options: ["The hand", "The head", "The foot", "The arm"],
        correctIndex: 1,
      },
      hint: "It's at the top of your body",
      explanation: "'La tête' means 'the head'. 'J'ai mal à la tête' = I have a headache.",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 1,
    },
    {
      exercise_type: "MULTIPLE_CHOICE",
      question: "Which body part is 'le genou'?",
      content: {
        options: ["The elbow", "The knee", "The ankle", "The shoulder"],
        correctIndex: 1,
      },
      hint: "It bends when you walk",
      explanation: "'Le genou' means 'the knee'. Plural: 'les genoux' (with 'x').",
      difficulty: "EASY",
      xp_reward: 2,
      order_index: 2,
    },
    {
      exercise_type: "MATCHING",
      question: "Match the French body parts with their meanings:",
      content: {
        pairs: [
          { left: "le bras", right: "the arm" },
          { left: "la jambe", right: "the leg" },
          { left: "le dos", right: "the back" },
          { left: "la gorge", right: "the throat" },
        ],
      },
      hint: "Think about where each body part is located",
      explanation: "Bras = arm, jambe = leg, dos = back, gorge = throat.",
      difficulty: "EASY",
      xp_reward: 5,
      order_index: 3,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "J'ai mal à ___ tête.",
        answer: "la",
        options: ["la", "le", "ma", "mon"],
        caseSensitive: false,
      },
      hint: "Use the definite article, not the possessive, with body parts",
      explanation: "'J'ai mal à la tête' — use definite articles (la/le/les) with body parts, not possessives.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 4,
    },
    {
      exercise_type: "FILL_BLANK",
      question: "Complete the sentence:",
      content: {
        sentence: "Elle a mal ___ ventre.",
        answer: "au",
        options: ["au", "à la", "à l'", "aux"],
        caseSensitive: false,
      },
      hint: "'Ventre' is masculine — what is 'à + le'?",
      explanation: "'Au' = à + le. 'Elle a mal au ventre' = She has a stomachache.",
      difficulty: "MEDIUM",
      xp_reward: 3,
      order_index: 5,
    },
    {
      exercise_type: "TRANSLATION",
      question: "Translate to French: 'My back hurts.'",
      content: {
        correctAnswer: "J'ai mal au dos.",
        acceptableAnswers: ["J'ai mal au dos", "j'ai mal au dos"],
        direction: "to_target",
      },
      hint: "Use 'avoir mal à' + definite article + body part",
      explanation: "'J'ai mal au dos.' — 'au' because 'dos' is masculine.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 6,
    },
    {
      exercise_type: "REORDER",
      question: "Put the words in order:",
      content: {
        words: ["la", "mal", "gorge", "à", "j'ai"],
        correctOrder: ["j'ai", "mal", "à", "la", "gorge"],
        translation: "I have a sore throat",
      },
      hint: "Start with 'j'ai mal à...'",
      explanation: "Correct order: J'ai mal à la gorge. (I have a sore throat.)",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 7,
    },
    {
      exercise_type: "LISTENING",
      question: "Listen and select the correct answer:",
      content: {
        ttsText: "J'ai mal à la jambe et au genou.",
        ttsLang: "fr-FR",
        options: [
          "My leg and knee hurt",
          "My arm and hand hurt",
          "My head and back hurt",
          "My throat and ear hurt",
        ],
        correctIndex: 0,
      },
      hint: "Listen for 'jambe' and 'genou'",
      explanation: "'J'ai mal à la jambe et au genou' = My leg and knee hurt.",
      difficulty: "MEDIUM",
      xp_reward: 4,
      order_index: 8,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "J'ai mal à la tête.",
        targetTranslation: "I have a headache.",
        acceptableVariants: ["j'ai mal à la tête"],
      },
      hint: "This is the most common health complaint in French",
      explanation: "Great! 'J'ai mal à la tête' — you'll use this phrase often!",
      difficulty: "MEDIUM",
      xp_reward: 5,
      order_index: 9,
    },
    {
      exercise_type: "SPEAK",
      question: "Say this sentence out loud:",
      content: {
        targetText: "J'ai mal au dos et à la gorge.",
        targetTranslation: "My back and throat hurt.",
        acceptableVariants: ["j'ai mal au dos et à la gorge"],
      },
      hint: "Two body parts: 'au dos' (masculine) and 'à la gorge' (feminine)",
      explanation: "Excellent! You combined two body parts with correct articles.",
      difficulty: "HARD",
      xp_reward: 5,
      order_index: 10,
    },
  ],
};
